"""
card_scoring.py — Heuristic card scoring for deck-building decisions.

Scores each card 0-10 based on damage/block/cost efficiency, special effects,
and synergy potential. Used by greedy_action() for card_reward, shop, and
card_select (removal) decisions.
"""
import json as _json
import os as _os

# === Empirical bonus from gameplay statistics ===
# Generated by agent/collect_deck_stats.py: log-ratio of card frequency in
# boss-reach decks vs early-died decks. Cards that empirically correlate with
# reaching the boss get a positive bonus (capped ±1.5). Re-run that script
# whenever the policy or strategy shifts substantially to refresh the data.
_EMPIRICAL_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", "data", "card_empirical.json")
try:
    with open(_EMPIRICAL_PATH) as _ef:
        EMPIRICAL_BONUS = _json.load(_ef)
except (FileNotFoundError, ValueError):
    EMPIRICAL_BONUS = {}

# Empirical bonus DISABLED (Run 23 retry showed avg_floor regression
# 14.3 → 9.9 vs Run 22 baseline despite weight=0.3 / min_magnitude=0.5
# settings). The data was collected from 3706k's own gameplay, so even
# small bonuses reinforced existing biases and caused the policy to drift
# off the verified-good Run 22 working point. Set weight=0.0 to disable
# without removing the data file; flip back if a future run uses externally
# collected stats (e.g. from a *different* policy or human play).
EMPIRICAL_WEIGHT = 0.0
EMPIRICAL_MIN_MAGNITUDE = 0.5

# Manual overrides for known high/low value cards.
# Cards not listed get scored by the generic formula.
OVERRIDES: dict[str, float] = {
    # === Ironclad top picks (9-10) ===
    "FEED": 9.5,            # kill an enemy → heal + max HP
    "DEMON_FORM": 9.5,      # +2 str/turn is game-winning
    "CORRUPTION": 9.0,      # skills cost 0, insane with dead branch
    "BRIMSTONE": 9.0,       # +2 str/turn, low downside for Ironclad
    "LIMIT_BREAK": 9.0,     # double strength
    "IMPERVIOUS": 9.0,      # 30 block
    "OFFERING": 8.5,        # draw + energy, life cost is fine
    "DARK_EMBRACE": 8.5,    # draw on exhaust synergy
    "FEEL_NO_PAIN": 8.5,    # block on exhaust
    "JUGGERNAUT": 8.5,      # each block = damage — game-winning in block-heavy decks
    "SENTINEL": 8.0,        # 3 energy if exhausted
    "SECOND_WIND": 8.0,     # exhaust + block
    "TRUE_GRIT": 7.5,       # exhaust 1, draw 2
    "WARCRY": 7.0,          # draw with no downside
    "SHRUG_IT_OFF": 8.0,    # 8 block + draw 1
    "SPOT_WEAKNESS": 6.5,   # +3 str if enemy attacking — strong conditional
    "BRUTALITY": 5.5,       # 0-cost draw at 1 HP/turn — aggressive cycle

    # === STS2 new cards — top picks (8-9) ===
    "HOWL_FROM_BEYOND": 9.0,   # AOE that auto-replays from exhaust pile each turn
    "APOTHEOSIS": 9.0,         # upgrade ALL cards (colorless) — enormous value
    "AGGRESSION": 8.5,         # power: free upgraded Attack from discard each turn
    "ADRENALINE": 8.0,         # 0-cost: gain 1 energy + draw 2 (no HP cost in STS2)
    "SHOCKWAVE": 7.5,          # AOE Weak + Vulnerable to all enemies — huge setup
    "FORGOTTEN_RITUAL": 8.0,   # gain energy when exhaust — capped (generic formula over-scores)
    "HELLRAISER": 8.0,         # auto-plays Strike on draw — free attacks all game
    "MOLTEN_FIST": 8.0,        # doubles target's Vulnerable — huge damage multiplier
    "DISMANTLE": 7.5,          # 13 dmg; hits twice if Vulnerable (26 for 1 energy)
    "BLADE_OF_INK": 6.0,       # this turn: +1 str per Attack — scales with attack-heavy turns
    "POMMEL_STRIKE": 7.5,      # 9 dmg + draw 1 (generic formula gives 8.5, slightly lower)
    "UNRELENTING": 7.5,        # 12 dmg + next Attack costs 0 — energy generation
    "BLUDGEON": 7.5,           # simple heavy single-target damage
    "SETUP_STRIKE": 7.0,       # 9 dmg + temporary strength this turn
    "GRAPPLE": 7.0,            # dmg + deals extra per block gained this turn
    "VICIOUS": 6.5,            # draw when you apply Vulnerable
    "INFERNAL_BLADE": 7.0,     # add free random Attack to hand
    "PERFECTED_STRIKE": 6.5,   # scales with Strike count (good early, less later)
    "CINDER": 5.5,             # dmg + forced exhaust top of draw (can trash good card)
    "BLOOD_WALL": 4.0,         # HP loss for block — net negative, avoid
    "BREAKTHROUGH": 6.0,       # AOE but costs HP — trade-off
    "EVIL_EYE": 6.0,           # block + extra block on exhaust — conditional
    "DOMINATE": 6.5,           # apply Vuln + gain Str per Vuln on enemy — strong offensive
    "TAUNT": 7.0,              # block + apply Vulnerable — efficient dual-purpose skill
    "JUGGLING": 5.5,           # power: add copy of 3rd Attack played each turn — free attacks
    "EXPECT_A_FIGHT": 5.0,     # gain 1 energy per Attack in hand — strong in attack-heavy decks
    "ASHEN_STRIKE": 5.0,       # damage scales with exhaust pile — strong with exhaust synergy
    "TREMBLE": 4.5,            # 1-cost Apply Vulnerable — combo piece with attack-heavy deck
    "RUPTURE": 4.5,            # power: +1 Str when losing HP from card — synergy with OFFERING/BRUTALITY
    "FEROCITY": 6.5,           # power: +1 Str per Attack played — snowballs in attack-heavy deck
    "HEARTSEEKER": 7.0,        # 8 dmg + 1 Vulnerable — efficient attack/debuff combo
    "OBLITERATE": 7.5,         # 20 dmg Exhaust — high single-hit for 1 energy
    "PREDATOR": 6.5,           # 15 dmg + conditional draw — good damage with upside

    # === Strong cards (7-8) ===
    "BARRICADE": 8.5,        # block persists between turns — enables massive block stacking
    "CARNAGE": 7.5,         # 20 damage for free (ethereal)
    "RECKLESS_CHARGE": 7.0, # 7 dmg + wound, still good DPE
    "CLEAVE": 7.0,          # AOE 8 damage
    "UPPERCUT": 7.5,        # 13 dmg + vuln + weak
    "PUMMEL": 7.0,          # multi-hit with str scaling
    "BURNING_PACT": 7.0,   # draw 2 + exhaust
    "INFLAME": 8.0,         # +2 str (power, persistent)
    "METALLICIZE": 7.5,     # +3 block/turn (power)
    "BATTLE_TRANCE": 7.0,   # draw 3
    "BLOODLETTING": 7.0,    # free energy
    "RAGE": 7.0,            # block on attack plays
    "DROPKICK": 8.0,        # 5 dmg + draw + energy if vuln target
    "WHIRLWIND": 1.0,       # X-cost AOE — causes NullRef crash in headless (BUG-034)
    "HEAVY_BLADE": 7.0,     # scales with str (3x multiplier)
    "SWORD_BOOMERANG": 7.0, # 3x3 random hits
    "CLASH": 6.5,           # 0-cost, 14 dmg — great in attack-heavy decks
    "BEAT_DOWN": 7.0,       # play N attacks from discard — strong reuse with good attacks
    "ANOINTED": 6.0,        # put all rares from draw pile into hand — useful mid/late game

    # === STS2 colorless decent picks (5-7) ===
    "DRAMATIC_ENTRANCE": 7.0,  # free AOE damage on combat start (Ethereal, costs 0)
    "METAMORPHOSIS": 6.5,   # add N free Attacks to draw pile — extra resources
    "BEAT_INTO_SHAPE": 6.5, # damage that scales with hits this turn — strong multi-hit
    "PANACHE": 6.0,         # power: AOE damage every 5 cards played
    "MASTER_OF_STRATEGY": 6.0, # draw 3, exhaust — card advantage
    "ANGER": 5.0,           # damage + copy in discard (scaling but clogs deck)
    "DARK_SHACKLES": 4.5,   # reduce enemy strength this turn — situational defensive
    "BLIGHT_STRIKE": 5.0,   # damage + apply Doom — Doom may not tick in headless (BUG-021)
    "DISCOVERY": 5.5,       # choose 1 of 3 random cards free — card quality upgrade
    "JACK_OF_ALL_TRADES": 5.0,  # add random colorless cards — inconsistent

    # === Decent cards (5-6) ===
    "ANGELIC_DEW": 5.5,
    "ARMAMENTS": 6.0,       # upgrade hand
    "BASH": 6.0,            # starter but vulnerable is good
    "BLOOD_FOR_BLOOD": 6.0,
    "BODY_SLAM": 6.5,       # scales with block
    "CLOTHESLINE": 5.5,     # 12 dmg + weak
    "COMBUST": 5.5,
    "ENTRENCH": 5.5,
    "FIEND_FIRE": 6.0,
    "FLEX": 5.0,
    "HAVOC": 5.5,
    "HEADBUTT": 5.5,        # 9 dmg + put card back on draw
    "HEMOKINESIS": 6.0,
    "IRON_WAVE": 5.5,       # 5 dmg + 5 block for 1
    "POWER_THROUGH": 6.0,  # 15 block, adds wounds
    "PUNCTURE": 5.0,
    "RAMPAGE": 5.5,
    "SEARING_BLOW": 5.0,   # needs upgrades
    "SEVER_SOUL": 5.5,
    "THUNDERCLAP": 7.0,    # AOE damage + Vulnerable to ALL enemies (strong setup)
    "TWIN_STRIKE": 6.0,    # 5x2 = 10 for 1
    "WILD_STRIKE": 5.5,    # 12 dmg, wound to draw

    # === Mediocre (3-4) ===
    "DEFEND": 3.0,          # basic, want to remove
    "DEFEND_IRONCLAD": 3.0,
    "DEFEND_SILENT": 3.0,
    "DEFEND_DEFECT": 3.0,
    "STRIKE": 2.0,          # basic, want to remove
    "STRIKE_IRONCLAD": 2.0,
    "STRIKE_SILENT": 2.0,
    "STRIKE_DEFECT": 2.0,
    "WOUND": 1.0,           # pure bad
    "DAZE": 1.0,
    "SLIMED": 1.0,
    "BURN": 0.5,
}

# Type-based generic scoring weights
ATTACK_DPE_BASELINE = 6.0   # Strike: 6 dmg / 1 cost
BLOCK_BPE_BASELINE = 5.0    # Defend: 5 block / 1 cost
DRAW_VALUE = 2.5            # per card drawn — Run 22 verified (3.0 caused regression in Run 24)
ENERGY_VALUE = 5.0          # per energy generated — Run 22 verified
LOW_COST_BONUS = 0.0        # 0-cost universal bonus — disabled after Run 24 showed
                            # avg_floor 14.3→11.2 regression. The bonus pulled the policy
                            # toward cheap utility cards at expense of damage. Re-enable
                            # only with stronger filtering (e.g. only when paired with draw/energy).
ONE_COST_BONUS = 0.0
VULN_WEAK_VALUE = 1.5       # vulnerable or weak bonus
STRENGTH_VALUE = 2.5        # per point of strength
DEXTERITY_VALUE = 2.0       # per point of dexterity
EXHAUST_VALUE = 1.0         # exhaust synergy bonus
AOE_VALUE = 1.5             # AOE bonus
POWER_BONUS = 1.5           # powers persist, extra value
RARITY_BONUS = {"Common": 0.0, "Uncommon": 0.5, "Rare": 1.0}

# Threshold above which an un-upgraded card should be a SMITH target at the next
# rest site. Calibrated so DEMON_FORM/BARRICADE/HOWL_FROM_BEYOND/LIMIT_BREAK and
# top draw/energy enablers (OFFERING/SHRUG_IT_OFF/POMMEL_STRIKE) all qualify, but
# common Strike/Defend variants do not.
SMITH_PRIORITY_THRESHOLD = 7.0

# Cards that are never worth picking (status/curse starters)
SKIP_IDS = {"STRIKE_R", "DEFEND_R", "STRIKE_B", "DEFEND_B", "STRIKE_G",
            "DEFEND_G", "WOUND", "DAZE", "SLIMED", "BURN", "DECAY",
            # STS2 naming variants
            "STRIKE_IRONCLAD", "DEFEND_IRONCLAD",
            "STRIKE_SILENT", "DEFEND_SILENT",
            "STRIKE_DEFECT", "DEFEND_DEFECT",
            # STS2 curses/status cards
            "DOUBT", "REGRET", "SHAME", "VOID", "NORMALITY"}


def score_card(card: dict) -> float:
    """Score a card 0-10 based on its effectiveness.

    card: dict with keys: id, cost, type, rarity, stats, name, keywords
    """
    card_id = card.get("id", "")
    if isinstance(card_id, dict):
        card_id = card_id.get("en", str(card_id))
    card_id = card_id.upper().strip()
    # Game prefixes IDs with "CARD." — strip it for override lookups
    if card_id.startswith("CARD."):
        card_id = card_id[5:]

    # Check manual override first — but DO still apply empirical bonus below
    # so the data-driven signal can nudge override values up/down.
    if card_id in OVERRIDES:
        score = OVERRIDES[card_id]
        if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
            _eb = EMPIRICAL_BONUS[card_id]
            if abs(_eb) >= EMPIRICAL_MIN_MAGNITUDE:
                score += _eb * EMPIRICAL_WEIGHT
        return max(0.0, min(score, 10.0))

    # Skip status/curse cards
    if card_id in SKIP_IDS:
        return 0.0

    raw_cost = card.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        raw_cost = 1
    cost = max(raw_cost, 1)  # treat 0-cost as 1 for ratio calc
    ctype = (card.get("type") or "").lower()
    rarity = card.get("rarity", "Common")
    stats = card.get("stats") or {}
    name = card.get("name", "")
    if isinstance(name, dict):
        name = name.get("en", "")

    score = 0.0
    # Low-cost combo bonus — 0-cost cards stack in high-energy turns,
    # 1-cost cards still cycle cheaply. Boss wins correlate with playing
    # many cards per turn, and cost is the gate.
    if raw_cost == 0:
        score += LOW_COST_BONUS
    elif raw_cost == 1:
        score += ONE_COST_BONUS

    # === Attack cards: score by damage per energy ===
    if ctype == "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            dpe = damage / cost
            score += min(dpe / ATTACK_DPE_BASELINE * 5.0, 7.0)

    # === Skill cards: score by block, draw, energy ===
    elif ctype == "skill":
        block = stats.get("block", 0)
        if block > 0:
            bpe = block / cost
            score += min(bpe / BLOCK_BPE_BASELINE * 4.0, 5.0)

    # === Power cards: base value + effect scoring ===
    elif ctype == "power":
        score += POWER_BONUS
        # Powers with str/dex are very strong
        if "strength" in str(stats).lower() or "str" in str(stats).lower():
            score += STRENGTH_VALUE
        if "dexterity" in str(stats).lower() or "dex" in str(stats).lower():
            score += DEXTERITY_VALUE

    # === Generic bonuses ===
    # Draw value
    draw = stats.get("draw", 0)
    if draw > 0:
        score += draw * DRAW_VALUE

    # Energy generation
    energy = stats.get("energy", 0)
    if energy > 0:
        score += energy * ENERGY_VALUE

    # Block on any card (not just skills)
    if ctype != "skill":
        block = stats.get("block", 0)
        if block > 0:
            score += min(block / cost * 0.5, 3.0)

    # Damage on non-attack cards
    if ctype != "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            score += min(damage / cost * 0.5, 3.0)

    # Check keywords/description for effects
    desc = str(card.get("description", "")).lower()
    if "vulnerable" in desc:
        score += VULN_WEAK_VALUE
    if "weak" in desc:
        score += VULN_WEAK_VALUE
    if "strength" in desc and ctype != "power":
        score += STRENGTH_VALUE * 0.5
    if "exhaust" in desc:
        score += EXHAUST_VALUE
    if "all enem" in desc:
        score += AOE_VALUE
    if "draw" in desc and draw == 0:
        score += DRAW_VALUE  # draw mentioned but not in stats

    # Rarity bonus
    score += RARITY_BONUS.get(rarity, 0.0)

    # Empirical bonus from boss-reach correlation data
    if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
        score += EMPIRICAL_BONUS[card_id] * EMPIRICAL_WEIGHT

    # Clamp to 0-10
    return max(0.0, min(score, 10.0))


def best_smith_target(deck: list[dict]) -> int | None:
    """Index in `deck` of the highest-value un-upgraded card worth a SMITH.

    Returns None if no card in the deck scores >= SMITH_PRIORITY_THRESHOLD when
    un-upgraded. Used by rest_site_action to override the default heal-vs-smith
    HP threshold: there's no point healing 5 HP if a key DEMON_FORM is sitting
    un-upgraded — upgrading it pays off across every remaining combat.
    """
    if not deck:
        return None
    best_idx, best_score = None, -1.0
    for i, c in enumerate(deck):
        if c.get("upgraded"):
            continue
        s = score_card(c)
        if s >= SMITH_PRIORITY_THRESHOLD and s > best_score:
            best_idx, best_score = i, s
    return best_idx


# --- Deck-archetype synergy ---------------------------------------------
# Cards that GIVE strength (a Strength build wants more attacks).
STRENGTH_GAIN_CARDS = {"DEMON_FORM", "INFLAME", "LIMIT_BREAK", "SPOT_WEAKNESS",
                       "FLEX", "RUPTURE", "FEROCITY", "BRIMSTONE",
                       "BLADE_OF_INK", "DOMINATE", "SETUP_STRIKE"}
# Cards that BENEFIT FROM strength (they scale per-hit).
STRENGTH_USER_CARDS = {"HEAVY_BLADE", "PUMMEL", "TWIN_STRIKE", "WHIRLWIND",
                       "FIEND_FIRE", "ANGER", "SWORD_BOOMERANG",
                       "BLUDGEON", "PERFECTED_STRIKE", "BEAT_DOWN", "GRAPPLE",
                       "POMMEL_STRIKE", "DISMANTLE", "DROPKICK"}
# Cards that EXHAUST (enable exhaust archetype).
EXHAUST_PAYLOAD_CARDS = {"FEEL_NO_PAIN", "DARK_EMBRACE", "CORRUPTION",
                         "FIRE_BREATHING", "SENTINEL", "JUGGERNAUT",
                         "FORGOTTEN_RITUAL", "ASHEN_STRIKE", "EVIL_EYE"}
# Cards that GET EXHAUSTED naturally (fuel for exhaust payload).
EXHAUST_FUEL_CARDS = {"TRUE_GRIT", "SECOND_WIND", "OFFERING", "SEVER_SOUL",
                      "FIEND_FIRE", "REAPER", "OBLITERATE", "CARNAGE"}
# Cards that scale with block (Block archetype).
BLOCK_PAYLOAD_CARDS = {"BARRICADE", "JUGGERNAUT", "ENTRENCH", "BODY_SLAM",
                       "GRAPPLE", "METALLICIZE", "SECOND_WIND"}


def _card_id_norm(card: dict) -> str:
    cid = card.get("id", "")
    if isinstance(cid, dict): cid = cid.get("en", str(cid))
    cid = str(cid).upper().strip()
    if cid.startswith("CARD."): cid = cid[5:]
    return cid


def compute_deck_archetype(deck: list[dict]) -> dict:
    """Count synergy markers in the deck. Used to bias card picks toward what
    the deck is becoming. Returns counts (not bools) so downstream code can
    weight by saturation (one Inflame is good; three is overkill)."""
    if not deck:
        return {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
                "exhaust_fuel": 0, "block_payload": 0, "n": 0}
    counts = {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
              "exhaust_fuel": 0, "block_payload": 0, "n": len(deck)}
    for c in deck:
        cid = _card_id_norm(c)
        if cid in STRENGTH_GAIN_CARDS: counts["str_gain"] += 1
        if cid in STRENGTH_USER_CARDS: counts["str_user"] += 1
        if cid in EXHAUST_PAYLOAD_CARDS: counts["exhaust_payload"] += 1
        if cid in EXHAUST_FUEL_CARDS: counts["exhaust_fuel"] += 1
        if cid in BLOCK_PAYLOAD_CARDS: counts["block_payload"] += 1
    return counts


def score_card_in_deck(card: dict, deck: list[dict]) -> float:
    """Score a card with deck-context bonuses. Reward cards that fit the
    archetype the deck is building toward; lightly penalize redundant payloads."""
    base = score_card(card)
    if not deck:
        return base
    cid = _card_id_norm(card)
    arch = compute_deck_archetype(deck)
    bonus = 0.0

    # Strength archetype: if deck has 1+ str_gain, str_user cards become more valuable.
    if arch["str_gain"] >= 1 and cid in STRENGTH_USER_CARDS:
        bonus += 1.0
    # Reverse: if deck has 2+ str_users (commits to strength), str_gain becomes more valuable.
    if arch["str_user"] >= 2 and cid in STRENGTH_GAIN_CARDS:
        bonus += 1.0

    # Exhaust archetype: payload + fuel synergy.
    if arch["exhaust_payload"] >= 1 and cid in EXHAUST_FUEL_CARDS:
        bonus += 0.7
    if arch["exhaust_fuel"] >= 2 and cid in EXHAUST_PAYLOAD_CARDS:
        bonus += 1.2

    # Block archetype: stack block payloads only if deck commits to defense.
    if arch["block_payload"] >= 1 and cid in BLOCK_PAYLOAD_CARDS:
        bonus += 0.5

    # Saturation penalty — three Inflames is one too many.
    if cid in STRENGTH_GAIN_CARDS and arch["str_gain"] >= 2:
        bonus -= 1.5
    if cid in EXHAUST_PAYLOAD_CARDS and arch["exhaust_payload"] >= 2:
        bonus -= 1.0

    return max(0.0, min(base + bonus, 10.0))


def deck_quality_score(deck: list[dict]) -> float:
    """Average score of the top-10 cards in the deck. Used as a milestone reward
    proxy: a deck whose top-10 averages 6+ is in good shape; below 4.5 is weak."""
    if not deck:
        return 0.0
    scores = sorted((score_card(c) for c in deck), reverse=True)[:10]
    return sum(scores) / len(scores) if scores else 0.0


def pick_best_card(cards: list[dict], threshold: float = 3.5,
                   deck: list[dict] = None) -> int | None:
    """Return index of the best card above threshold, or None to skip.
    If `deck` is provided, uses deck-aware scoring (synergy bonuses)."""
    if not cards:
        return None
    scorer = (lambda c: score_card_in_deck(c, deck)) if deck else score_card
    scored = [(i, scorer(c)) for i, c in enumerate(cards)]
    scored.sort(key=lambda x: x[1], reverse=True)
    best_idx, best_score = scored[0]
    if best_score >= threshold:
        return best_idx
    return None


def pick_worst_card(cards: list[dict], threshold: float = 5.0) -> int | None:
    """Return index of the worst card below threshold for removal, or None."""
    if not cards:
        return None
    scored = [(i, score_card(c)) for i, c in enumerate(cards)]
    scored.sort(key=lambda x: x[1])
    worst_idx, worst_score = scored[0]
    if worst_score < threshold:
        return worst_idx
    return None
