"""
card_scoring.py — Heuristic card scoring for deck-building decisions.

Scores each card 0-10 based on damage/block/cost efficiency, special effects,
and synergy potential. Used by greedy_action() for card_reward, shop, and
card_select (removal) decisions.
"""
import json as _json
import os as _os

# === Empirical bonus from gameplay statistics ===
# Generated by agent/collect_deck_stats.py: log-ratio of card frequency in
# boss-reach decks vs early-died decks. Cards that empirically correlate with
# reaching the boss get a positive bonus (capped ±1.5). Re-run that script
# whenever the policy or strategy shifts substantially to refresh the data.
_EMPIRICAL_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", "data", "card_empirical.json")
try:
    with open(_EMPIRICAL_PATH) as _ef:
        EMPIRICAL_BONUS = _json.load(_ef)
except (FileNotFoundError, ValueError):
    EMPIRICAL_BONUS = {}

# Card-archetype tags (Phase 1 of stream-aware scoring) — load lazily from
# data/ironclad_card_tags.json (generated by agent/build_card_tags.py).
# Each card → list of tags (e.g. SCALING_PILLAR, BLOCK_SCALING, DRAW).
_CARD_TAGS_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", "data", "ironclad_card_tags.json")
_CARD_TAGS: dict[str, list[str]] = {}
try:
    with open(_CARD_TAGS_PATH) as _tf:
        _CARD_TAGS = _json.load(_tf).get("card_tags", {})
except (FileNotFoundError, ValueError):
    pass

# Advisor tier ratings + axes (data/advisor_card_ratings.json,
# data/advisor_card_tags.json), generated by agent/build_advisor_ratings.py.
_ADVISOR_RATINGS_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                      "..", "data", "advisor_card_ratings.json")
_ADVISOR_TAGS_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                   "..", "data", "advisor_card_tags.json")
_ADVISOR_RATINGS: dict | None = None
_ADVISOR_TAGS: dict | None = None

_TIER_BASE = {"S": 9.5, "A": 8.0, "B": 6.0, "C": 4.0, "D": 2.0}
_OVERRIDE_DELTA_CAP = 2.0


def _load_advisor_ratings() -> dict:
    """Lazy-load data/advisor_card_ratings.json. Missing data disables it."""
    global _ADVISOR_RATINGS
    if _ADVISOR_RATINGS is None:
        try:
            with open(_ADVISOR_RATINGS_PATH) as _f:
                _ADVISOR_RATINGS = _json.load(_f)
        except (FileNotFoundError, ValueError):
            _ADVISOR_RATINGS = {}
    return _ADVISOR_RATINGS


def _load_advisor_tags() -> dict:
    """Lazy-load data/advisor_card_tags.json. Missing data disables it."""
    global _ADVISOR_TAGS
    if _ADVISOR_TAGS is None:
        try:
            with open(_ADVISOR_TAGS_PATH) as _f:
                _ADVISOR_TAGS = _json.load(_f)
        except (FileNotFoundError, ValueError):
            _ADVISOR_TAGS = {}
    return _ADVISOR_TAGS

# Empirical bonus DISABLED (Run 23 retry showed avg_floor regression
# 14.3 → 9.9 vs Run 22 baseline despite weight=0.3 / min_magnitude=0.5
# settings). The data was collected from 3706k's own gameplay, so even
# small bonuses reinforced existing biases and caused the policy to drift
# off the verified-good Run 22 working point. Set weight=0.0 to disable
# without removing the data file; flip back if a future run uses externally
# collected stats (e.g. from a *different* policy or human play).
EMPIRICAL_WEIGHT = 0.0
EMPIRICAL_MIN_MAGNITUDE = 0.5

# Manual overrides for known high/low value cards.
# Cards not listed get scored by the generic formula.
OVERRIDES: dict[str, float] = {
    # === Ironclad top picks (9-10) ===
    "FEED": 9.5,            # kill an enemy → heal + max HP
    "DEMON_FORM": 9.5,      # +2 str/turn is game-winning
    "CORRUPTION": 9.0,      # skills cost 0, insane with dead branch
    "BRIMSTONE": 9.0,       # +2 str/turn, low downside for Ironclad
    "LIMIT_BREAK": 9.0,     # double strength
    "IMPERVIOUS": 9.0,      # 30 block
    "OFFERING": 8.5,        # draw + energy, life cost is fine
    "DARK_EMBRACE": 8.5,    # draw on exhaust synergy
    "FEEL_NO_PAIN": 8.5,    # block on exhaust
    "JUGGERNAUT": 8.5,      # each block = damage — game-winning in block-heavy decks
    "SENTINEL": 8.0,        # 3 energy if exhausted
    "SECOND_WIND": 8.0,     # exhaust + block
    "TRUE_GRIT": 7.5,       # exhaust 1, draw 2
    "WARCRY": 7.0,          # draw with no downside
    "SHRUG_IT_OFF": 8.0,    # 8 block + draw 1
    "SPOT_WEAKNESS": 6.5,   # +3 str if enemy attacking — strong conditional
    "BRUTALITY": 5.5,       # 0-cost draw at 1 HP/turn — aggressive cycle

    # === STS2 new cards — top picks (8-9) ===
    "HOWL_FROM_BEYOND": 9.0,   # AOE that auto-replays from exhaust pile each turn
    "APOTHEOSIS": 9.0,         # upgrade ALL cards (colorless) — enormous value
    "AGGRESSION": 8.5,         # power: free upgraded Attack from discard each turn
    "ADRENALINE": 8.0,         # 0-cost: gain 1 energy + draw 2 (no HP cost in STS2)
    "SHOCKWAVE": 7.5,          # AOE Weak + Vulnerable to all enemies — huge setup
    "FORGOTTEN_RITUAL": 8.0,   # gain energy when exhaust — capped (generic formula over-scores)
    "HELLRAISER": 8.0,         # auto-plays Strike on draw — free attacks all game
    "MOLTEN_FIST": 8.0,        # doubles target's Vulnerable — huge damage multiplier
    "DISMANTLE": 7.5,          # 13 dmg; hits twice if Vulnerable (26 for 1 energy)
    "BLADE_OF_INK": 6.0,       # this turn: +1 str per Attack — scales with attack-heavy turns
    "POMMEL_STRIKE": 7.5,      # 9 dmg + draw 1 (generic formula gives 8.5, slightly lower)
    "UNRELENTING": 7.5,        # 12 dmg + next Attack costs 0 — energy generation
    "BLUDGEON": 7.5,           # simple heavy single-target damage
    "SETUP_STRIKE": 7.0,       # 9 dmg + temporary strength this turn
    "GRAPPLE": 7.0,            # dmg + deals extra per block gained this turn
    "VICIOUS": 6.5,            # draw when you apply Vulnerable
    "INFERNAL_BLADE": 7.0,     # add free random Attack to hand
    "PERFECTED_STRIKE": 6.5,   # scales with Strike count (good early, less later)
    "CINDER": 5.5,             # dmg + forced exhaust top of draw (can trash good card)
    "BLOOD_WALL": 4.0,         # HP loss for block — net negative, avoid
    "BREAKTHROUGH": 6.0,       # AOE but costs HP — trade-off
    "EVIL_EYE": 6.0,           # block + extra block on exhaust — conditional
    "DOMINATE": 6.5,           # apply Vuln + gain Str per Vuln on enemy — strong offensive
    "TAUNT": 7.0,              # block + apply Vulnerable — efficient dual-purpose skill
    "JUGGLING": 5.5,           # power: add copy of 3rd Attack played each turn — free attacks
    "EXPECT_A_FIGHT": 5.0,     # gain 1 energy per Attack in hand — strong in attack-heavy decks
    "ASHEN_STRIKE": 5.0,       # damage scales with exhaust pile — strong with exhaust synergy
    "TREMBLE": 4.5,            # 1-cost Apply Vulnerable — combo piece with attack-heavy deck
    "RUPTURE": 4.5,            # power: +1 Str when losing HP from card — synergy with OFFERING/BRUTALITY
    "FEROCITY": 6.5,           # power: +1 Str per Attack played — snowballs in attack-heavy deck
    "HEARTSEEKER": 7.0,        # 8 dmg + 1 Vulnerable — efficient attack/debuff combo
    "OBLITERATE": 7.5,         # 20 dmg Exhaust — high single-hit for 1 energy
    "PREDATOR": 6.5,           # 15 dmg + conditional draw — good damage with upside

    # === Strong cards (7-8) ===
    "BARRICADE": 8.5,        # block persists between turns — enables massive block stacking
    "CARNAGE": 7.5,         # 20 damage for free (ethereal)
    "RECKLESS_CHARGE": 7.0, # 7 dmg + wound, still good DPE
    "CLEAVE": 7.0,          # AOE 8 damage
    "UPPERCUT": 7.5,        # 13 dmg + vuln + weak
    "PUMMEL": 7.0,          # multi-hit with str scaling
    "BURNING_PACT": 7.0,   # draw 2 + exhaust
    "INFLAME": 8.0,         # +2 str (power, persistent)
    "METALLICIZE": 7.5,     # +3 block/turn (power)
    "BATTLE_TRANCE": 7.0,   # draw 3
    "BLOODLETTING": 7.0,    # free energy
    "RAGE": 7.0,            # block on attack plays
    "DROPKICK": 8.0,        # 5 dmg + draw + energy if vuln target
    "WHIRLWIND": 1.0,       # X-cost AOE — causes NullRef crash in headless (BUG-034)
    "HEAVY_BLADE": 7.0,     # scales with str (3x multiplier)
    "SWORD_BOOMERANG": 7.0, # 3x3 random hits
    "CLASH": 6.5,           # 0-cost, 14 dmg — great in attack-heavy decks
    "BEAT_DOWN": 7.0,       # play N attacks from discard — strong reuse with good attacks
    "ANOINTED": 6.0,        # put all rares from draw pile into hand — useful mid/late game

    # === STS2 colorless decent picks (5-7) ===
    "DRAMATIC_ENTRANCE": 7.0,  # free AOE damage on combat start (Ethereal, costs 0)
    "METAMORPHOSIS": 6.5,   # add N free Attacks to draw pile — extra resources
    "BEAT_INTO_SHAPE": 6.5, # damage that scales with hits this turn — strong multi-hit
    "PANACHE": 6.0,         # power: AOE damage every 5 cards played
    "MASTER_OF_STRATEGY": 6.0, # draw 3, exhaust — card advantage
    "ANGER": 5.0,           # damage + copy in discard (scaling but clogs deck)
    "DARK_SHACKLES": 4.5,   # reduce enemy strength this turn — situational defensive
    "BLIGHT_STRIKE": 5.0,   # damage + apply Doom — Doom may not tick in headless (BUG-021)
    "DISCOVERY": 5.5,       # choose 1 of 3 random cards free — card quality upgrade
    "JACK_OF_ALL_TRADES": 5.0,  # add random colorless cards — inconsistent

    # === Decent cards (5-6) ===
    "ANGELIC_DEW": 5.5,
    "ARMAMENTS": 6.0,       # upgrade hand
    "BASH": 6.0,            # starter but vulnerable is good
    "BLOOD_FOR_BLOOD": 6.0,
    "BODY_SLAM": 6.5,       # scales with block
    "CLOTHESLINE": 5.5,     # 12 dmg + weak
    "COMBUST": 5.5,
    "ENTRENCH": 5.5,
    "FIEND_FIRE": 6.0,
    "FLEX": 5.0,
    "HAVOC": 5.5,
    "HEADBUTT": 5.5,        # 9 dmg + put card back on draw
    "HEMOKINESIS": 6.0,
    "IRON_WAVE": 5.5,       # 5 dmg + 5 block for 1
    "POWER_THROUGH": 6.0,  # 15 block, adds wounds
    "PUNCTURE": 5.0,
    "RAMPAGE": 5.5,
    "SEARING_BLOW": 5.0,   # needs upgrades
    "SEVER_SOUL": 5.5,
    "THUNDERCLAP": 7.0,    # AOE damage + Vulnerable to ALL enemies (strong setup)
    "TWIN_STRIKE": 6.0,    # 5x2 = 10 for 1
    "WILD_STRIKE": 5.5,    # 12 dmg, wound to draw

    # === Mediocre (3-4) ===
    "DEFEND": 3.0,          # basic, want to remove
    "DEFEND_IRONCLAD": 3.0,
    "DEFEND_SILENT": 3.0,
    "DEFEND_DEFECT": 3.0,
    "STRIKE": 2.0,          # basic, want to remove
    "STRIKE_IRONCLAD": 2.0,
    "STRIKE_SILENT": 2.0,
    "STRIKE_DEFECT": 2.0,
    "WOUND": 1.0,           # pure bad
    "DAZE": 1.0,
    "SLIMED": 1.0,
    "BURN": 0.5,
}

# Type-based generic scoring weights
ATTACK_DPE_BASELINE = 6.0   # Strike: 6 dmg / 1 cost
BLOCK_BPE_BASELINE = 5.0    # Defend: 5 block / 1 cost
DRAW_VALUE = 2.5            # per card drawn — Run 22 verified (3.0 caused regression in Run 24)
ENERGY_VALUE = 5.0          # per energy generated — Run 22 verified
LOW_COST_BONUS = 0.0        # 0-cost universal bonus — disabled after Run 24 showed
                            # avg_floor 14.3→11.2 regression. The bonus pulled the policy
                            # toward cheap utility cards at expense of damage. Re-enable
                            # only with stronger filtering (e.g. only when paired with draw/energy).
ONE_COST_BONUS = 0.0
VULN_WEAK_VALUE = 1.5       # vulnerable or weak bonus
STRENGTH_VALUE = 2.5        # per point of strength
DEXTERITY_VALUE = 2.0       # per point of dexterity
EXHAUST_VALUE = 1.0         # exhaust synergy bonus
AOE_VALUE = 1.5             # AOE bonus
POWER_BONUS = 1.5           # powers persist, extra value
RARITY_BONUS = {"Common": 0.0, "Uncommon": 0.5, "Rare": 1.0}

# Cards whose OnPlay throws NullReferenceException in headless mode (the
# game expects some manager/VFX singleton that doesn't exist when running
# without Godot). Playing them inside a combat poisons the async task chain,
# stalls ActionExecutor for ~10s, and trashes training metrics (cwr→13%,
# cr→85%). Until we patch the underlying call in setup.sh's IL pass, we
# blacklist them in pick_best_card so the agent never adds them to its deck.
# Identified 2026-05-26 from training_run_full8 collapse at chunk 53.2%:
#   System.NullReferenceException at FlashOfSteel.OnPlay
#   System.NullReferenceException at Whirlwind.OnPlay
# (Whirlwind was already known from memory: BUG-034 / commit 936231d; the
# Steam-update May 22 reopened the same NullRef path that the C# fix had
# addressed.)
BROKEN_CARDS = {"FLASH_OF_STEEL", "WHIRLWIND"}

# Threshold above which an un-upgraded card should be a SMITH target at the next
# rest site. Calibrated so DEMON_FORM/BARRICADE/HOWL_FROM_BEYOND/LIMIT_BREAK and
# top draw/energy enablers (OFFERING/SHRUG_IT_OFF/POMMEL_STRIKE) all qualify, but
# common Strike/Defend variants do not.
SMITH_PRIORITY_THRESHOLD = 7.0

# Cards that are never worth picking (status/curse starters)
SKIP_IDS = {"STRIKE_R", "DEFEND_R", "STRIKE_B", "DEFEND_B", "STRIKE_G",
            "DEFEND_G", "WOUND", "DAZE", "SLIMED", "BURN", "DECAY",
            # STS2 naming variants
            "STRIKE_IRONCLAD", "DEFEND_IRONCLAD",
            "STRIKE_SILENT", "DEFEND_SILENT",
            "STRIKE_DEFECT", "DEFEND_DEFECT",
            # STS2 curses/status cards
            "DOUBT", "REGRET", "SHAME", "VOID", "NORMALITY"}

_STARTER_DEAD_WEIGHT_IDS = {
    "STRIKE_R", "DEFEND_R", "STRIKE_B", "DEFEND_B", "STRIKE_G", "DEFEND_G",
    "STRIKE_IRONCLAD", "DEFEND_IRONCLAD",
    "STRIKE_SILENT", "DEFEND_SILENT",
    "STRIKE_DEFECT", "DEFEND_DEFECT",
}
_ZERO_DIMENSION_IDS = SKIP_IDS - _STARTER_DEAD_WEIGHT_IDS


def _context_bonus(card: dict) -> float:
    """Small bonuses layered on top of advisor tier baselines."""
    import re as _re_cb

    raw_cost = card.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        raw_cost = 1
    ctype = (card.get("type") or "").lower()
    stats = card.get("stats") or {}
    desc = str(card.get("description", "")).lower()

    bonus = 0.0
    if raw_cost == 0:
        bonus += LOW_COST_BONUS
    elif raw_cost == 1:
        bonus += ONE_COST_BONUS

    draw = stats.get("cards", stats.get("draw", 0)) or 0
    if draw > 0:
        bonus += draw * DRAW_VALUE

    energy = stats.get("energy", 0)
    if energy > 0:
        bonus += energy * ENERGY_VALUE

    if "vulnerable" in desc:
        bonus += VULN_WEAK_VALUE
    if "weak" in desc:
        bonus += VULN_WEAK_VALUE
    if "strength" in desc and ctype != "power":
        bonus += STRENGTH_VALUE * 0.5
    if "exhaust" in desc:
        bonus += EXHAUST_VALUE
    if "all enem" in desc:
        bonus += AOE_VALUE
    if "draw" in desc and draw == 0:
        bonus += DRAW_VALUE

    hp_loss_m = _re_cb.search(r"lose\s+(\d+)\s+hp", desc)
    if hp_loss_m:
        bonus -= 0.3 * int(hp_loss_m.group(1))
    if "damage equal to" in desc:
        bonus += 5.0
    if " x " in desc or "x times" in desc:
        x_dmg_m = _re_cb.search(r"(\d+)\s+damage", desc)
        bonus += min(int(x_dmg_m.group(1)) * 2 / 3, 5.0) if x_dmg_m else 2.0
    return bonus


def score_card(card: dict) -> float:
    """Score a card 0-10 based on its effectiveness.

    card: dict with keys: id, cost, type, rarity, stats, name, keywords

    Broken cards (BROKEN_CARDS — crash combat in headless mode) get score 0
    so they're never selected by any deck-less scoring path either."""
    if _card_id_norm(card) in BROKEN_CARDS:
        return 0.0
    card_id = card.get("id", "")
    if isinstance(card_id, dict):
        card_id = card_id.get("en", str(card_id))
    card_id = card_id.upper().strip()
    # Game prefixes IDs with "CARD." — strip it for override lookups
    if card_id.startswith("CARD."):
        card_id = card_id[5:]

    _adv = _load_advisor_ratings().get(card_id)
    if _adv and _adv.get("tier") in _TIER_BASE:
        score = _TIER_BASE[_adv["tier"]] + _context_bonus(card)
        if card_id in OVERRIDES:
            delta = OVERRIDES[card_id] - _TIER_BASE[_adv["tier"]]
            delta = max(-_OVERRIDE_DELTA_CAP, min(_OVERRIDE_DELTA_CAP, delta))
            score += delta
        if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
            score += EMPIRICAL_BONUS[card_id] * EMPIRICAL_WEIGHT
        return max(0.0, min(score, 10.0))

    # Check manual override first — but DO still apply empirical bonus below
    # so the data-driven signal can nudge override values up/down.
    if card_id in OVERRIDES:
        score = OVERRIDES[card_id]
        if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
            _eb = EMPIRICAL_BONUS[card_id]
            if abs(_eb) >= EMPIRICAL_MIN_MAGNITUDE:
                score += _eb * EMPIRICAL_WEIGHT
        return max(0.0, min(score, 10.0))

    # Skip status/curse cards
    if card_id in SKIP_IDS:
        return 0.0

    raw_cost = card.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        raw_cost = 1
    cost = max(raw_cost, 1)  # treat 0-cost as 1 for ratio calc
    ctype = (card.get("type") or "").lower()
    rarity = card.get("rarity", "Common")
    stats = card.get("stats") or {}
    name = card.get("name", "")
    if isinstance(name, dict):
        name = name.get("en", "")

    score = 0.0
    # Low-cost combo bonus — 0-cost cards stack in high-energy turns,
    # 1-cost cards still cycle cheaply. Boss wins correlate with playing
    # many cards per turn, and cost is the gate.
    if raw_cost == 0:
        score += LOW_COST_BONUS
    elif raw_cost == 1:
        score += ONE_COST_BONUS

    # === Attack cards: score by damage per energy ===
    if ctype == "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            dpe = damage / cost
            score += min(dpe / ATTACK_DPE_BASELINE * 5.0, 7.0)

    # === Skill cards: score by block, draw, energy ===
    elif ctype == "skill":
        block = stats.get("block", 0)
        if block > 0:
            bpe = block / cost
            score += min(bpe / BLOCK_BPE_BASELINE * 4.0, 5.0)

    # === Power cards: base value + effect scoring ===
    elif ctype == "power":
        score += POWER_BONUS
        # Powers with str/dex are very strong
        if "strength" in str(stats).lower() or "str" in str(stats).lower():
            score += STRENGTH_VALUE
        if "dexterity" in str(stats).lower() or "dex" in str(stats).lower():
            score += DEXTERITY_VALUE

    # === Generic bonuses ===
    # Draw value — the C# runtime sends draw count under the `cards` stat key
    # (e.g. Pommel Strike: stats={damage:9, cards:1}); accept `draw` too in
    # case the wiki/sim path ever populates it directly.
    draw = stats.get("cards", stats.get("draw", 0)) or 0
    if draw > 0:
        score += draw * DRAW_VALUE

    # Energy generation
    energy = stats.get("energy", 0)
    if energy > 0:
        score += energy * ENERGY_VALUE

    # Block on any card (not just skills)
    if ctype != "skill":
        block = stats.get("block", 0)
        if block > 0:
            score += min(block / cost * 0.5, 3.0)

    # Damage on non-attack cards
    if ctype != "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            score += min(damage / cost * 0.5, 3.0)

    # Check keywords/description for effects
    desc = str(card.get("description", "")).lower()
    if "vulnerable" in desc:
        score += VULN_WEAK_VALUE
    if "weak" in desc:
        score += VULN_WEAK_VALUE
    if "strength" in desc and ctype != "power":
        score += STRENGTH_VALUE * 0.5
    if "exhaust" in desc:
        score += EXHAUST_VALUE
    if "all enem" in desc:
        score += AOE_VALUE
    if "draw" in desc and draw == 0:
        score += DRAW_VALUE  # draw mentioned but not in stats

    # --- Jun 10 patches per user feedback ---
    # (a) HP loss penalty — OFFERING/BLOODLETTING/HEMOKINESIS etc. carry HP cost
    #     that prior scoring under-weighted. Each HP lost = -0.3 (small drag).
    import re as _re_sc
    hp_loss_m = _re_sc.search(r"lose\s+(\d+)\s+hp", desc)
    if hp_loss_m:
        score -= 0.3 * int(hp_loss_m.group(1))

    # (b) "Damage equal to" — BODY_SLAM-class cards have no parsed damage but
    #     do real damage in context. Assign a reasonable mid-deck proxy.
    if "damage equal to" in desc:
        score += 5.0  # presence of conditional damage scaler; refined by
                     # tag/synergy bonuses elsewhere when deck context known

    # (c) X-cost cards — WHIRLWIND-class "X times" scale with energy. Static
    #     parse misses the multiplier; assume X≈2 (typical energy spend).
    if " x " in desc or "x times" in desc:
        # Approximate damage = base × 2 (X=2 default)
        x_dmg_m = _re_sc.search(r"(\d+)\s+damage", desc)
        if x_dmg_m:
            score += min(int(x_dmg_m.group(1)) * 2 / 3, 5.0)  # /3 normalizes
        else:
            score += 2.0  # fallback for non-damage X cards

    # Rarity bonus
    score += RARITY_BONUS.get(rarity, 0.0)

    # Empirical bonus from boss-reach correlation data
    if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
        score += EMPIRICAL_BONUS[card_id] * EMPIRICAL_WEIGHT

    # Clamp to 0-10
    return max(0.0, min(score, 10.0))


def best_smith_target(deck: list[dict]) -> int | None:
    """Index in `deck` of the highest-value un-upgraded card worth a SMITH.

    Returns None if no card in the deck scores >= SMITH_PRIORITY_THRESHOLD when
    un-upgraded. Used by rest_site_action to override the default heal-vs-smith
    HP threshold: there's no point healing 5 HP if a key DEMON_FORM is sitting
    un-upgraded — upgrading it pays off across every remaining combat.

    Cards tagged UPGRADE_PRIORITY_HIGH (cost reduction, innate gained, scaling
    acceleration — e.g. BODY_SLAM 1→0, DEMON_FORM 2→3 STR/turn) get a +3.0
    score bump so they're preferred over higher-raw-scored MID upgrades when
    both are un-upgraded.
    """
    if not deck:
        return None
    best_idx, best_score = None, -1.0
    for i, c in enumerate(deck):
        if c.get("upgraded"):
            continue
        s = score_card(c)
        if "UPGRADE_PRIORITY_HIGH" in _card_tags(c):
            s += 3.0
        if s >= SMITH_PRIORITY_THRESHOLD and s > best_score:
            best_idx, best_score = i, s
    return best_idx


# --- Pairwise card-card synergy (subagent-generated) -------------------
# Loaded from data/card_synergies.py. Each entry: card_id → list of (other_id, score)
# tuples. When picking card B for the deck, sum synergy(A, B) for each A already
# in the deck — gives a deck-context-aware bonus that captures real combos
# (e.g. UNRELENTING + BLUDGEON, DEMON_FORM + LIMIT_BREAK).
try:
    from data.card_synergies import SYNERGIES as _PAIRWISE_SYNERGIES
except ImportError:
    _PAIRWISE_SYNERGIES = {}

PAIRWISE_WEIGHT = 0.4   # Multiplier on summed pairwise synergy. 0.4 caps a single
                        # iconic 3.0-pair at +1.2; multiple weak pairs sum but get
                        # capped further by the per-card overall clamp.
PAIRWISE_CAP = 2.5      # Maximum pairwise bonus per card pick (prevents runaway
                        # for cards that synergize with many deck members).


def pairwise_synergy_bonus(card_id: str, deck: list[dict]) -> float:
    """Sum of synergy scores between card_id and every card already in deck.
    Multi-copy in deck multiplies (e.g. 2 INFLAMEs in deck = 2× synergy).
    Returns 0 if no synergies match. Capped at PAIRWISE_CAP."""
    if not _PAIRWISE_SYNERGIES or not deck or card_id not in _PAIRWISE_SYNERGIES:
        return 0.0
    pairs = dict(_PAIRWISE_SYNERGIES[card_id])  # other_id → score
    total = 0.0
    for c in deck:
        other = _card_id_norm(c)
        if other in pairs:
            total += pairs[other]
    return min(total * PAIRWISE_WEIGHT, PAIRWISE_CAP)


# --- 4-dimension deck capability scoring (May 11) -----------------------
# Rate the deck across four axes — attack output, defense, energy gen, draw —
# then bias new card picks toward the weakest axis. Prevents over-stacking
# attacks at the cost of defense (which was the failure mode in 5692k boss
# fights: deck had strong damage but couldn't survive incoming AoE).

# Target "good deck" levels — used as deficit reference. A deck whose per-card
# average reaches these is well-rounded.
DIM_BASELINES = {"attack": 3.0, "defense": 1.5, "energy": 0.20, "draw": 0.25}


def card_dimensions(card: dict) -> dict[str, float]:
    """How much this card contributes to each dimension. Per-card scalars,
    not per-energy — so a 0-cost draw card is correctly scored without
    division blow-up."""
    cid = _card_id_norm(card)
    if cid in _ZERO_DIMENSION_IDS:
        return {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    ctype = (card.get("type") or "").lower()
    wiki = _load_wiki_stats().get(cid, {})
    if not ctype:
        ctype = str(wiki.get("type") or "").lower()
    raw_cost = card.get("cost", 1)
    if raw_cost in (None, ""):
        raw_cost = wiki.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        try:
            raw_cost = float(raw_cost)
        except (TypeError, ValueError):
            raw_cost = 1
    cost = max(raw_cost, 1)
    stats = card.get("stats") or {}
    res = {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    dmg = stats.get("damage", _card_field(card, "damage", 0)) or 0
    if ctype == "attack" and dmg > 0:
        res["attack"] = dmg / cost
    blk = stats.get("block", _card_field(card, "block", 0)) or 0
    if blk > 0:
        res["defense"] = blk / cost
    e = stats.get("energy", _card_field(card, "energy", 0)) or 0
    if e > 0:
        res["energy"] = float(e)
    # Runtime sends draw count under the `cards` key; keep `draw` fallback for
    # any path that pre-normalises (parsers, sim, viewer).
    d = (stats.get("cards") or stats.get("draw") or
         _card_field(card, "cards", _card_field(card, "draw", 0)) or 0)
    if d > 0:
        res["draw"] = float(d)
    # Powers: strength-gain count as attack potential (4 dmg-equiv per 1 str
    # over a fight averaging ~4 attacks); energy-per-turn powers count as energy.
    if ctype == "power":
        desc = str(card.get("description", "")).lower()
        if "strength" in desc and "lose" not in desc and "enem" not in desc:
            res["attack"] += 4.0
        if "dexterity" in desc:
            res["defense"] += 2.5
        if "energy" in desc and ("each turn" in desc or "every turn" in desc):
            res["energy"] += 1.0
        if "draw" in desc and ("each turn" in desc or "every turn" in desc):
            res["draw"] += 1.0
    return res


# ─── Operational deck-quality thresholds (Jun 9) ──────────────────────
# User-defined thresholds for "this deck can beat Act-1 boss":
#   1. Output:   ≥200 damage in 5 turns
#   2. Defense:  ≥15 block per turn (stable)
#   3. Engine:   deck size ≤15 + core-card draw probability high
#   4. Boss:     ≥1 multi-hit attack + ≥1 AoE for boss adds (champ minions etc)


# Wiki-derived stats cache: card_id → {damage, block, hits, draw, str_gain, text}
_WIKI_STATS: dict | None = None
import re as _re_quality
_DMG_RE = _re_quality.compile(r"deal\s+(\d+)\s+damage", _re_quality.I)
_BLK_RE = _re_quality.compile(r"gain\s+(\d+)\s+block", _re_quality.I)
_DRAW_RE = _re_quality.compile(r"draw\s+(\d+)\s+cards?", _re_quality.I)
_STR_RE = _re_quality.compile(r"gain\s+(\d+)\s+strength", _re_quality.I)
_TWICE_RE = _re_quality.compile(r"\btwice\b|\bthree\s+times\b", _re_quality.I)
_RAMPAGE_GAIN_RE = _re_quality.compile(
    r"increase this card'?s damage by\s+(\d+)", _re_quality.I)


def _load_wiki_stats():
    global _WIKI_STATS
    if _WIKI_STATS is not None:
        return _WIKI_STATS
    _WIKI_STATS = {}
    path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                         "..", "data", "ironclad_cards.json")
    try:
        import json as _json
        with open(path) as f:
            data = _json.load(f)
        for c in data.get("cards", []):
            rid = (c.get("id") or "").upper().replace("-", "_")
            text = c.get("normal_text") or ""
            raw_cost = c.get("cost")
            try:
                cost = int(raw_cost)
            except (TypeError, ValueError):
                cost = 1
            dmg_m = _DMG_RE.search(text)
            blk_m = _BLK_RE.search(text)
            drw_m = _DRAW_RE.search(text)
            str_m = _STR_RE.search(text)
            hits = 2 if _TWICE_RE.search(text) else 1
            _WIKI_STATS[rid] = {
                "damage": int(dmg_m.group(1)) if dmg_m else 0,
                "block": int(blk_m.group(1)) if blk_m else 0,
                "draw": int(drw_m.group(1)) if drw_m else 0,
                "strength": int(str_m.group(1)) if str_m else 0,
                "hits": hits,
                "is_aoe": "all enemies" in text.lower(),
                "type": c.get("type") or "",
                "cost": cost,
                "text": text,
            }
        # Starter card aliases — wiki ids "strike", "defend" map to runtime
        # "STRIKE_IRONCLAD", "DEFEND_IRONCLAD" etc.
        for base, alias in [("STRIKE", "STRIKE_IRONCLAD"),
                             ("DEFEND", "DEFEND_IRONCLAD")]:
            if base in _WIKI_STATS and alias not in _WIKI_STATS:
                _WIKI_STATS[alias] = _WIKI_STATS[base]
    except Exception:
        pass
    return _WIKI_STATS


def _card_field(card: dict, key: str, default=0):
    """Read card stat from card.stats, top-level, or wiki cache."""
    stats = card.get("stats") or {}
    v = stats.get(key)
    if v is not None and v != 0:
        return v
    v = card.get(key)
    if v is not None and v != 0:
        return v
    # Fallback to wiki stats
    cid = _card_id_norm(card)
    wiki = _load_wiki_stats().get(cid)
    if wiki:
        return wiki.get(key, default)
    return default


def _card_text(card: dict) -> str:
    text = str(card.get("description") or "")
    if text:
        return text.lower()
    rec = _load_wiki_stats().get(_card_id_norm(card))
    return str((rec or {}).get("text") or "").lower()


def _strength_burst_equiv(card: dict) -> float:
    """Effective strength gain for a 5-turn boss burst estimate."""
    raw = _card_field(card, "strength", 0)
    text = _card_text(card)
    if not raw:
        m = _STR_RE.search(text)
        raw = int(m.group(1)) if m else 0
    try:
        raw = float(raw)
    except (TypeError, ValueError):
        return 0.0
    if raw <= 0:
        return 0.0
    if "each turn" in text or "every turn" in text:
        return raw * 3.0
    return raw


def _rampage_cycle_bonus(deck: list[dict]) -> float:
    """Extra boss-style damage from replaying Rampage in lean decks."""
    if not deck:
        return 0.0
    size = max(len(deck), 1)
    draw_extra = sum(_card_field(c, "cards", _card_field(c, "draw", 0))
                     for c in deck)
    seen_cards = 25.0 + min(float(draw_extra or 0), 5.0)
    bonus = 0.0
    for c in deck:
        if _card_id_norm(c) != "RAMPAGE":
            continue
        text = _card_text(c)
        m = _RAMPAGE_GAIN_RE.search(text)
        increment = float(m.group(1)) if m else 5.0
        base_damage = float(_card_field(c, "damage", 0) or 0)
        expected_plays = min(3.0, seen_cards / size)
        repeats = max(0.0, expected_plays - 1.0)
        bonus += base_damage * repeats
        bonus += increment * expected_plays * repeats / 2.0
    return bonus


def deck_5turn_burst(deck: list[dict]) -> float:
    """Estimated total damage dealt in first 5 turns of a boss-style combat.
    Assumes 3 energy/turn and average draw cycling. Threshold ≥200 = boss-killable.
    """
    if not deck:
        return 0.0
    def _ctype(c):
        t = (c.get("type") or "").lower()
        if t: return t
        # Wiki fallback for starter cards / missing type
        rec = _load_wiki_stats().get(_card_id_norm(c))
        return (rec.get("type") if rec else "").lower()
    attacks = [c for c in deck if _ctype(c) == "attack"]
    if not attacks:
        return 0.0
    # 5 turns × ~3 plays = 15 cards; if deck ≤ 15 we cycle through
    cards_played = min(15, len(deck))
    attack_ratio = len(attacks) / len(deck)
    estimated_attack_plays = cards_played * attack_ratio
    avg_dmg = sum(_card_field(c, "damage", 0) for c in attacks) / max(len(attacks), 1)
    base = estimated_attack_plays * avg_dmg
    # Strength scaling: each str_gain card contributes ~0.5×attack_plays bonus
    str_gain = sum(_strength_burst_equiv(c) for c in deck)
    # Strength affects every later attack, and Act-1 boss wins depend on
    # scaling across several turns; value it as multiple attack applications.
    str_bonus = str_gain * estimated_attack_plays * 1.5
    # Block→damage payoff (Body Slam): offense scales with accumulated block.
    # Jun 13: a Barricade+Body Slam deck deals burst FROM its block, which the
    # attack-damage sum misses entirely (Body Slam's parsed damage is 0).
    ids = {_card_id_norm(c) for c in deck}
    payoff_bonus = 0.0
    if ids & _BLOCK_PAYOFF:
        bpt = deck_block_per_turn(deck)
        n_payoff = sum(1 for c in deck if _card_id_norm(c) in _BLOCK_PAYOFF)
        # Each Body Slam hits for ~accumulated block; ~2 plays over 5 turns.
        payoff_bonus = bpt * 1.5 * min(n_payoff, 2)
    return base + str_bonus + payoff_bonus + _rampage_cycle_bonus(deck)


# Block-scaling engines: Barricade keeps block across turns (accumulates),
# Entrench doubles it. These multiply effective block-per-turn.
_BLOCK_SCALING_KEYSTONES = {"BARRICADE", "ENTRENCH"}
# Block→damage payoff cards: their offense scales with accumulated block.
_BLOCK_PAYOFF = {"BODY_SLAM"}


def deck_block_per_turn(deck: list[dict]) -> float:
    """Expected block per turn from ALL block-granting cards. Threshold ≥10.

    Jun 13 fix: previously only counted Skill cards, which dropped Iron Wave
    (Attack: 5 block + 5 dmg), Body Slam, Barricade (Power), Juggernaut —
    i.e. every efficient/hybrid defense card. This systematically UNDER-rated
    Barricade/Body-Slam decks (the right answer vs escalating bosses) and
    over-rated piles of low-efficiency Defends."""
    if not deck:
        return 0.0
    # Block from any card type (Iron Wave is an Attack; Barricade is a Power)
    blocks = [_card_field(c, "block", 0) for c in deck]
    blocks = [b for b in blocks if b > 0]
    if not blocks:
        return 0.0
    block_ratio = len(blocks) / len(deck)
    avg_block_per = sum(blocks) / len(blocks)
    bpt = 3 * block_ratio * avg_block_per
    # Barricade/Entrench: block persists/doubles → effective block ~1.8× over
    # a multi-turn boss fight (accumulation).
    ids = {_card_id_norm(c) for c in deck}
    if ids & _BLOCK_SCALING_KEYSTONES:
        bpt *= 1.8
    return bpt


def deck_engine_efficiency(deck: list[dict]) -> float:
    """Returns [0, 1] — higher means tighter deck + better core-card draw rate.
    Threshold: ≤15 cards = 1.0 size component; +0.0-0.3 from draw cards."""
    if not deck:
        return 0.0
    size = len(deck)
    # Size: 10 cards → 1.0, 15 → 1.0, 20 → 0.5, 30+ → 0
    size_score = max(0.0, min(1.0, (25 - size) / 10))
    draws = sum(_card_field(c, "cards", _card_field(c, "draw", 0)) for c in deck)
    draw_ratio = min(1.0, draws / max(size, 1) * 5)  # 1 draw / 5 cards = max
    return 0.7 * size_score + 0.3 * draw_ratio


def deck_boss_versatility(deck: list[dict]) -> float:
    """Returns [0, 1] — counts multi-hit attacks + AoE for handling boss adds.
    Threshold: ≥1 multi-hit AND ≥1 AoE = 1.0; partial credit."""
    if not deck:
        return 0.0
    multi_hit = 0
    aoe = 0
    wiki = _load_wiki_stats()
    for c in deck:
        text = (c.get("description") or "").lower()
        cid = _card_id_norm(c)
        wiki_rec = wiki.get(cid, {})
        hits = _card_field(c, "hits", 1)
        if isinstance(hits, (int, float)) and hits >= 2:
            multi_hit += 1
        elif "twice" in text or "three times" in text or " hits" in text:
            multi_hit += 1
        if "all enemies" in text or wiki_rec.get("is_aoe"):
            aoe += 1
    mh_score = min(1.0, multi_hit / 2)  # 2 multi-hits = full
    aoe_score = min(1.0, aoe / 1)        # 1 AoE = full
    return 0.5 * mh_score + 0.5 * aoe_score


def deck_quality_metrics(deck: list[dict]) -> dict:
    """All 4 operational quality dimensions in one call.

    Thresholds calibrated for "win Act-1 boss from HP=40+ entry":
      Burst:   ≥200 dmg over 5 turns (boss ≈ 200 HP, must close fast)
      Block:   ≥10 block/turn (boss deals 10-20/turn; 10 sustains ~3-6 turns)
      Engine:  ≤15 cards + draw, so core scalers cycle every fight
      Boss:    multi-hit + AoE matters less vs single boss; weight lower

    Weighted overall: burst 0.35 + block 0.30 + engine 0.20 + boss 0.15.
    """
    burst = deck_5turn_burst(deck)
    bpt = deck_block_per_turn(deck)
    eng = deck_engine_efficiency(deck)
    boss = deck_boss_versatility(deck)
    burst_pass = 1.0 if burst >= 200 else burst / 200
    block_pass = 1.0 if bpt >= 10 else bpt / 10
    return {
        "burst_5turn": burst,
        "burst_pass": burst_pass,
        "block_per_turn": bpt,
        "block_pass": block_pass,
        "engine_efficiency": eng,
        "engine_pass": eng,
        "boss_versatility": boss,
        "boss_pass": boss,
        "overall": (
            0.35 * burst_pass + 0.30 * block_pass +
            0.20 * eng + 0.15 * boss
        ),
    }


def score_deck_dimensions(deck: list[dict]) -> dict[str, float]:
    """Per-card average across 4 dimensions. Useful for diagnosing which axis
    the deck is weak on."""
    if not deck:
        return {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    totals = {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    for c in deck:
        d = card_dimensions(c)
        for k, v in d.items():
            totals[k] += v
    n = len(deck)
    return {k: v / n for k, v in totals.items()}


# --- Learned deck predictor (May 12) -----------------------------------
# Loaded lazily from data/deck_predictor.pkl. Predicts max_floor for a deck;
# we use the marginal lift "predicted(deck + card) − predicted(deck)" as a bonus.
_PREDICTOR_PIPELINE = None
_PREDICTOR_LOADED = False


_PREDICTOR_VERSION = None  # "v1" or "v2"; set during _load_predictor
_CARD_DB = None            # cached card_id → metadata lookup (for v2)


def _load_card_db():
    """Lazy-load data/card_metadata.json. Returns empty dict if missing."""
    global _CARD_DB
    if _CARD_DB is not None:
        return _CARD_DB
    path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                         "..", "data", "card_metadata.json")
    if not _os.path.exists(path):
        _CARD_DB = {}
        return _CARD_DB
    try:
        import json as _json
        with open(path) as f:
            _CARD_DB = _json.load(f)
    except Exception:
        _CARD_DB = {}
    return _CARD_DB


_PREDICTOR_VOCAB: dict = {}  # populated by _load_predictor: card_ids, top_relics, floor_buckets


def _load_predictor():
    """Prefer v2 (data/deck_predictor_v2.pkl) over v1. v2-256 schema adds
    card_ids/top_relics/floor_buckets vocab — populated into _PREDICTOR_VOCAB
    for feature extraction below. Falls back gracefully."""
    global _PREDICTOR_PIPELINE, _PREDICTOR_LOADED, _PREDICTOR_VERSION, _PREDICTOR_VOCAB
    if _PREDICTOR_LOADED:
        return _PREDICTOR_PIPELINE
    _PREDICTOR_LOADED = True
    try:
        import pickle as _pk
        # Try v2 first; v1 fallback
        for path_rel, default_ver in [("data/deck_predictor_v2.pkl", "v2"),
                                       ("data/deck_predictor.pkl", "v1")]:
            path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", path_rel)
            if not _os.path.exists(path):
                continue
            with open(path, "rb") as f:
                blob = _pk.load(f)
            _PREDICTOR_PIPELINE = blob.get("pipeline")
            _PREDICTOR_VERSION = blob.get("version", default_ver)
            _PREDICTOR_VOCAB = {
                "card_ids": blob.get("card_ids") or [],
                "top_relics": blob.get("top_relics") or [],
                "floor_buckets": blob.get("floor_buckets") or [],
            }
            return _PREDICTOR_PIPELINE
        return None
    except Exception:
        return None


def _deck_features(deck: list[dict], floor_crossed: int = 10) -> list[float]:
    """Same feature layout as agent/train_deck_predictor.py FEATURE_NAMES.
    `floor_crossed` defaults to 10 — the deck is evaluated as if at the fl=10
    milestone for relative comparison; what matters is the *difference* in
    prediction between (deck) and (deck + new_card)."""
    if not deck:
        return [floor_crossed, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    dims = score_deck_dimensions(deck)
    arch = compute_deck_archetype(deck)
    return [
        float(floor_crossed),
        float(len(deck)),
        float(deck_quality_score(deck)),
        float(dims["attack"]),
        float(dims["defense"]),
        float(dims["energy"]),
        float(dims["draw"]),
        float(arch.get("str_gain", 0)),
        float(arch.get("str_user", 0)),
        float(arch.get("exhaust_payload", 0)),
        float(arch.get("exhaust_fuel", 0)),
        float(arch.get("block_payload", 0)),
    ]


PREDICTOR_WEIGHT = 0.3   # bonus = predictor_lift × this. Predictor outputs floors;
                          # 1-floor lift → +0.3 bonus.
PREDICTOR_CAP = 1.2       # hard cap to prevent runaway bonuses from a confident model.

# v2 inference uses a separate scale: it predicts run.max_floor directly given
# (deck features + candidate features); the model's training y mean is ~10.5
# so we center the prediction. v2 variance across candidates at one decision
# point is typically ±0.5-1 floor, so weight 0.4 / cap 1.0 keeps it on par
# with v1 in effective contribution to score_card_in_deck.
PREDICTOR_V2_CENTER = 10.5
PREDICTOR_V2_WEIGHT = 0.4
PREDICTOR_V2_CAP = 1.0

# v2 feature-extraction vocab — must stay synced with train_deck_predictor_v2.py
_V2_TYPES = ["Attack", "Skill", "Power"]
_V2_RARITIES = ["Common", "Uncommon", "Rare"]


def _card_metadata(card: dict, card_db: dict) -> tuple:
    """Return (cost, type, rarity) for a card, preferring its own fields then
    falling back to card_db lookup by normalized id."""
    cost = card.get("cost")
    ctype = card.get("type")
    crarity = card.get("rarity")
    if cost is None or not ctype or not crarity:
        cid = _card_id_norm(card)
        meta = card_db.get(cid)
        if meta:
            if cost is None: cost = meta.get("cost")
            if not ctype: ctype = meta.get("type")
            if not crarity: crarity = meta.get("rarity")
    return cost, ctype, crarity


def _deck_features_v2(deck: list[dict], candidate: dict,
                      floor: int = 10, hp_ratio: float = 0.7,
                      relics: list[str] | None = None) -> list[float]:
    """Features for v2 predictor — schema adapts to pkl vocab.

    Base 32 features always returned. If pkl carries card_ids/top_relics/
    floor_buckets vocab (v2-256 schema), append deck_card_counts (80) +
    cand_card_onehot (80) + relic_onehot (50) + floor_onehot (14) for 256 total.

    floor and hp_ratio default to neutral mid-game values when unknown.
    relics is the player's currently owned relic IDs (uppercase snake-case).
    """
    card_db = _load_card_db()
    if not deck:
        deck_dims = {"attack": 0, "defense": 0, "energy": 0, "draw": 0}
        deck_arch = {"str_gain": 0, "str_user": 0,
                     "exhaust_payload": 0, "exhaust_fuel": 0, "block_payload": 0}
    else:
        deck_dims = score_deck_dimensions(deck)
        deck_arch = compute_deck_archetype(deck)
    n_cost = [0, 0, 0, 0]
    n_type = [0, 0, 0]
    n_rar = [0, 0, 0]
    for c in deck:
        cost, ctype, crarity = _card_metadata(c, card_db)
        if cost is not None:
            n_cost[min(int(cost), 3)] += 1
        if ctype in _V2_TYPES:
            n_type[_V2_TYPES.index(ctype)] += 1
        if crarity in _V2_RARITIES:
            n_rar[_V2_RARITIES.index(crarity)] += 1
    cand_cost, cand_type, cand_rar = _card_metadata(candidate, card_db)
    cand_cost_v = float(cand_cost) if cand_cost is not None else -1.0
    cand_type_oh = [1.0 if cand_type == t else 0.0 for t in _V2_TYPES]
    cand_rar_oh = [1.0 if cand_rar == r else 0.0 for r in _V2_RARITIES]
    cand_upg = 1.0 if candidate.get("upgraded") else 0.0

    # relic features — must match train_deck_predictor_v2.py
    _ENERGY_RELIC_IDS = {
        "LANTERN", "VERY_HOT_COCOA", "VENERABLE_TEA_SET",
        "PHILOSOPHERS_STONE", "PUMPKIN_CANDLE", "SOZU", "SPIKED_GAUNTLETS",
        "VELVET_CHOKER", "WHISPERING_EARRING", "BLESSED_ANTLER",
        "BLOOD_SOAKED_ROSE", "BREAD",
    }
    norm_relics = {str(r).upper().replace("-", "_") for r in (relics or [])}
    relic_count = float(len(norm_relics))
    has_energy_relic = 1.0 if (norm_relics & _ENERGY_RELIC_IDS) else 0.0
    has_bb = 1.0 if "BURNING_BLOOD" in norm_relics else 0.0

    base = [
        float(deck_dims.get("attack", 0)),
        float(deck_dims.get("defense", 0)),
        float(deck_dims.get("energy", 0)),
        float(deck_dims.get("draw", 0)),
        float(deck_arch.get("str_gain", 0)),
        float(deck_arch.get("str_user", 0)),
        float(deck_arch.get("exhaust_payload", 0)),
        float(deck_arch.get("exhaust_fuel", 0)),
        float(deck_arch.get("block_payload", 0)),
        float(n_cost[0]), float(n_cost[1]), float(n_cost[2]), float(n_cost[3]),
        float(n_type[0]), float(n_type[1]), float(n_type[2]),
        float(n_rar[0]), float(n_rar[1]), float(n_rar[2]),
        float(len(deck)),
        float(floor),
        float(hp_ratio),
        relic_count, has_energy_relic, has_bb,
        cand_cost_v,
        cand_type_oh[0], cand_type_oh[1], cand_type_oh[2],
        cand_rar_oh[0], cand_rar_oh[1], cand_rar_oh[2],
        cand_upg,
    ]

    # 12 deck × relic interaction features — must match _interaction_features
    # in train_deck_predictor_v2.py
    interactions = [
        has_energy_relic * float(n_cost[2]),
        has_energy_relic * float(n_cost[3]),
        has_energy_relic * float(len(deck)),
        has_energy_relic * float(n_type[2]),
        has_energy_relic * float(deck_dims.get("attack", 0)),
        has_bb * float(hp_ratio),
        has_bb * float(n_type[0]),
        relic_count * float(n_cost[3]),
        cand_cost_v * has_energy_relic,
        cand_type_oh[2] * has_energy_relic,
        cand_cost_v * relic_count,
        cand_type_oh[0] * has_bb,
    ]
    base = base + interactions

    # Extended 256-feat schema if pkl carries vocab
    card_ids = _PREDICTOR_VOCAB.get("card_ids") or []
    top_relics = _PREDICTOR_VOCAB.get("top_relics") or []
    floor_buckets = _PREDICTOR_VOCAB.get("floor_buckets") or []
    if card_ids:
        card_idx = {cid: i for i, cid in enumerate(card_ids)}
        deck_counts = [0.0] * len(card_ids)
        for c in deck:
            cid = _card_id_norm(c)
            if cid in card_idx:
                deck_counts[card_idx[cid]] += 1.0
        cand_oh = [0.0] * len(card_ids)
        cid = _card_id_norm(candidate)
        if cid in card_idx:
            cand_oh[card_idx[cid]] = 1.0
        relic_oh = [0.0] * len(top_relics)
        relic_idx = {r: i for i, r in enumerate(top_relics)}
        for r in norm_relics:
            if r in relic_idx:
                relic_oh[relic_idx[r]] = 1.0
        floor_oh = [1.0 if floor == f else 0.0 for f in floor_buckets]
        return base + deck_counts + cand_oh + relic_oh + floor_oh
    return base


def predictor_lift_bonus(card: dict, deck: list[dict]) -> float:
    """Predictor-driven bonus added to score_card_in_deck.

    v1: marginal predicted lift = pred(deck + card) − pred(deck), uses the
        12-dim deck-only feature schema.
    v2: returns 0 here — v2 needs the full candidate set to normalize, so the
        actual v2 bonus is computed once by pick_best_card via
        predictor_v2_set_bonuses() and added on top of base scoring.
    Returns 0 if no model is loaded."""
    pipe = _load_predictor()
    if pipe is None or not deck:
        return 0.0
    if _PREDICTOR_VERSION == "v2":
        return 0.0  # handled set-aware in pick_best_card
    try:
        import numpy as _np
        before = _np.array([_deck_features(deck)])
        after  = _np.array([_deck_features(deck + [card])])
        lift = float(pipe.predict(after)[0] - pipe.predict(before)[0])
    except Exception:
        return 0.0
    return max(-PREDICTOR_CAP, min(lift * PREDICTOR_WEIGHT, PREDICTOR_CAP))


def predictor_v2_set_bonuses(cards: list[dict], deck: list[dict]) -> list[float]:
    """For v2 predictor: compute one bonus per offered card, normalized
    within the choice set so absolute prediction bias cancels and only the
    DIFFERENTIAL ranking signal survives.

    Returns a list aligned with `cards` (same length, same order); all zeros
    if v2 isn't loaded or no deck is provided.

    Why normalize: v2 predicts run.max_floor and includes floor/hp_ratio
    features that dominate the absolute output (~0.7+ permutation importance).
    Within a single card_reward decision floor/hp/deck are CONSTANT across
    candidates, so the absolute prediction is constant too; only the small
    candidate-feature-driven variance (~0.05-0.2 floors) carries the actual
    ranking signal. Subtracting the set mean isolates that signal."""
    pipe = _load_predictor()
    if pipe is None or not str(_PREDICTOR_VERSION or "").startswith("v2") or not deck or not cards:
        return [0.0] * len(cards)
    try:
        import numpy as _np
        # Pass game-state context (floor, hp_ratio, relics) from _MC_CONTEXT if set,
        # so the v2-256 predictor can use real values instead of neutral defaults.
        ctx_floor = _MC_CONTEXT.get("floor", 10)
        ctx_max_hp = max(_MC_CONTEXT.get("max_hp", 80) or 80, 1)
        ctx_hp_ratio = _MC_CONTEXT.get("hp", 56) / ctx_max_hp
        ctx_relics = _MC_CONTEXT.get("relics")
        feats = _np.array([_deck_features_v2(deck, c, floor=ctx_floor,
                                              hp_ratio=ctx_hp_ratio,
                                              relics=ctx_relics)
                            for c in cards])
        preds = pipe.predict(feats)
        mean = float(preds.mean())
        out = []
        for p in preds:
            lift = float(p) - mean
            out.append(max(-PREDICTOR_V2_CAP, min(lift * PREDICTOR_V2_WEIGHT,
                                                  PREDICTOR_V2_CAP)))
        return out
    except Exception:
        return [0.0] * len(cards)


def dimension_balance_bonus(card: dict, deck: list[dict]) -> float:
    """Bonus when this card fills a dimension the deck is weak in.
    Score-bias toward balanced decks: a defense-poor deck gets nudged toward
    block cards; a low-energy deck toward energy-gen; etc."""
    if not deck or len(deck) < 5:
        return 0.0  # too early — let synergy logic dominate
    dims = score_deck_dimensions(deck)
    contrib = card_dimensions(card)
    bonus = 0.0
    for dim, baseline in DIM_BASELINES.items():
        if dims[dim] < baseline and contrib[dim] > 0:
            # Larger deficit + stronger card contribution → bigger bonus.
            # Normalized so a typical "fills the gap perfectly" card gets ~0.4.
            deficit = (baseline - dims[dim]) / baseline  # 0..1
            relative_fill = contrib[dim] / baseline       # often >=1 for good cards
            bonus += deficit * min(relative_fill, 1.5) * 0.5
    return min(bonus, 1.2)


# --- Deck-archetype synergy ---------------------------------------------
# Cards that GIVE strength (a Strength build wants more attacks).
STRENGTH_GAIN_CARDS = {"DEMON_FORM", "INFLAME", "LIMIT_BREAK", "SPOT_WEAKNESS",
                       "FLEX", "RUPTURE", "FEROCITY", "BRIMSTONE",
                       "BLADE_OF_INK", "DOMINATE", "SETUP_STRIKE"}
# Cards that BENEFIT FROM strength (they scale per-hit).
STRENGTH_USER_CARDS = {"HEAVY_BLADE", "PUMMEL", "TWIN_STRIKE", "WHIRLWIND",
                       "FIEND_FIRE", "ANGER", "SWORD_BOOMERANG",
                       "BLUDGEON", "PERFECTED_STRIKE", "BEAT_DOWN", "GRAPPLE",
                       "POMMEL_STRIKE", "DISMANTLE", "DROPKICK"}
# Cards that EXHAUST (enable exhaust archetype).
EXHAUST_PAYLOAD_CARDS = {"FEEL_NO_PAIN", "DARK_EMBRACE", "CORRUPTION",
                         "FIRE_BREATHING", "SENTINEL", "JUGGERNAUT",
                         "FORGOTTEN_RITUAL", "ASHEN_STRIKE", "EVIL_EYE"}
# Cards that GET EXHAUSTED naturally (fuel for exhaust payload).
EXHAUST_FUEL_CARDS = {"TRUE_GRIT", "SECOND_WIND", "OFFERING", "SEVER_SOUL",
                      "FIEND_FIRE", "REAPER", "OBLITERATE", "CARNAGE"}
# Cards that scale with block (Block archetype).
BLOCK_PAYLOAD_CARDS = {"BARRICADE", "JUGGERNAUT", "ENTRENCH", "BODY_SLAM",
                       "GRAPPLE", "METALLICIZE", "SECOND_WIND"}


def _card_id_norm(card: dict) -> str:
    cid = card.get("id", "")
    if isinstance(cid, dict): cid = cid.get("en", str(cid))
    cid = str(cid).upper().strip()
    if cid.startswith("CARD."): cid = cid[5:]
    return cid


def compute_deck_archetype(deck: list[dict]) -> dict:
    """Count synergy markers in the deck. Used to bias card picks toward what
    the deck is becoming. Returns counts (not bools) so downstream code can
    weight by saturation (one Inflame is good; three is overkill)."""
    if not deck:
        return {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
                "exhaust_fuel": 0, "block_payload": 0, "n": 0}
    counts = {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
              "exhaust_fuel": 0, "block_payload": 0, "n": len(deck)}
    for c in deck:
        cid = _card_id_norm(c)
        if cid in STRENGTH_GAIN_CARDS: counts["str_gain"] += 1
        if cid in STRENGTH_USER_CARDS: counts["str_user"] += 1
        if cid in EXHAUST_PAYLOAD_CARDS: counts["exhaust_payload"] += 1
        if cid in EXHAUST_FUEL_CARDS: counts["exhaust_fuel"] += 1
        if cid in BLOCK_PAYLOAD_CARDS: counts["block_payload"] += 1
    return counts


# ============================================================================
# Archetype-drafting experiment (STS2_ARCHETYPE env var). When set to one of the
# SpireSpy Ironclad archetypes, score_card_in_deck biases the draft toward that
# archetype's cards. INERT when unset → identical to baseline. Membership is
# detected from card effects (description keywords) + advisor axes, so it works
# on the full card pool, not just the 26 curated advisor cards.
# ============================================================================
_ACTIVE_ARCHETYPE = _os.environ.get("STS2_ARCHETYPE", "").strip().lower()
_ADV_AXES_CACHE = None


def _adv_axes_map() -> dict:
    """cid -> set(axes) from data/advisor_card_ratings.json. {} if missing."""
    global _ADV_AXES_CACHE
    if _ADV_AXES_CACHE is None:
        _ADV_AXES_CACHE = {}
        try:
            _p = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                               "..", "data", "advisor_card_ratings.json")
            with open(_p) as _f:
                for _cid, _v in _json.load(_f).items():
                    _ADV_AXES_CACHE[_cid] = set(_v.get("axes") or [])
        except (FileNotFoundError, ValueError):
            pass
    return _ADV_AXES_CACHE


def _archetype_member(card: dict, cid: str, arch: str) -> bool:
    ax = _adv_axes_map().get(cid, set())
    desc = str(card.get("description", "")).lower()
    cost = card.get("cost", 1)
    if not isinstance(cost, (int, float)):
        cost = 1
    if arch == "vulnerable":
        return "vulnerable" in desc or bool(ax & {"VULN", "VULN_AMPLIFIER", "VULN_PRODUCER"})
    if arch == "exhaust":
        return "exhaust" in desc or any(a.startswith("EXHAUST") for a in ax)
    if arch == "self_damage":
        return ("lose" in desc and "hp" in desc) or bool(ax & {"HP_LOSS", "HP_LOSS_CONSUMER"})
    if arch == "strikes":
        return "STRIKE" in cid or "strike" in desc
    if arch == "infinite_strike":
        return "STRIKE" in cid or bool(ax & {"UNLIMITED", "REPLAY", "REPEAT", "CARD_RETURN"})
    if arch == "high_cost":
        return cost >= 2
    if arch == "rampage":
        return cid == "RAMPAGE" or (bool(ax & {"MULTI_HIT_SCALING"}))
    return False


def _archetype_keystone(card: dict, cid: str, arch: str) -> bool:
    ax = _adv_axes_map().get(cid, set())
    desc = str(card.get("description", "")).lower()
    cost = card.get("cost", 1)
    if not isinstance(cost, (int, float)):
        cost = 1
    if arch == "vulnerable":
        return bool(ax & {"VULN_AMPLIFIER"}) or cid in {"CRUELTY", "DOMINATE", "MOLTEN_FIST", "COLOSSUS"}
    if arch == "exhaust":
        return bool(ax & {"EXHAUST_PRODUCER", "EXHAUST_DRAIN_PASSIVE"}) or \
            cid in {"FEEL_NO_PAIN", "DARK_EMBRACE", "CORRUPTION", "SENTINEL", "DEAD_BRANCH"}
    if arch == "self_damage":
        return bool(ax & {"HP_LOSS_CONSUMER"}) or cid in {"RUPTURE"}
    if arch == "strikes":
        return cid in {"PERFECTED_STRIKE", "TWIN_STRIKE"} or ("strike" in desc and ("for each" in desc or "per " in desc))
    if arch == "infinite_strike":
        return bool(ax & {"REPLAY", "REPEAT", "UNLIMITED"})
    if arch == "high_cost":
        return cost >= 3
    if arch == "rampage":
        return cid == "RAMPAGE"
    return False


def _archetype_lockin_bonus(card: dict, cid: str, deck: list[dict]) -> float:
    """Draft bias toward _ACTIVE_ARCHETYPE. 0.0 when no archetype is active."""
    arch = _ACTIVE_ARCHETYPE
    if not arch or not _archetype_member(card, cid, arch):
        return 0.0
    b = 3.0  # steer the draft toward this archetype from pick 1 (strong commit)
    if _archetype_keystone(card, cid, arch):
        b += 2.0  # payoffs are premium
    n_mem = sum(1 for c in deck if _archetype_member(c, _card_id_norm(c), arch))
    if n_mem >= 2:
        b += 1.5  # compounding synergy once the deck commits
    if n_mem >= 8:
        b -= 2.0  # saturation — stop over-stacking
    return b


def score_card_in_deck(card: dict, deck: list[dict]) -> float:
    """Score a card with deck-context bonuses. Reward cards that fit the
    archetype the deck is building toward; lightly penalize redundant payloads.

    Broken cards (crash combat in headless) get score 0 here so they're
    rejected by every caller — card_reward picks, shop buys, event rewards."""
    if _card_id_norm(card) in BROKEN_CARDS:
        return 0.0
    base = score_card(card)
    if not deck:
        return base
    cid = _card_id_norm(card)
    arch = compute_deck_archetype(deck)
    bonus = 0.0

    # Strength archetype: if deck has 1+ str_gain, str_user cards become more valuable.
    if arch["str_gain"] >= 1 and cid in STRENGTH_USER_CARDS:
        bonus += 1.0
    # Reverse: if deck has 2+ str_users (commits to strength), str_gain becomes more valuable.
    if arch["str_user"] >= 2 and cid in STRENGTH_GAIN_CARDS:
        bonus += 1.0

    # Exhaust archetype: payload + fuel synergy.
    if arch["exhaust_payload"] >= 1 and cid in EXHAUST_FUEL_CARDS:
        bonus += 0.7
    if arch["exhaust_fuel"] >= 2 and cid in EXHAUST_PAYLOAD_CARDS:
        bonus += 1.2

    # Block archetype: stack block payloads only if deck commits to defense.
    if arch["block_payload"] >= 1 and cid in BLOCK_PAYLOAD_CARDS:
        bonus += 0.5

    # Saturation penalty — three Inflames is one too many.
    if cid in STRENGTH_GAIN_CARDS and arch["str_gain"] >= 2:
        bonus -= 1.5
    if cid in EXHAUST_PAYLOAD_CARDS and arch["exhaust_payload"] >= 2:
        bonus -= 1.0

    # --- Jun 10: dynamic context-aware corrections ---
    # BODY_SLAM scales with block delivered per turn. Add +0.6 per
    # block_payload card already in deck (≤4 effective).
    if cid == "BODY_SLAM":
        bonus += min(arch["block_payload"], 4) * 0.6
    # OFFERING -6 HP is a real cost — penalize when deck lacks healing
    # (Bird-Faced Urn / Burning Blood etc. assumed via relics elsewhere).
    if cid == "OFFERING":
        bonus -= 2.0
        # Slight bump if Exhaust archetype committed (Offering exhausts itself
        # → fuels payloads like Dark Embrace/Feel No Pain)
        if arch["exhaust_payload"] >= 2:
            bonus += 1.0
    # BLOODLETTING -3 HP — milder version
    if cid == "BLOODLETTING":
        bonus -= 1.0
    # HEMOKINESIS -2 HP for 14 damage — already efficient, mild penalty
    if cid == "HEMOKINESIS":
        bonus -= 0.5

    # Pairwise card-card synergies — captures specific iconic combos
    # (UNRELENTING+BLUDGEON, DEMON_FORM+LIMIT_BREAK, BARRICADE+JUGGERNAUT, etc.)
    # that the coarse archetype categories above miss.
    bonus += pairwise_synergy_bonus(cid, deck)

    # Archetype-drafting experiment (inert unless STS2_ARCHETYPE is set).
    bonus += _archetype_lockin_bonus(card, cid, deck)

    # 4-dim balance bonus — nudge picks toward dimensions the deck lacks.
    bonus += dimension_balance_bonus(card, deck)

    # Learned predictor lift — data-driven nudge based on which decks
    # historically reached deeper floors. Zero until enough games collected.
    bonus += predictor_lift_bonus(card, deck)

    # Deck-size pressure (May 14): penalize picks when deck is already large.
    # Optimal STS deck is ~20-30 cards; too small (lose to RNG draws),
    # too large (key cards rarely appear). Curve: free below 25, gradual
    # penalty up to -1.5 at deck size 40+.
    n = len(deck)
    if n >= 25:
        # Linear ramp: 0 at n=25, -1.5 at n=40
        size_penalty = -min((n - 25) * 0.10, 1.5)
        bonus += size_penalty

    return max(0.0, min(base + bonus, 10.0))


def deck_quality_score(deck: list[dict]) -> float:
    """Average score of the top-10 cards in the deck. Used as a milestone reward
    proxy: a deck whose top-10 averages 6+ is in good shape; below 4.5 is weak."""
    if not deck:
        return 0.0
    scores = sorted((score_card(c) for c in deck), reverse=True)[:10]
    return sum(scores) / len(scores) if scores else 0.0


# MC-rollout opt-in flag. Set via env (STS2_MC_ROLLOUT=1) or directly from
# a calling script. When True, pick_best_card replaces the v2 set bonus with
# Monte-Carlo rollout signal (Phase 3 simulator). Off by default because
# 4s/decision overhead is fine for eval but kills training throughput.
import os as _os_mc
# Diagnostic counters — published via atexit when STS2_MC_DIAG is set.
_smart_mc_counts = {"invoked": 0, "skipped": 0}


def _print_mc_diag():
    inv, skp = _smart_mc_counts["invoked"], _smart_mc_counts["skipped"]
    total = inv + skp
    if total == 0:
        return
    rate = 100.0 * inv / total
    import sys as _s
    print(f"[MC diag] picks={total} MC-invoked={inv} v2-only={skp} ({rate:.1f}% triggered)",
          file=_s.stderr)


if _os_mc.environ.get("STS2_MC_DIAG", "") in ("1", "true"):
    import atexit
    atexit.register(_print_mc_diag)


_MC_ENV = _os_mc.environ.get("STS2_MC_ROLLOUT", "").lower()
_MC_ROLLOUT_ENABLED = _MC_ENV in ("1", "true", "on", "ensemble", "replace", "smart")
_MC_MODE = (
    "replace" if _MC_ENV == "replace"
    else "smart" if _MC_ENV == "smart"
    else "ensemble"
)
# In "smart" mode, only invoke MC when the v2 bonuses are close (top two
# differ by less than this threshold) — saves compute on decisive picks
# AND keeps MC's noise away from already-confident decisions.
_MC_SMART_THRESHOLD = float(_os_mc.environ.get("STS2_MC_SMART_THRESH", "0.15"))


def set_mc_rollout_enabled(flag: bool) -> None:
    global _MC_ROLLOUT_ENABLED
    _MC_ROLLOUT_ENABLED = bool(flag)


# Per-decision game-state context (hp / floor) for MC rollout. Callers set
# this right before they call pick_best_card so the rollout can build a
# realistic CombatState. Module-level rather than threading new args through
# every score_card_in_deck call site.
_MC_CONTEXT: dict = {"hp": 80, "max_hp": 80, "floor": 5}


def set_mc_context(hp: int, max_hp: int, floor: int,
                   relics: list[str] | None = None,
                   boss_id: str | None = None) -> None:
    """Set the run-state context the MC rollout uses to build a CombatState.

    relics — list of relic runtime IDs (uppercase snake-case) the player
    currently owns. If None, the rollout falls back to its starter default
    (currently ["BURNING_BLOOD"]). Callers that know the actual owned set
    (combat_env's card_reward path) should pass it through so things like
    Lantern / Philosophers Stone show up in the sim.

    boss_id — the act boss's encounter ID with "_BOSS" stripped (e.g.
    "VANTOM", "CEREMONIAL_BEAST", "THE_KIN"). Exposed by C# at every
    decision point via state.context.boss. When set, the MC rollout
    simulates THE ACTUAL upcoming boss instead of a random one, so deck
    construction organically counters its specific attack pattern."""
    _MC_CONTEXT["hp"] = int(hp)
    _MC_CONTEXT["max_hp"] = int(max_hp)
    _MC_CONTEXT["floor"] = int(floor)
    if relics is not None:
        _MC_CONTEXT["relics"] = list(relics)
    elif "relics" in _MC_CONTEXT:
        del _MC_CONTEXT["relics"]
    if boss_id:
        _MC_CONTEXT["boss_id"] = str(boss_id)
    elif "boss_id" in _MC_CONTEXT:
        del _MC_CONTEXT["boss_id"]


def _mc_rollout_bonuses(cards: list[dict], deck: list[dict]) -> list[float]:
    """Look up MC rollout scoring for these options. Returns 0s on failure
    so picks fall back to heuristic + v2 cleanly."""
    if not _MC_ROLLOUT_ENABLED or not cards or not deck:
        return [0.0] * len(cards)
    try:
        from agent.sim.rollout_recursive import score_candidates_via_rollout
        deck_ids = [_card_id_norm(c) for c in deck]
        # Phase 4 attempted depth=3 multi-floor rollout but it underperformed
        # depth=1 (eval 11.7 vs 12.5) because simulator-fidelity gaps
        # (un-fired trigger bodies, no relic scaling, no Energy growth) get
        # amplified over chained combats. Stick with depth=1 for the live
        # path; multi-depth is available via max_depth param when the sim
        # is hardened.
        return score_candidates_via_rollout(
            cards, deck_ids,
            hp=_MC_CONTEXT["hp"], max_hp=_MC_CONTEXT["max_hp"],
            floor=_MC_CONTEXT["floor"], n_sims=15, max_depth=1,
            relics=_MC_CONTEXT.get("relics"),
            boss_id=_MC_CONTEXT.get("boss_id"),
        )
    except Exception:
        return [0.0] * len(cards)


# ─── Phase 2: stream-aware (tag-synergy) scoring ─────────────────────────
def _card_tags(card: dict) -> list[str]:
    cid = _card_id_norm(card)
    advisor_tags = _load_advisor_tags()

    def _resolve(key: str) -> list[str]:
        hand_tags = _CARD_TAGS.get(key)
        axes = advisor_tags.get(key, [])
        if hand_tags is None:
            return list(axes)
        return hand_tags + [axis for axis in axes if axis not in hand_tags]

    tags = _resolve(cid)
    if tags:
        return tags
    # Starter cards: runtime IDs carry "_IRONCLAD" / "_SILENT" etc. suffix but
    # the wiki-sourced tag map uses bare "STRIKE" / "DEFEND". Strip the suffix
    # and retry once before giving up.
    for suffix in ("_IRONCLAD", "_SILENT", "_DEFECT", "_REGENT", "_NECROBINDER"):
        if cid.endswith(suffix):
            return _resolve(cid[:-len(suffix)])
    return []


def _deck_tag_counts(deck: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for c in deck:
        for t in _card_tags(c):
            counts[t] = counts.get(t, 0) + 1
    return counts


# ─── Archetype-driven priority (Strength flow) — Jun 9 ───────────────
# User-provided guide:
#   Early (Act1): stack 2 Inflame, keep deck lean (≤15-18 cards)
#   Mid  (Act2): trim Strikes/Defends as soon as deck is committed
#   Late (Act3): add Demon Form once energy support is in (Lantern, etc.)
#
# STS2-equivalent priorities (no Limit Break in STS2):
#   S: INFLAME (+2 permanent), DEMON_FORM (+2/turn, energy gated)
#   A: BRAND (+1 STR via exhaust), WHIRLWIND (Str×N hits, late-game burst)
#   B: PERFECTED_STRIKE (Strike-counter scaling), Multi-hits

_STR_GAINERS = {"INFLAME", "DEMON_FORM", "BRAND", "DOMINATE", "SETUP_STRIKE"}
_STR_USERS = {"TWIN_STRIKE", "POMMEL_STRIKE", "SWORD_BOOMERANG", "WHIRLWIND",
              "THRASH", "PERFECTED_STRIKE", "HEAVY_BLADE", "TEAR_ASUNDER"}


def _detect_archetype_commit(deck_ids: list[str]) -> str:
    """Return the archetype the deck has committed to, or 'none'.
    A deck is committed when (a) it has a keystone card, OR (b) it has ≥2
    cards from a single archetype's signature set."""
    str_signals = sum(1 for d in deck_ids if d in _STR_GAINERS or d in _STR_USERS)
    exh_signals = sum(1 for d in deck_ids if (
        d in _EXHAUST_KEYSTONES or d in _EXHAUST_PAYLOADS
        or d in _EXHAUST_FUEL_BURST))
    blk_signals = sum(1 for d in deck_ids if (
        d in _BLOCK_KEYSTONES or d in _BLOCK_WIN_CONDITION
        or d in _BLOCK_PAYLOADS or d in _BLOCK_PROCS))
    # Keystone presence forces commitment
    if any(d in _BLOCK_KEYSTONES for d in deck_ids):
        return "BLOCK"
    if any(d in _EXHAUST_KEYSTONES for d in deck_ids):
        return "EXHAUST"
    # Strength has no single keystone — use signal count threshold
    if str_signals >= 2 and str_signals > max(exh_signals, blk_signals):
        return "STRENGTH"
    if blk_signals >= 2 and blk_signals > max(str_signals, exh_signals):
        return "BLOCK"
    if exh_signals >= 2 and exh_signals > max(str_signals, blk_signals):
        return "EXHAUST"
    return "none"


def strength_archetype_bonus(card: dict, deck: list[dict], floor: int = 10,
                              relics: list[str] | None = None) -> float:
    """Operational priority bonus for the Strength-stacking archetype.

    Rules per user guide:
      R1: ≤2 Inflame stacking — first 2 Inflames get +6, 3rd+ none
      R2: Demon Form gated on energy support (energy relic OR ≥1 cost-reduction
          relic) AND floor ≥10 — adds +5 only when conditions met
      R3: Strength-user multi-hits get +2 if deck has ≥1 strength gainer
      R4: Deck-pruning penalty — if deck size ≥20, penalize all non-pillar
          adds (-1) to push policy toward SKIP
    """
    cid = _card_id_norm(card)
    bonus = 0.0
    deck_ids = [_card_id_norm(c) for c in (deck or [])]
    n_inflame = deck_ids.count("INFLAME")
    has_inflame = n_inflame >= 1
    has_demonform = "DEMON_FORM" in deck_ids
    n_gainers = sum(1 for c in deck_ids if c in _STR_GAINERS)

    # R1 / R1b: Inflame — stacking anchor + core-combo completion.
    # Inflame + Demon Form is the strength engine; force it to form rather
    # than leave single gainers diluted (Jun 13: three boss decks all had a
    # lone Inflame, one had a lone Demon Form, none completed the engine).
    if cid == "INFLAME":
        if has_demonform and n_inflame == 0:
            bonus += 8.0    # complete the engine from the Demon Form side
        elif n_inflame < 2:
            bonus += 6.0    # stacking anchor (first 2 Inflames)
        # 3rd+ Inflame: no bonus (diminishing return)

    # R1b / R2: Demon Form — core-combo completion or gated base value.
    elif cid == "DEMON_FORM":
        if has_inflame and not has_demonform:
            bonus += 8.0    # complete the engine (strongest pull)
        elif not has_demonform and floor >= 10:
            committed = has_inflame or n_gainers >= 2
            if committed:
                bonus += 5.0   # engine payoff — assume energy manageable
            else:
                energy_support = any(r in (relics or []) for r in (
                    "LANTERN", "VERY_HOT_COCOA", "PHILOSOPHERS_STONE",
                    "DAMARU", "BREAD", "CHANDELIER", "FUSION_HAMMER",
                ))
                bonus += 5.0 if energy_support else 2.0

    # R3: Strength users compound when deck has gainers
    if cid in _STR_USERS and n_gainers >= 1:
        bonus += 2.5 * min(n_gainers, 2)   # up to +5 with 2+ gainers

    # R4: Lean-deck penalty (deck-pruning rule) — order matters: check
    # bigger threshold first because both > 20 and > 25 trigger if/else.
    is_pillar = "SCALING_PILLAR" in _card_tags(card)
    if len(deck_ids) >= 25 and not is_pillar:
        bonus -= 3.0   # really bloated
    elif len(deck_ids) >= 20 and not is_pillar:
        bonus -= 1.5

    return bonus


# ─── Archetype-driven priority (Exhaust engine flow) — pending guide ──
# Core cards (STS2 verified):
#   S: CORRUPTION (skills cost 0 but exhaust), FEEL_NO_PAIN (block/exhaust)
#   A: DARK_EMBRACE (draw/exhaust), OFFERING (-6HP +2E +3 draw, exhaust),
#      FIEND_FIRE (exhaust hand, 7 dmg each)
#   B: HAVOC (random play+exhaust), PACTS_END (17 dmg if exhaust pile ≥3)

_EXHAUST_KEYSTONES = {"CORRUPTION"}
_EXHAUST_PAYLOADS = {"FEEL_NO_PAIN", "DARK_EMBRACE", "CHARONS_ASHES", "PACTS_END"}
_EXHAUST_FUEL_BURST = {"FIEND_FIRE", "OFFERING", "HAVOC"}


def exhaust_archetype_bonus(card: dict, deck: list[dict], floor: int = 10,
                             relics: list[str] | None = None) -> float:
    """Operational priority for the Exhaust-engine archetype.

    Awaiting full guide; conservative rules below:
      R1: CORRUPTION as the archetype keystone — +6 if not yet in deck,
          floor ≤ 13 (room to build the engine before Act-2 end)
      R2: EXHAUST_PAYLOAD (FNP/DARK_EMBRACE/etc) compounds when CORRUPTION
          exists in deck: +3 per payload added
      R3: FIEND_FIRE / OFFERING bonus when ≥2 exhaust payloads present
      R4: standard lean-deck penalty (same as strength flow)
    """
    cid = _card_id_norm(card)
    bonus = 0.0
    deck_ids = [_card_id_norm(c) for c in (deck or [])]
    has_keystone = any(d in _EXHAUST_KEYSTONES for d in deck_ids)
    n_payloads = sum(1 for d in deck_ids if d in _EXHAUST_PAYLOADS)

    # R1: keystone Corruption — kept at 6 (R1=4 tuning regressed n=60 -0.4)
    if cid in _EXHAUST_KEYSTONES and not has_keystone and floor <= 13:
        bonus += 6.0

    # R2: payloads compound with keystone
    if cid in _EXHAUST_PAYLOADS and has_keystone:
        bonus += 3.0

    # R3: burst finishers need payloads to be worth it
    if cid in _EXHAUST_FUEL_BURST and n_payloads >= 2:
        bonus += 3.0

    # R4: lean-deck penalty (shared with strength archetype)
    is_pillar = "SCALING_PILLAR" in _card_tags(card)
    if len(deck_ids) >= 25 and not is_pillar:
        bonus -= 3.0
    elif len(deck_ids) >= 20 and not is_pillar:
        bonus -= 1.5

    return bonus


# ─── Archetype-driven priority (Barricade Block-Control flow) ─────────
# Core idea: BARRICADE persists block across turns; BODY_SLAM converts the
# stacked block into a one-shot kill.
#
# Core cards (STS2 verified):
#   S: BARRICADE (keystone — without it no archetype),
#      ENTRENCH (not in STS2; use BLOOD_WALL/SECOND_WIND as proxies)
#   A: BODY_SLAM (win condition), IMPERVIOUS (30 block burst),
#      SHRUG_IT_OFF (block + draw)
#   B: IRON_WAVE, JUGGERNAUT (passive damage on block gain)
#
# STS2 substitutions:
#   ENTRENCH → BLOOD_WALL (lose 2 HP, 16 block — most efficient 2-cost)
#   SENTINEL → FORGOTTEN_RITUAL (3 energy if exhausted)

_BLOCK_KEYSTONES = {"BARRICADE"}
_BLOCK_WIN_CONDITION = {"BODY_SLAM"}
_BLOCK_PAYLOADS = {"SHRUG_IT_OFF", "IMPERVIOUS", "BLOOD_WALL", "SECOND_WIND",
                    "IRON_WAVE", "TRUE_GRIT"}
_BLOCK_PROCS = {"JUGGERNAUT"}   # benefits per block-gain event


def block_archetype_bonus(card: dict, deck: list[dict], floor: int = 10,
                          relics: list[str] | None = None) -> float:
    """Operational priority for the Barricade block-control archetype.

    Rules:
      R1: BARRICADE keystone — +6 if not yet in deck, floor ≤ 14 (Act-1/2)
      R2: BODY_SLAM is win condition — +5 when BARRICADE in deck (or any
          block-scaling card on the board); else +1
      R3: block payloads compound when BARRICADE owned (+2 each), and
          JUGGERNAUT triggers off frequency so it gets +3 if ≥3 block sources
      R4: lean-deck penalty (shared)
    """
    cid = _card_id_norm(card)
    bonus = 0.0
    deck_ids = [_card_id_norm(c) for c in (deck or [])]
    has_keystone = any(d in _BLOCK_KEYSTONES for d in deck_ids)
    n_payloads = sum(1 for d in deck_ids if d in _BLOCK_PAYLOADS)

    # R1: BARRICADE keystone — kept at 6 (R1=4 tuning regressed n=60 -0.4)
    if cid in _BLOCK_KEYSTONES and not has_keystone and floor <= 14:
        bonus += 6.0

    # R2: BODY_SLAM win condition
    if cid in _BLOCK_WIN_CONDITION:
        bonus += 5.0 if has_keystone else 1.0

    # R3: block payload compounding
    if cid in _BLOCK_PAYLOADS and has_keystone:
        bonus += 2.0
    # JUGGERNAUT scales with how often we gain block per turn
    if cid in _BLOCK_PROCS and n_payloads >= 3:
        bonus += 3.0

    # R4: lean-deck penalty (shared)
    is_pillar = "SCALING_PILLAR" in _card_tags(card)
    if len(deck_ids) >= 25 and not is_pillar:
        bonus -= 3.0
    elif len(deck_ids) >= 20 and not is_pillar:
        bonus -= 1.5

    return bonus


# Planned-route context (Phase g, Jun 13): when the map planner is active it
# publishes the ACTUAL composition of the chosen path to the boss, replacing
# the static remaining-combat estimate. Card picks then optimize against the
# real route (2 elites ahead → ELITE_OPTIMAL cards rank up, etc).
_ROUTE_CONTEXT: dict = {}


def set_route_context(mobs: int, elites: int, rests: int = 0,
                      floor: int = 0, boss_id: str | None = None) -> None:
    """Publish the planned route's remaining node composition. Called by
    map_planner.choose_map_node after each map_select planning pass."""
    _ROUTE_CONTEXT.update({
        "mobs": int(mobs), "elites": int(elites), "rests": int(rests),
        "floor": int(floor), "boss_id": boss_id,
    })


def clear_route_context() -> None:
    _ROUTE_CONTEXT.clear()


def _remaining_combats(floor: int) -> tuple[int, int, int]:
    """Remaining (mobs, elites, bosses) at given floor.

    Prefers the map planner's ACTUAL planned route (set_route_context);
    falls back to the static Act-1 estimate (10 mobs + 2 elites + 1 boss
    linear decay) when no plan is published (planner off / pre-map)."""
    f = max(1, min(int(floor or 1), 17))
    if _ROUTE_CONTEXT and abs(_ROUTE_CONTEXT.get("floor", 0) - f) <= 3:
        return (_ROUTE_CONTEXT["mobs"], _ROUTE_CONTEXT["elites"],
                1 if f < 17 else 0)
    mobs = max(0, round(10 * (17 - f) / 16))
    elites = max(0, round(2 * (14 - f) / 13)) if f < 14 else (0 if f >= 14 else 1)
    bosses = 1 if f < 17 else 0
    return mobs, elites, bosses


def combat_type_bonus(card: dict, floor: int = 10) -> float:
    """Bonus for cards tagged optimal for combat types still ahead in this run.
    Weighted by remaining-combat count so early picks favour mob-friendly
    cards (lots of mobs left), late picks favour boss-pillars (1 boss left).
    """
    tags = _card_tags(card)
    if not tags:
        return 0.0
    mobs, elites, bosses = _remaining_combats(floor)
    bonus = 0.0
    if "MOB_OPTIMAL" in tags:
        bonus += 0.1 * mobs
    if "ELITE_OPTIMAL" in tags:
        bonus += 0.5 * elites
    if "BOSS_OPTIMAL" in tags:
        bonus += 2.0 * bosses
    return bonus


def boss_defense_gap_bonus(card: dict, deck: list[dict], floor: int = 10) -> float:
    """Late Act-1 nudge for real block cards when boss readiness lacks block."""
    if not deck or floor < 12:
        return 0.0
    bpt = deck_block_per_turn(deck)
    target_bpt = 10.0
    if bpt >= target_bpt:
        return 0.0
    block = _card_field(card, "block", 0)
    if not isinstance(block, (int, float)) or block <= 0:
        return 0.0
    gap = (target_bpt - bpt) / target_bpt
    block_quality = min(float(block) / 8.0, 1.5)
    return min(5.0, gap * block_quality * 8.0)


def boss_readiness_lift_bonus(card: dict, deck: list[dict], floor: int = 10) -> float:
    """Prioritize cards that materially improve a boss-unready deck.

    Tag bonuses can over-favor mob-efficient attacks early. This bonus looks at
    the actual operational boss metrics (burst, block, engine, versatility) and
    amplifies the marginal lift only while the deck is still below target.
    """
    if _os.environ.get("STS2_BOSS_READINESS_LIFT", "") not in ("1", "true", "on"):
        return 0.0
    if not deck or floor < 3:
        return 0.0
    before = deck_quality_metrics(deck)
    readiness = float(before.get("overall", 0.0) or 0.0)
    target = 0.70
    if readiness >= target:
        return 0.0
    after = deck_quality_metrics(deck + [card])
    lift = float(after.get("overall", 0.0) or 0.0) - readiness
    if lift <= 0:
        return 0.0
    gap = target - readiness
    return min(3.0, lift * gap * 75.0)


def tag_synergy_bonus(card: dict, deck: list[dict], floor: int = 10) -> float:
    """Stage-aware tag bonus on top of base scoring.

    Stage weights (floor-driven): early picks favour raw card strength;
    once tags accumulate the model rewards matching tags more; late game
    a SCALING_PILLAR bonus ensures growth cards (Body Slam, Demon Form,
    Inflame, Whirlwind, …) join the deck.

    Synergy per tag = min(deck_count * 0.5, 3.0)  — capped to prevent
    runaway from oversaturated streams. Per-card total clamped at 5.0
    before the stage weight applies.

    Pillar bonus (when card has SCALING_PILLAR tag AND deck has <2 pillars):
      early=0, mid=+2.0, late=+4.0 — guarantees at least 1-2 pillar cards
      enter the deck by Act-1 mid/late.
    """
    tags = _card_tags(card)
    if not tags:
        return 0.0
    if floor < 7:
        syn_w, pillar_w = 0.3, 0.0
    elif floor < 13:
        syn_w, pillar_w = 1.0, 2.0
    else:
        syn_w, pillar_w = 1.5, 4.0

    deck_counts = _deck_tag_counts(deck or [])
    syn_total = 0.0
    for t in tags:
        syn_total += min(deck_counts.get(t, 0) * 0.5, 3.0)
    syn_total = min(syn_total, 5.0)
    bonus = syn_total * syn_w

    if "SCALING_PILLAR" in tags:
        n_pillars = sum(1 for c in (deck or [])
                        if "SCALING_PILLAR" in _card_tags(c))
        if n_pillars < 2:
            bonus += pillar_w
    return bonus


def pick_best_card(cards: list[dict], threshold: float = 3.5,
                   deck: list[dict] = None) -> int | None:
    """Return index of the best card above threshold, or None to skip.
    If `deck` is provided, uses deck-aware scoring (synergy bonuses) and the
    v2 set-normalized predictor bonus (when v2 model is loaded).

    When STS2_MC_ROLLOUT=1 (env var) and `set_mc_context()` has been called
    with valid game state, the MC rollout signal REPLACES the v2 bonus
    (richer-but-slower forward simulation outranks the deck-only regressor).

    Cards in BROKEN_CARDS are force-skipped (they crash combat in headless)."""
    if not cards:
        return None
    # Filter broken cards before scoring so they're never picked, even if their
    # synergy/predictor scores rank highest.
    valid = [(i, c) for i, c in enumerate(cards) if _card_id_norm(c) not in BROKEN_CARDS]
    if not valid:
        return None  # all offered cards are blacklisted → skip
    valid_cards = [c for _, c in valid]
    scorer = (lambda c: score_card_in_deck(c, deck)) if deck else score_card
    base = [scorer(c) for c in valid_cards]
    # Set-aware bonus combination:
    #   STS2_MC_ROLLOUT=replace  → MC bonus replaces v2 (Phase 3 step 2)
    #   STS2_MC_ROLLOUT=ensemble → 0.5 MC + 0.5 v2 (Phase 3 ensemble)
    #   STS2_MC_ROLLOUT=smart    → MC only when v2 top-two are close;
    #                              otherwise pure v2 (saves compute + noise)
    #   off → v2 only
    if _MC_ROLLOUT_ENABLED and deck:
        v2 = predictor_v2_set_bonuses(valid_cards, deck)
        if _MC_MODE == "smart":
            # Decide whether v2 is decisive enough to skip MC
            sorted_v2 = sorted(v2, reverse=True)
            top_gap = (sorted_v2[0] - sorted_v2[1]) if len(sorted_v2) >= 2 else 0.0
            if top_gap >= _MC_SMART_THRESHOLD:
                set_bonus = v2
                _smart_mc_counts["skipped"] += 1
            else:
                mc = _mc_rollout_bonuses(valid_cards, deck)
                set_bonus = [0.5 * a + 0.5 * b for a, b in zip(v2, mc)]
                _smart_mc_counts["invoked"] += 1
        elif _MC_MODE == "replace":
            mc = _mc_rollout_bonuses(valid_cards, deck)
            set_bonus = mc
            _smart_mc_counts["invoked"] += 1
        else:  # "ensemble"
            mc = _mc_rollout_bonuses(valid_cards, deck)
            set_bonus = [0.5 * a + 0.5 * b for a, b in zip(v2, mc)]
            _smart_mc_counts["invoked"] += 1
    else:
        set_bonus = (predictor_v2_set_bonuses(valid_cards, deck)
                     if deck else [0.0] * len(valid_cards))
    # Phase 2 tag-synergy bonus: stream-aware deck building. Uses _MC_CONTEXT
    # floor when set (mid-run picks know which phase they're in); falls back
    # to a neutral floor=10 otherwise.
    ctx_floor = int(_MC_CONTEXT.get("floor", 10) or 10)
    tag_bonus = ([tag_synergy_bonus(c, deck or [], ctx_floor) for c in valid_cards]
                 if deck else [0.0] * len(valid_cards))
    # L2 combat-type bonus: weight cards by remaining (mob/elite/boss) combats
    ct_bonus = [combat_type_bonus(c, ctx_floor) for c in valid_cards]
    # Late Act-1 boss readiness: when block/turn is below target, real block
    # cards must overcome generic attack-tag momentum.
    bd_bonus = ([boss_defense_gap_bonus(c, deck or [], ctx_floor) for c in valid_cards]
                if deck else [0.0] * len(valid_cards))
    # Boss-readiness lift: when the deck is operationally unready, prefer the
    # card that improves the actual boss metrics over mob-efficient tag picks.
    br_bonus = ([boss_readiness_lift_bonus(c, deck or [], ctx_floor) for c in valid_cards]
                if deck else [0.0] * len(valid_cards))
    # Quality-lift bonus reduced to × 3 (Jun 9, eval showed × 10 destabilized
    # picks for ckpt 13255k_TAG which was tuned to lower-magnitude bonuses).
    q_bonus = [0.0] * len(valid_cards)
    if deck:
        base_q = deck_quality_metrics(deck)["overall"]
        for i, c in enumerate(valid_cards):
            new_q = deck_quality_metrics(deck + [c])["overall"]
            q_bonus[i] = (new_q - base_q) * 3.0
    # Archetype operational bonuses (3 flows from user guide) — with lock-in:
    # once deck commits to one archetype (keystone present OR ≥2 archetype
    # cards), suppress other archetypes' bonuses so the policy stays the course
    # instead of pivoting mid-Act.
    ctx_relics = _MC_CONTEXT.get("relics")
    deck_ids_norm = [_card_id_norm(c) for c in (deck or [])]
    commit = _detect_archetype_commit(deck_ids_norm)
    sa_bonus = [strength_archetype_bonus(c, deck or [], ctx_floor, ctx_relics)
                if commit in ("none", "STRENGTH") else 0.0
                for c in valid_cards]
    ea_bonus = [exhaust_archetype_bonus(c, deck or [], ctx_floor, ctx_relics)
                if commit in ("none", "EXHAUST") else 0.0
                for c in valid_cards]
    ba_bonus = [block_archetype_bonus(c, deck or [], ctx_floor, ctx_relics)
                if commit in ("none", "BLOCK") else 0.0
                for c in valid_cards]
    arch_bonus = [max(s, e, b) for s, e, b in zip(sa_bonus, ea_bonus, ba_bonus)]
    # Bandit Q adjustment: per-card historical avg max_floor signal.
    # Returns 0 for cards with <30 picks (sparse), small ±0.5/floor otherwise.
    q_adj = [q_adjustment(c) for c in valid_cards]
    totals = [b + s + t + ct + bd + br + q + a + qa
              for b, s, t, ct, bd, br, q, a, qa in
              zip(base, set_bonus, tag_bonus, ct_bonus, bd_bonus, br_bonus,
                  q_bonus, arch_bonus, q_adj)]
    scored = sorted(enumerate(totals), key=lambda x: x[1], reverse=True)
    best_valid_idx, best_score = scored[0]
    if best_score < threshold:
        return None
    # Probabilistic selection (Jun 10): if STS2_CARD_PICK_TEMP > 0, sample by
    # softmax over scores instead of argmax. Low temp (0.3-0.5) keeps mostly
    # the same picks but lets the Q-bandit learn from occasional explores of
    # near-top alternatives. Default off (deterministic argmax).
    temp_env = _os.environ.get("STS2_CARD_PICK_TEMP", "0")
    try:
        temperature = float(temp_env)
    except ValueError:
        temperature = 0.0
    if temperature > 0:
        import math as _math
        import random as _rand
        max_t = max(totals)
        exps = [_math.exp((t - max_t) / temperature) for t in totals]
        total = sum(exps)
        if total > 0:
            r = _rand.random() * total
            cum = 0.0
            for i, e in enumerate(exps):
                cum += e
                if r <= cum:
                    return valid[i][0]
    return valid[best_valid_idx][0]  # remap to original cards index


# ─── Outcome-feedback bandit (Jun 10) ─────────────────────────────────
# Tracks per-card Q value = (avg run max_floor when this card was picked).
# Persisted to data/card_q_values.json. card_scoring.q_adjustment(card) returns
# a delta added to score_card_in_deck so low-scoring cards that empirically
# correlate with high-floor outcomes get boosted, and vice versa.
import os as _os_q
_CARD_Q_PATH = _os_q.path.join(_os_q.path.dirname(_os_q.path.abspath(__file__)),
                                 "..", "data", "card_q_values.json")
_CARD_Q: dict[str, dict] = {}  # cid → {"n": int, "sum": float}
_CARD_Q_LOADED = False


def _load_card_q():
    global _CARD_Q, _CARD_Q_LOADED
    if _CARD_Q_LOADED:
        return
    _CARD_Q_LOADED = True
    try:
        import json as _jq
        with open(_CARD_Q_PATH) as f:
            _CARD_Q = _jq.load(f)
    except (FileNotFoundError, ValueError):
        _CARD_Q = {}


def update_card_q(card_id: str, run_max_floor: int) -> None:
    """Call once per card picked in a completed run. card_id should be
    canonical (uppercase underscore form). Updates running mean of
    run.max_floor across picks of this card."""
    _load_card_q()
    cid = str(card_id).upper().replace("-", "_")
    rec = _CARD_Q.setdefault(cid, {"n": 0, "sum": 0.0})
    rec["n"] += 1
    rec["sum"] += float(run_max_floor)


def save_card_q() -> None:
    """Persist learned Q values to disk. Call at process exit or periodically."""
    _load_card_q()
    try:
        import json as _jq
        _os_q.makedirs(_os_q.path.dirname(_CARD_Q_PATH) or ".", exist_ok=True)
        with open(_CARD_Q_PATH, "w") as f:
            _jq.dump(_CARD_Q, f, indent=1)
    except Exception:
        pass


def q_adjustment(card: dict, min_picks: int = 30) -> float:
    """Score adjustment from learned Q value. Center reward at 10
    (≈ average max_floor in current eval). Each floor above/below 10 maps to
    ±0.5 score delta. min_picks=30 prevents tiny-sample noise."""
    _load_card_q()
    cid = _card_id_norm(card)
    rec = _CARD_Q.get(cid)
    if not rec or rec["n"] < min_picks:
        return 0.0
    avg = rec["sum"] / rec["n"]
    return (avg - 10.0) * 0.5


def removal_value(deck: list[dict]) -> float:
    """Quantify the marginal value of removing the deck's worst card.

    Empirical observation (Jun 10): removal payoff is strong at deck size ≤ 15,
    moderate at 15-20, decays sharply beyond 20-30 because:
      - Small deck cycles faster — removing 1 junk = real boost to core-draw rate
      - Large deck dilutes removal impact (Strike already a small fraction)

    Formula:
      size_factor: 1.0 (size ≤15), → 0.4 (size=20), → 0.1 (size=30), → 0.05 (>30)
      junk_factor: (5 - worst_score) / 5, capped [0, 1]
      return = size_factor × junk_factor × 10  (scaled to compare with buy_card scores)

    Use in shop decisions: when removal_value(deck) > best buyable card score,
    pick remove. When deck is bloated AND has no junk, value is near 0 (skip).
    """
    if not deck:
        return 0.0
    size = len(deck)
    worst = min(score_card(c) for c in deck)

    # Size-decay piecewise (matches user's "deck < 20 strong, > 20 weak" rule)
    if size <= 15:
        size_factor = 1.0
    elif size <= 20:
        size_factor = 0.4 + 0.6 * (20 - size) / 5.0
    elif size <= 30:
        size_factor = 0.1 + 0.3 * (30 - size) / 10.0
    else:
        size_factor = 0.05

    # Junk factor: removing a 2-score Strike worth way more than 5-score average
    junk_factor = max(0.0, min(1.0, (5.0 - worst) / 5.0))

    return size_factor * junk_factor * 10.0


def pick_worst_card(cards: list[dict], threshold: float = 5.0) -> int | None:
    """Return index of the worst card below threshold for removal, or None."""
    if not cards:
        return None
    scored = [(i, score_card(c)) for i, c in enumerate(cards)]
    scored.sort(key=lambda x: x[1])
    worst_idx, worst_score = scored[0]
    if worst_score < threshold:
        return worst_idx
    return None
