"""
card_scoring.py — Heuristic card scoring for deck-building decisions.

Scores each card 0-10 based on damage/block/cost efficiency, special effects,
and synergy potential. Used by greedy_action() for card_reward, shop, and
card_select (removal) decisions.
"""
import json as _json
import os as _os

# === Empirical bonus from gameplay statistics ===
# Generated by agent/collect_deck_stats.py: log-ratio of card frequency in
# boss-reach decks vs early-died decks. Cards that empirically correlate with
# reaching the boss get a positive bonus (capped ±1.5). Re-run that script
# whenever the policy or strategy shifts substantially to refresh the data.
_EMPIRICAL_PATH = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", "data", "card_empirical.json")
try:
    with open(_EMPIRICAL_PATH) as _ef:
        EMPIRICAL_BONUS = _json.load(_ef)
except (FileNotFoundError, ValueError):
    EMPIRICAL_BONUS = {}

# Empirical bonus DISABLED (Run 23 retry showed avg_floor regression
# 14.3 → 9.9 vs Run 22 baseline despite weight=0.3 / min_magnitude=0.5
# settings). The data was collected from 3706k's own gameplay, so even
# small bonuses reinforced existing biases and caused the policy to drift
# off the verified-good Run 22 working point. Set weight=0.0 to disable
# without removing the data file; flip back if a future run uses externally
# collected stats (e.g. from a *different* policy or human play).
EMPIRICAL_WEIGHT = 0.0
EMPIRICAL_MIN_MAGNITUDE = 0.5

# Manual overrides for known high/low value cards.
# Cards not listed get scored by the generic formula.
OVERRIDES: dict[str, float] = {
    # === Ironclad top picks (9-10) ===
    "FEED": 9.5,            # kill an enemy → heal + max HP
    "DEMON_FORM": 9.5,      # +2 str/turn is game-winning
    "CORRUPTION": 9.0,      # skills cost 0, insane with dead branch
    "BRIMSTONE": 9.0,       # +2 str/turn, low downside for Ironclad
    "LIMIT_BREAK": 9.0,     # double strength
    "IMPERVIOUS": 9.0,      # 30 block
    "OFFERING": 8.5,        # draw + energy, life cost is fine
    "DARK_EMBRACE": 8.5,    # draw on exhaust synergy
    "FEEL_NO_PAIN": 8.5,    # block on exhaust
    "JUGGERNAUT": 8.5,      # each block = damage — game-winning in block-heavy decks
    "SENTINEL": 8.0,        # 3 energy if exhausted
    "SECOND_WIND": 8.0,     # exhaust + block
    "TRUE_GRIT": 7.5,       # exhaust 1, draw 2
    "WARCRY": 7.0,          # draw with no downside
    "SHRUG_IT_OFF": 8.0,    # 8 block + draw 1
    "SPOT_WEAKNESS": 6.5,   # +3 str if enemy attacking — strong conditional
    "BRUTALITY": 5.5,       # 0-cost draw at 1 HP/turn — aggressive cycle

    # === STS2 new cards — top picks (8-9) ===
    "HOWL_FROM_BEYOND": 9.0,   # AOE that auto-replays from exhaust pile each turn
    "APOTHEOSIS": 9.0,         # upgrade ALL cards (colorless) — enormous value
    "AGGRESSION": 8.5,         # power: free upgraded Attack from discard each turn
    "ADRENALINE": 8.0,         # 0-cost: gain 1 energy + draw 2 (no HP cost in STS2)
    "SHOCKWAVE": 7.5,          # AOE Weak + Vulnerable to all enemies — huge setup
    "FORGOTTEN_RITUAL": 8.0,   # gain energy when exhaust — capped (generic formula over-scores)
    "HELLRAISER": 8.0,         # auto-plays Strike on draw — free attacks all game
    "MOLTEN_FIST": 8.0,        # doubles target's Vulnerable — huge damage multiplier
    "DISMANTLE": 7.5,          # 13 dmg; hits twice if Vulnerable (26 for 1 energy)
    "BLADE_OF_INK": 6.0,       # this turn: +1 str per Attack — scales with attack-heavy turns
    "POMMEL_STRIKE": 7.5,      # 9 dmg + draw 1 (generic formula gives 8.5, slightly lower)
    "UNRELENTING": 7.5,        # 12 dmg + next Attack costs 0 — energy generation
    "BLUDGEON": 7.5,           # simple heavy single-target damage
    "SETUP_STRIKE": 7.0,       # 9 dmg + temporary strength this turn
    "GRAPPLE": 7.0,            # dmg + deals extra per block gained this turn
    "VICIOUS": 6.5,            # draw when you apply Vulnerable
    "INFERNAL_BLADE": 7.0,     # add free random Attack to hand
    "PERFECTED_STRIKE": 6.5,   # scales with Strike count (good early, less later)
    "CINDER": 5.5,             # dmg + forced exhaust top of draw (can trash good card)
    "BLOOD_WALL": 4.0,         # HP loss for block — net negative, avoid
    "BREAKTHROUGH": 6.0,       # AOE but costs HP — trade-off
    "EVIL_EYE": 6.0,           # block + extra block on exhaust — conditional
    "DOMINATE": 6.5,           # apply Vuln + gain Str per Vuln on enemy — strong offensive
    "TAUNT": 7.0,              # block + apply Vulnerable — efficient dual-purpose skill
    "JUGGLING": 5.5,           # power: add copy of 3rd Attack played each turn — free attacks
    "EXPECT_A_FIGHT": 5.0,     # gain 1 energy per Attack in hand — strong in attack-heavy decks
    "ASHEN_STRIKE": 5.0,       # damage scales with exhaust pile — strong with exhaust synergy
    "TREMBLE": 4.5,            # 1-cost Apply Vulnerable — combo piece with attack-heavy deck
    "RUPTURE": 4.5,            # power: +1 Str when losing HP from card — synergy with OFFERING/BRUTALITY
    "FEROCITY": 6.5,           # power: +1 Str per Attack played — snowballs in attack-heavy deck
    "HEARTSEEKER": 7.0,        # 8 dmg + 1 Vulnerable — efficient attack/debuff combo
    "OBLITERATE": 7.5,         # 20 dmg Exhaust — high single-hit for 1 energy
    "PREDATOR": 6.5,           # 15 dmg + conditional draw — good damage with upside

    # === Strong cards (7-8) ===
    "BARRICADE": 8.5,        # block persists between turns — enables massive block stacking
    "CARNAGE": 7.5,         # 20 damage for free (ethereal)
    "RECKLESS_CHARGE": 7.0, # 7 dmg + wound, still good DPE
    "CLEAVE": 7.0,          # AOE 8 damage
    "UPPERCUT": 7.5,        # 13 dmg + vuln + weak
    "PUMMEL": 7.0,          # multi-hit with str scaling
    "BURNING_PACT": 7.0,   # draw 2 + exhaust
    "INFLAME": 8.0,         # +2 str (power, persistent)
    "METALLICIZE": 7.5,     # +3 block/turn (power)
    "BATTLE_TRANCE": 7.0,   # draw 3
    "BLOODLETTING": 7.0,    # free energy
    "RAGE": 7.0,            # block on attack plays
    "DROPKICK": 8.0,        # 5 dmg + draw + energy if vuln target
    "WHIRLWIND": 1.0,       # X-cost AOE — causes NullRef crash in headless (BUG-034)
    "HEAVY_BLADE": 7.0,     # scales with str (3x multiplier)
    "SWORD_BOOMERANG": 7.0, # 3x3 random hits
    "CLASH": 6.5,           # 0-cost, 14 dmg — great in attack-heavy decks
    "BEAT_DOWN": 7.0,       # play N attacks from discard — strong reuse with good attacks
    "ANOINTED": 6.0,        # put all rares from draw pile into hand — useful mid/late game

    # === STS2 colorless decent picks (5-7) ===
    "DRAMATIC_ENTRANCE": 7.0,  # free AOE damage on combat start (Ethereal, costs 0)
    "METAMORPHOSIS": 6.5,   # add N free Attacks to draw pile — extra resources
    "BEAT_INTO_SHAPE": 6.5, # damage that scales with hits this turn — strong multi-hit
    "PANACHE": 6.0,         # power: AOE damage every 5 cards played
    "MASTER_OF_STRATEGY": 6.0, # draw 3, exhaust — card advantage
    "ANGER": 5.0,           # damage + copy in discard (scaling but clogs deck)
    "DARK_SHACKLES": 4.5,   # reduce enemy strength this turn — situational defensive
    "BLIGHT_STRIKE": 5.0,   # damage + apply Doom — Doom may not tick in headless (BUG-021)
    "DISCOVERY": 5.5,       # choose 1 of 3 random cards free — card quality upgrade
    "JACK_OF_ALL_TRADES": 5.0,  # add random colorless cards — inconsistent

    # === Decent cards (5-6) ===
    "ANGELIC_DEW": 5.5,
    "ARMAMENTS": 6.0,       # upgrade hand
    "BASH": 6.0,            # starter but vulnerable is good
    "BLOOD_FOR_BLOOD": 6.0,
    "BODY_SLAM": 6.5,       # scales with block
    "CLOTHESLINE": 5.5,     # 12 dmg + weak
    "COMBUST": 5.5,
    "ENTRENCH": 5.5,
    "FIEND_FIRE": 6.0,
    "FLEX": 5.0,
    "HAVOC": 5.5,
    "HEADBUTT": 5.5,        # 9 dmg + put card back on draw
    "HEMOKINESIS": 6.0,
    "IRON_WAVE": 5.5,       # 5 dmg + 5 block for 1
    "POWER_THROUGH": 6.0,  # 15 block, adds wounds
    "PUNCTURE": 5.0,
    "RAMPAGE": 5.5,
    "SEARING_BLOW": 5.0,   # needs upgrades
    "SEVER_SOUL": 5.5,
    "THUNDERCLAP": 7.0,    # AOE damage + Vulnerable to ALL enemies (strong setup)
    "TWIN_STRIKE": 6.0,    # 5x2 = 10 for 1
    "WILD_STRIKE": 5.5,    # 12 dmg, wound to draw

    # === Mediocre (3-4) ===
    "DEFEND": 3.0,          # basic, want to remove
    "DEFEND_IRONCLAD": 3.0,
    "DEFEND_SILENT": 3.0,
    "DEFEND_DEFECT": 3.0,
    "STRIKE": 2.0,          # basic, want to remove
    "STRIKE_IRONCLAD": 2.0,
    "STRIKE_SILENT": 2.0,
    "STRIKE_DEFECT": 2.0,
    "WOUND": 1.0,           # pure bad
    "DAZE": 1.0,
    "SLIMED": 1.0,
    "BURN": 0.5,
}

# Type-based generic scoring weights
ATTACK_DPE_BASELINE = 6.0   # Strike: 6 dmg / 1 cost
BLOCK_BPE_BASELINE = 5.0    # Defend: 5 block / 1 cost
DRAW_VALUE = 2.5            # per card drawn — Run 22 verified (3.0 caused regression in Run 24)
ENERGY_VALUE = 5.0          # per energy generated — Run 22 verified
LOW_COST_BONUS = 0.0        # 0-cost universal bonus — disabled after Run 24 showed
                            # avg_floor 14.3→11.2 regression. The bonus pulled the policy
                            # toward cheap utility cards at expense of damage. Re-enable
                            # only with stronger filtering (e.g. only when paired with draw/energy).
ONE_COST_BONUS = 0.0
VULN_WEAK_VALUE = 1.5       # vulnerable or weak bonus
STRENGTH_VALUE = 2.5        # per point of strength
DEXTERITY_VALUE = 2.0       # per point of dexterity
EXHAUST_VALUE = 1.0         # exhaust synergy bonus
AOE_VALUE = 1.5             # AOE bonus
POWER_BONUS = 1.5           # powers persist, extra value
RARITY_BONUS = {"Common": 0.0, "Uncommon": 0.5, "Rare": 1.0}

# Cards whose OnPlay throws NullReferenceException in headless mode (the
# game expects some manager/VFX singleton that doesn't exist when running
# without Godot). Playing them inside a combat poisons the async task chain,
# stalls ActionExecutor for ~10s, and trashes training metrics (cwr→13%,
# cr→85%). Until we patch the underlying call in setup.sh's IL pass, we
# blacklist them in pick_best_card so the agent never adds them to its deck.
# Identified 2026-05-26 from training_run_full8 collapse at chunk 53.2%:
#   System.NullReferenceException at FlashOfSteel.OnPlay
#   System.NullReferenceException at Whirlwind.OnPlay
# (Whirlwind was already known from memory: BUG-034 / commit 936231d; the
# Steam-update May 22 reopened the same NullRef path that the C# fix had
# addressed.)
BROKEN_CARDS = {"FLASH_OF_STEEL", "WHIRLWIND"}

# Threshold above which an un-upgraded card should be a SMITH target at the next
# rest site. Calibrated so DEMON_FORM/BARRICADE/HOWL_FROM_BEYOND/LIMIT_BREAK and
# top draw/energy enablers (OFFERING/SHRUG_IT_OFF/POMMEL_STRIKE) all qualify, but
# common Strike/Defend variants do not.
SMITH_PRIORITY_THRESHOLD = 7.0

# Cards that are never worth picking (status/curse starters)
SKIP_IDS = {"STRIKE_R", "DEFEND_R", "STRIKE_B", "DEFEND_B", "STRIKE_G",
            "DEFEND_G", "WOUND", "DAZE", "SLIMED", "BURN", "DECAY",
            # STS2 naming variants
            "STRIKE_IRONCLAD", "DEFEND_IRONCLAD",
            "STRIKE_SILENT", "DEFEND_SILENT",
            "STRIKE_DEFECT", "DEFEND_DEFECT",
            # STS2 curses/status cards
            "DOUBT", "REGRET", "SHAME", "VOID", "NORMALITY"}


def score_card(card: dict) -> float:
    """Score a card 0-10 based on its effectiveness.

    card: dict with keys: id, cost, type, rarity, stats, name, keywords

    Broken cards (BROKEN_CARDS — crash combat in headless mode) get score 0
    so they're never selected by any deck-less scoring path either."""
    if _card_id_norm(card) in BROKEN_CARDS:
        return 0.0
    card_id = card.get("id", "")
    if isinstance(card_id, dict):
        card_id = card_id.get("en", str(card_id))
    card_id = card_id.upper().strip()
    # Game prefixes IDs with "CARD." — strip it for override lookups
    if card_id.startswith("CARD."):
        card_id = card_id[5:]

    # Check manual override first — but DO still apply empirical bonus below
    # so the data-driven signal can nudge override values up/down.
    if card_id in OVERRIDES:
        score = OVERRIDES[card_id]
        if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
            _eb = EMPIRICAL_BONUS[card_id]
            if abs(_eb) >= EMPIRICAL_MIN_MAGNITUDE:
                score += _eb * EMPIRICAL_WEIGHT
        return max(0.0, min(score, 10.0))

    # Skip status/curse cards
    if card_id in SKIP_IDS:
        return 0.0

    raw_cost = card.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        raw_cost = 1
    cost = max(raw_cost, 1)  # treat 0-cost as 1 for ratio calc
    ctype = (card.get("type") or "").lower()
    rarity = card.get("rarity", "Common")
    stats = card.get("stats") or {}
    name = card.get("name", "")
    if isinstance(name, dict):
        name = name.get("en", "")

    score = 0.0
    # Low-cost combo bonus — 0-cost cards stack in high-energy turns,
    # 1-cost cards still cycle cheaply. Boss wins correlate with playing
    # many cards per turn, and cost is the gate.
    if raw_cost == 0:
        score += LOW_COST_BONUS
    elif raw_cost == 1:
        score += ONE_COST_BONUS

    # === Attack cards: score by damage per energy ===
    if ctype == "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            dpe = damage / cost
            score += min(dpe / ATTACK_DPE_BASELINE * 5.0, 7.0)

    # === Skill cards: score by block, draw, energy ===
    elif ctype == "skill":
        block = stats.get("block", 0)
        if block > 0:
            bpe = block / cost
            score += min(bpe / BLOCK_BPE_BASELINE * 4.0, 5.0)

    # === Power cards: base value + effect scoring ===
    elif ctype == "power":
        score += POWER_BONUS
        # Powers with str/dex are very strong
        if "strength" in str(stats).lower() or "str" in str(stats).lower():
            score += STRENGTH_VALUE
        if "dexterity" in str(stats).lower() or "dex" in str(stats).lower():
            score += DEXTERITY_VALUE

    # === Generic bonuses ===
    # Draw value
    draw = stats.get("draw", 0)
    if draw > 0:
        score += draw * DRAW_VALUE

    # Energy generation
    energy = stats.get("energy", 0)
    if energy > 0:
        score += energy * ENERGY_VALUE

    # Block on any card (not just skills)
    if ctype != "skill":
        block = stats.get("block", 0)
        if block > 0:
            score += min(block / cost * 0.5, 3.0)

    # Damage on non-attack cards
    if ctype != "attack":
        damage = stats.get("damage", 0)
        if damage > 0:
            score += min(damage / cost * 0.5, 3.0)

    # Check keywords/description for effects
    desc = str(card.get("description", "")).lower()
    if "vulnerable" in desc:
        score += VULN_WEAK_VALUE
    if "weak" in desc:
        score += VULN_WEAK_VALUE
    if "strength" in desc and ctype != "power":
        score += STRENGTH_VALUE * 0.5
    if "exhaust" in desc:
        score += EXHAUST_VALUE
    if "all enem" in desc:
        score += AOE_VALUE
    if "draw" in desc and draw == 0:
        score += DRAW_VALUE  # draw mentioned but not in stats

    # Rarity bonus
    score += RARITY_BONUS.get(rarity, 0.0)

    # Empirical bonus from boss-reach correlation data
    if EMPIRICAL_BONUS and card_id in EMPIRICAL_BONUS:
        score += EMPIRICAL_BONUS[card_id] * EMPIRICAL_WEIGHT

    # Clamp to 0-10
    return max(0.0, min(score, 10.0))


def best_smith_target(deck: list[dict]) -> int | None:
    """Index in `deck` of the highest-value un-upgraded card worth a SMITH.

    Returns None if no card in the deck scores >= SMITH_PRIORITY_THRESHOLD when
    un-upgraded. Used by rest_site_action to override the default heal-vs-smith
    HP threshold: there's no point healing 5 HP if a key DEMON_FORM is sitting
    un-upgraded — upgrading it pays off across every remaining combat.
    """
    if not deck:
        return None
    best_idx, best_score = None, -1.0
    for i, c in enumerate(deck):
        if c.get("upgraded"):
            continue
        s = score_card(c)
        if s >= SMITH_PRIORITY_THRESHOLD and s > best_score:
            best_idx, best_score = i, s
    return best_idx


# --- Pairwise card-card synergy (subagent-generated) -------------------
# Loaded from data/card_synergies.py. Each entry: card_id → list of (other_id, score)
# tuples. When picking card B for the deck, sum synergy(A, B) for each A already
# in the deck — gives a deck-context-aware bonus that captures real combos
# (e.g. UNRELENTING + BLUDGEON, DEMON_FORM + LIMIT_BREAK).
try:
    from data.card_synergies import SYNERGIES as _PAIRWISE_SYNERGIES
except ImportError:
    _PAIRWISE_SYNERGIES = {}

PAIRWISE_WEIGHT = 0.4   # Multiplier on summed pairwise synergy. 0.4 caps a single
                        # iconic 3.0-pair at +1.2; multiple weak pairs sum but get
                        # capped further by the per-card overall clamp.
PAIRWISE_CAP = 2.5      # Maximum pairwise bonus per card pick (prevents runaway
                        # for cards that synergize with many deck members).


def pairwise_synergy_bonus(card_id: str, deck: list[dict]) -> float:
    """Sum of synergy scores between card_id and every card already in deck.
    Multi-copy in deck multiplies (e.g. 2 INFLAMEs in deck = 2× synergy).
    Returns 0 if no synergies match. Capped at PAIRWISE_CAP."""
    if not _PAIRWISE_SYNERGIES or not deck or card_id not in _PAIRWISE_SYNERGIES:
        return 0.0
    pairs = dict(_PAIRWISE_SYNERGIES[card_id])  # other_id → score
    total = 0.0
    for c in deck:
        other = _card_id_norm(c)
        if other in pairs:
            total += pairs[other]
    return min(total * PAIRWISE_WEIGHT, PAIRWISE_CAP)


# --- 4-dimension deck capability scoring (May 11) -----------------------
# Rate the deck across four axes — attack output, defense, energy gen, draw —
# then bias new card picks toward the weakest axis. Prevents over-stacking
# attacks at the cost of defense (which was the failure mode in 5692k boss
# fights: deck had strong damage but couldn't survive incoming AoE).

# Target "good deck" levels — used as deficit reference. A deck whose per-card
# average reaches these is well-rounded.
DIM_BASELINES = {"attack": 3.0, "defense": 1.5, "energy": 0.20, "draw": 0.25}


def card_dimensions(card: dict) -> dict[str, float]:
    """How much this card contributes to each dimension. Per-card scalars,
    not per-energy — so a 0-cost draw card is correctly scored without
    division blow-up."""
    cid = _card_id_norm(card)
    if cid in SKIP_IDS:
        return {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    ctype = (card.get("type") or "").lower()
    raw_cost = card.get("cost", 1)
    if not isinstance(raw_cost, (int, float)):
        raw_cost = 1
    cost = max(raw_cost, 1)
    stats = card.get("stats") or {}
    res = {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    dmg = stats.get("damage", 0) or 0
    if ctype == "attack" and dmg > 0:
        res["attack"] = dmg / cost
    blk = stats.get("block", 0) or 0
    if blk > 0:
        res["defense"] = blk / cost
    e = stats.get("energy", 0) or 0
    if e > 0:
        res["energy"] = float(e)
    d = stats.get("draw", 0) or 0
    if d > 0:
        res["draw"] = float(d)
    # Powers: strength-gain count as attack potential (4 dmg-equiv per 1 str
    # over a fight averaging ~4 attacks); energy-per-turn powers count as energy.
    if ctype == "power":
        desc = str(card.get("description", "")).lower()
        if "strength" in desc and "lose" not in desc and "enem" not in desc:
            res["attack"] += 4.0
        if "dexterity" in desc:
            res["defense"] += 2.5
        if "energy" in desc and ("each turn" in desc or "every turn" in desc):
            res["energy"] += 1.0
        if "draw" in desc and ("each turn" in desc or "every turn" in desc):
            res["draw"] += 1.0
    return res


def score_deck_dimensions(deck: list[dict]) -> dict[str, float]:
    """Per-card average across 4 dimensions. Useful for diagnosing which axis
    the deck is weak on."""
    if not deck:
        return {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    totals = {"attack": 0.0, "defense": 0.0, "energy": 0.0, "draw": 0.0}
    for c in deck:
        d = card_dimensions(c)
        for k, v in d.items():
            totals[k] += v
    n = len(deck)
    return {k: v / n for k, v in totals.items()}


# --- Learned deck predictor (May 12) -----------------------------------
# Loaded lazily from data/deck_predictor.pkl. Predicts max_floor for a deck;
# we use the marginal lift "predicted(deck + card) − predicted(deck)" as a bonus.
_PREDICTOR_PIPELINE = None
_PREDICTOR_LOADED = False


_PREDICTOR_VERSION = None  # "v1" or "v2"; set during _load_predictor
_CARD_DB = None            # cached card_id → metadata lookup (for v2)


def _load_card_db():
    """Lazy-load data/card_metadata.json. Returns empty dict if missing."""
    global _CARD_DB
    if _CARD_DB is not None:
        return _CARD_DB
    path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                         "..", "data", "card_metadata.json")
    if not _os.path.exists(path):
        _CARD_DB = {}
        return _CARD_DB
    try:
        import json as _json
        with open(path) as f:
            _CARD_DB = _json.load(f)
    except Exception:
        _CARD_DB = {}
    return _CARD_DB


def _load_predictor():
    """Prefer v2 (data/deck_predictor_v2.pkl, 30-dim card-aware features) over
    v1 (data/deck_predictor.pkl, 12-dim deck-only). Falls back gracefully if
    only one exists."""
    global _PREDICTOR_PIPELINE, _PREDICTOR_LOADED, _PREDICTOR_VERSION
    if _PREDICTOR_LOADED:
        return _PREDICTOR_PIPELINE
    _PREDICTOR_LOADED = True
    try:
        import pickle as _pk
        # Try v2 first; v1 fallback
        for path_rel, default_ver in [("data/deck_predictor_v2.pkl", "v2"),
                                       ("data/deck_predictor.pkl", "v1")]:
            path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                 "..", path_rel)
            if not _os.path.exists(path):
                continue
            with open(path, "rb") as f:
                blob = _pk.load(f)
            _PREDICTOR_PIPELINE = blob.get("pipeline")
            _PREDICTOR_VERSION = blob.get("version", default_ver)
            return _PREDICTOR_PIPELINE
        return None
    except Exception:
        return None


def _deck_features(deck: list[dict], floor_crossed: int = 10) -> list[float]:
    """Same feature layout as agent/train_deck_predictor.py FEATURE_NAMES.
    `floor_crossed` defaults to 10 — the deck is evaluated as if at the fl=10
    milestone for relative comparison; what matters is the *difference* in
    prediction between (deck) and (deck + new_card)."""
    if not deck:
        return [floor_crossed, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    dims = score_deck_dimensions(deck)
    arch = compute_deck_archetype(deck)
    return [
        float(floor_crossed),
        float(len(deck)),
        float(deck_quality_score(deck)),
        float(dims["attack"]),
        float(dims["defense"]),
        float(dims["energy"]),
        float(dims["draw"]),
        float(arch.get("str_gain", 0)),
        float(arch.get("str_user", 0)),
        float(arch.get("exhaust_payload", 0)),
        float(arch.get("exhaust_fuel", 0)),
        float(arch.get("block_payload", 0)),
    ]


PREDICTOR_WEIGHT = 0.3   # bonus = predictor_lift × this. Predictor outputs floors;
                          # 1-floor lift → +0.3 bonus.
PREDICTOR_CAP = 1.2       # hard cap to prevent runaway bonuses from a confident model.

# v2 inference uses a separate scale: it predicts run.max_floor directly given
# (deck features + candidate features); the model's training y mean is ~10.5
# so we center the prediction. v2 variance across candidates at one decision
# point is typically ±0.5-1 floor, so weight 0.4 / cap 1.0 keeps it on par
# with v1 in effective contribution to score_card_in_deck.
PREDICTOR_V2_CENTER = 10.5
PREDICTOR_V2_WEIGHT = 0.4
PREDICTOR_V2_CAP = 1.0

# v2 feature-extraction vocab — must stay synced with train_deck_predictor_v2.py
_V2_TYPES = ["Attack", "Skill", "Power"]
_V2_RARITIES = ["Common", "Uncommon", "Rare"]


def _card_metadata(card: dict, card_db: dict) -> tuple:
    """Return (cost, type, rarity) for a card, preferring its own fields then
    falling back to card_db lookup by normalized id."""
    cost = card.get("cost")
    ctype = card.get("type")
    crarity = card.get("rarity")
    if cost is None or not ctype or not crarity:
        cid = _card_id_norm(card)
        meta = card_db.get(cid)
        if meta:
            if cost is None: cost = meta.get("cost")
            if not ctype: ctype = meta.get("type")
            if not crarity: crarity = meta.get("rarity")
    return cost, ctype, crarity


def _deck_features_v2(deck: list[dict], candidate: dict,
                      floor: int = 10, hp_ratio: float = 0.7) -> list[float]:
    """30-dim features for v2 predictor (matches train_deck_predictor_v2.py).

    floor and hp_ratio default to neutral mid-game values when unknown — the
    most important features at any single decision are constant across the
    3 candidates anyway; what matters is differential candidate ranking.
    """
    card_db = _load_card_db()
    if not deck:
        deck_dims = {"attack": 0, "defense": 0, "energy": 0, "draw": 0}
        deck_arch = {"str_gain": 0, "str_user": 0,
                     "exhaust_payload": 0, "exhaust_fuel": 0, "block_payload": 0}
    else:
        deck_dims = score_deck_dimensions(deck)
        deck_arch = compute_deck_archetype(deck)
    n_cost = [0, 0, 0, 0]
    n_type = [0, 0, 0]
    n_rar = [0, 0, 0]
    for c in deck:
        cost, ctype, crarity = _card_metadata(c, card_db)
        if cost is not None:
            n_cost[min(int(cost), 3)] += 1
        if ctype in _V2_TYPES:
            n_type[_V2_TYPES.index(ctype)] += 1
        if crarity in _V2_RARITIES:
            n_rar[_V2_RARITIES.index(crarity)] += 1
    cand_cost, cand_type, cand_rar = _card_metadata(candidate, card_db)
    cand_cost_v = float(cand_cost) if cand_cost is not None else -1.0
    cand_type_oh = [1.0 if cand_type == t else 0.0 for t in _V2_TYPES]
    cand_rar_oh = [1.0 if cand_rar == r else 0.0 for r in _V2_RARITIES]
    cand_upg = 1.0 if candidate.get("upgraded") else 0.0
    return [
        float(deck_dims.get("attack", 0)),
        float(deck_dims.get("defense", 0)),
        float(deck_dims.get("energy", 0)),
        float(deck_dims.get("draw", 0)),
        float(deck_arch.get("str_gain", 0)),
        float(deck_arch.get("str_user", 0)),
        float(deck_arch.get("exhaust_payload", 0)),
        float(deck_arch.get("exhaust_fuel", 0)),
        float(deck_arch.get("block_payload", 0)),
        float(n_cost[0]), float(n_cost[1]), float(n_cost[2]), float(n_cost[3]),
        float(n_type[0]), float(n_type[1]), float(n_type[2]),
        float(n_rar[0]), float(n_rar[1]), float(n_rar[2]),
        float(len(deck)),
        float(floor),
        float(hp_ratio),
        cand_cost_v,
        cand_type_oh[0], cand_type_oh[1], cand_type_oh[2],
        cand_rar_oh[0], cand_rar_oh[1], cand_rar_oh[2],
        cand_upg,
    ]


def predictor_lift_bonus(card: dict, deck: list[dict]) -> float:
    """Predictor-driven bonus added to score_card_in_deck.

    v1: marginal predicted lift = pred(deck + card) − pred(deck), uses the
        12-dim deck-only feature schema.
    v2: returns 0 here — v2 needs the full candidate set to normalize, so the
        actual v2 bonus is computed once by pick_best_card via
        predictor_v2_set_bonuses() and added on top of base scoring.
    Returns 0 if no model is loaded."""
    pipe = _load_predictor()
    if pipe is None or not deck:
        return 0.0
    if _PREDICTOR_VERSION == "v2":
        return 0.0  # handled set-aware in pick_best_card
    try:
        import numpy as _np
        before = _np.array([_deck_features(deck)])
        after  = _np.array([_deck_features(deck + [card])])
        lift = float(pipe.predict(after)[0] - pipe.predict(before)[0])
    except Exception:
        return 0.0
    return max(-PREDICTOR_CAP, min(lift * PREDICTOR_WEIGHT, PREDICTOR_CAP))


def predictor_v2_set_bonuses(cards: list[dict], deck: list[dict]) -> list[float]:
    """For v2 predictor: compute one bonus per offered card, normalized
    within the choice set so absolute prediction bias cancels and only the
    DIFFERENTIAL ranking signal survives.

    Returns a list aligned with `cards` (same length, same order); all zeros
    if v2 isn't loaded or no deck is provided.

    Why normalize: v2 predicts run.max_floor and includes floor/hp_ratio
    features that dominate the absolute output (~0.7+ permutation importance).
    Within a single card_reward decision floor/hp/deck are CONSTANT across
    candidates, so the absolute prediction is constant too; only the small
    candidate-feature-driven variance (~0.05-0.2 floors) carries the actual
    ranking signal. Subtracting the set mean isolates that signal."""
    pipe = _load_predictor()
    if pipe is None or _PREDICTOR_VERSION != "v2" or not deck or not cards:
        return [0.0] * len(cards)
    try:
        import numpy as _np
        feats = _np.array([_deck_features_v2(deck, c) for c in cards])
        preds = pipe.predict(feats)
        mean = float(preds.mean())
        out = []
        for p in preds:
            lift = float(p) - mean
            out.append(max(-PREDICTOR_V2_CAP, min(lift * PREDICTOR_V2_WEIGHT,
                                                  PREDICTOR_V2_CAP)))
        return out
    except Exception:
        return [0.0] * len(cards)


def dimension_balance_bonus(card: dict, deck: list[dict]) -> float:
    """Bonus when this card fills a dimension the deck is weak in.
    Score-bias toward balanced decks: a defense-poor deck gets nudged toward
    block cards; a low-energy deck toward energy-gen; etc."""
    if not deck or len(deck) < 5:
        return 0.0  # too early — let synergy logic dominate
    dims = score_deck_dimensions(deck)
    contrib = card_dimensions(card)
    bonus = 0.0
    for dim, baseline in DIM_BASELINES.items():
        if dims[dim] < baseline and contrib[dim] > 0:
            # Larger deficit + stronger card contribution → bigger bonus.
            # Normalized so a typical "fills the gap perfectly" card gets ~0.4.
            deficit = (baseline - dims[dim]) / baseline  # 0..1
            relative_fill = contrib[dim] / baseline       # often >=1 for good cards
            bonus += deficit * min(relative_fill, 1.5) * 0.5
    return min(bonus, 1.2)


# --- Deck-archetype synergy ---------------------------------------------
# Cards that GIVE strength (a Strength build wants more attacks).
STRENGTH_GAIN_CARDS = {"DEMON_FORM", "INFLAME", "LIMIT_BREAK", "SPOT_WEAKNESS",
                       "FLEX", "RUPTURE", "FEROCITY", "BRIMSTONE",
                       "BLADE_OF_INK", "DOMINATE", "SETUP_STRIKE"}
# Cards that BENEFIT FROM strength (they scale per-hit).
STRENGTH_USER_CARDS = {"HEAVY_BLADE", "PUMMEL", "TWIN_STRIKE", "WHIRLWIND",
                       "FIEND_FIRE", "ANGER", "SWORD_BOOMERANG",
                       "BLUDGEON", "PERFECTED_STRIKE", "BEAT_DOWN", "GRAPPLE",
                       "POMMEL_STRIKE", "DISMANTLE", "DROPKICK"}
# Cards that EXHAUST (enable exhaust archetype).
EXHAUST_PAYLOAD_CARDS = {"FEEL_NO_PAIN", "DARK_EMBRACE", "CORRUPTION",
                         "FIRE_BREATHING", "SENTINEL", "JUGGERNAUT",
                         "FORGOTTEN_RITUAL", "ASHEN_STRIKE", "EVIL_EYE"}
# Cards that GET EXHAUSTED naturally (fuel for exhaust payload).
EXHAUST_FUEL_CARDS = {"TRUE_GRIT", "SECOND_WIND", "OFFERING", "SEVER_SOUL",
                      "FIEND_FIRE", "REAPER", "OBLITERATE", "CARNAGE"}
# Cards that scale with block (Block archetype).
BLOCK_PAYLOAD_CARDS = {"BARRICADE", "JUGGERNAUT", "ENTRENCH", "BODY_SLAM",
                       "GRAPPLE", "METALLICIZE", "SECOND_WIND"}


def _card_id_norm(card: dict) -> str:
    cid = card.get("id", "")
    if isinstance(cid, dict): cid = cid.get("en", str(cid))
    cid = str(cid).upper().strip()
    if cid.startswith("CARD."): cid = cid[5:]
    return cid


def compute_deck_archetype(deck: list[dict]) -> dict:
    """Count synergy markers in the deck. Used to bias card picks toward what
    the deck is becoming. Returns counts (not bools) so downstream code can
    weight by saturation (one Inflame is good; three is overkill)."""
    if not deck:
        return {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
                "exhaust_fuel": 0, "block_payload": 0, "n": 0}
    counts = {"str_gain": 0, "str_user": 0, "exhaust_payload": 0,
              "exhaust_fuel": 0, "block_payload": 0, "n": len(deck)}
    for c in deck:
        cid = _card_id_norm(c)
        if cid in STRENGTH_GAIN_CARDS: counts["str_gain"] += 1
        if cid in STRENGTH_USER_CARDS: counts["str_user"] += 1
        if cid in EXHAUST_PAYLOAD_CARDS: counts["exhaust_payload"] += 1
        if cid in EXHAUST_FUEL_CARDS: counts["exhaust_fuel"] += 1
        if cid in BLOCK_PAYLOAD_CARDS: counts["block_payload"] += 1
    return counts


def score_card_in_deck(card: dict, deck: list[dict]) -> float:
    """Score a card with deck-context bonuses. Reward cards that fit the
    archetype the deck is building toward; lightly penalize redundant payloads.

    Broken cards (crash combat in headless) get score 0 here so they're
    rejected by every caller — card_reward picks, shop buys, event rewards."""
    if _card_id_norm(card) in BROKEN_CARDS:
        return 0.0
    base = score_card(card)
    if not deck:
        return base
    cid = _card_id_norm(card)
    arch = compute_deck_archetype(deck)
    bonus = 0.0

    # Strength archetype: if deck has 1+ str_gain, str_user cards become more valuable.
    if arch["str_gain"] >= 1 and cid in STRENGTH_USER_CARDS:
        bonus += 1.0
    # Reverse: if deck has 2+ str_users (commits to strength), str_gain becomes more valuable.
    if arch["str_user"] >= 2 and cid in STRENGTH_GAIN_CARDS:
        bonus += 1.0

    # Exhaust archetype: payload + fuel synergy.
    if arch["exhaust_payload"] >= 1 and cid in EXHAUST_FUEL_CARDS:
        bonus += 0.7
    if arch["exhaust_fuel"] >= 2 and cid in EXHAUST_PAYLOAD_CARDS:
        bonus += 1.2

    # Block archetype: stack block payloads only if deck commits to defense.
    if arch["block_payload"] >= 1 and cid in BLOCK_PAYLOAD_CARDS:
        bonus += 0.5

    # Saturation penalty — three Inflames is one too many.
    if cid in STRENGTH_GAIN_CARDS and arch["str_gain"] >= 2:
        bonus -= 1.5
    if cid in EXHAUST_PAYLOAD_CARDS and arch["exhaust_payload"] >= 2:
        bonus -= 1.0

    # Pairwise card-card synergies — captures specific iconic combos
    # (UNRELENTING+BLUDGEON, DEMON_FORM+LIMIT_BREAK, BARRICADE+JUGGERNAUT, etc.)
    # that the coarse archetype categories above miss.
    bonus += pairwise_synergy_bonus(cid, deck)

    # 4-dim balance bonus — nudge picks toward dimensions the deck lacks.
    bonus += dimension_balance_bonus(card, deck)

    # Learned predictor lift — data-driven nudge based on which decks
    # historically reached deeper floors. Zero until enough games collected.
    bonus += predictor_lift_bonus(card, deck)

    # Deck-size pressure (May 14): penalize picks when deck is already large.
    # Optimal STS deck is ~20-30 cards; too small (lose to RNG draws),
    # too large (key cards rarely appear). Curve: free below 25, gradual
    # penalty up to -1.5 at deck size 40+.
    n = len(deck)
    if n >= 25:
        # Linear ramp: 0 at n=25, -1.5 at n=40
        size_penalty = -min((n - 25) * 0.10, 1.5)
        bonus += size_penalty

    return max(0.0, min(base + bonus, 10.0))


def deck_quality_score(deck: list[dict]) -> float:
    """Average score of the top-10 cards in the deck. Used as a milestone reward
    proxy: a deck whose top-10 averages 6+ is in good shape; below 4.5 is weak."""
    if not deck:
        return 0.0
    scores = sorted((score_card(c) for c in deck), reverse=True)[:10]
    return sum(scores) / len(scores) if scores else 0.0


# MC-rollout opt-in flag. Set via env (STS2_MC_ROLLOUT=1) or directly from
# a calling script. When True, pick_best_card replaces the v2 set bonus with
# Monte-Carlo rollout signal (Phase 3 simulator). Off by default because
# 4s/decision overhead is fine for eval but kills training throughput.
import os as _os_mc
_MC_ROLLOUT_ENABLED = _os_mc.environ.get("STS2_MC_ROLLOUT", "").lower() in ("1", "true", "on")


def set_mc_rollout_enabled(flag: bool) -> None:
    global _MC_ROLLOUT_ENABLED
    _MC_ROLLOUT_ENABLED = bool(flag)


# Per-decision game-state context (hp / floor) for MC rollout. Callers set
# this right before they call pick_best_card so the rollout can build a
# realistic CombatState. Module-level rather than threading new args through
# every score_card_in_deck call site.
_MC_CONTEXT: dict = {"hp": 80, "max_hp": 80, "floor": 5}


def set_mc_context(hp: int, max_hp: int, floor: int) -> None:
    _MC_CONTEXT["hp"] = int(hp)
    _MC_CONTEXT["max_hp"] = int(max_hp)
    _MC_CONTEXT["floor"] = int(floor)


def _mc_rollout_bonuses(cards: list[dict], deck: list[dict]) -> list[float]:
    """Look up MC rollout scoring for these options. Returns 0s on failure
    so picks fall back to heuristic + v2 cleanly."""
    if not _MC_ROLLOUT_ENABLED or not cards or not deck:
        return [0.0] * len(cards)
    try:
        from agent.sim.rollout_recursive import score_candidates_via_rollout
        deck_ids = [_card_id_norm(c) for c in deck]
        return score_candidates_via_rollout(
            cards, deck_ids,
            hp=_MC_CONTEXT["hp"], max_hp=_MC_CONTEXT["max_hp"],
            floor=_MC_CONTEXT["floor"], n_sims=15,
        )
    except Exception:
        return [0.0] * len(cards)


def pick_best_card(cards: list[dict], threshold: float = 3.5,
                   deck: list[dict] = None) -> int | None:
    """Return index of the best card above threshold, or None to skip.
    If `deck` is provided, uses deck-aware scoring (synergy bonuses) and the
    v2 set-normalized predictor bonus (when v2 model is loaded).

    When STS2_MC_ROLLOUT=1 (env var) and `set_mc_context()` has been called
    with valid game state, the MC rollout signal REPLACES the v2 bonus
    (richer-but-slower forward simulation outranks the deck-only regressor).

    Cards in BROKEN_CARDS are force-skipped (they crash combat in headless)."""
    if not cards:
        return None
    # Filter broken cards before scoring so they're never picked, even if their
    # synergy/predictor scores rank highest.
    valid = [(i, c) for i, c in enumerate(cards) if _card_id_norm(c) not in BROKEN_CARDS]
    if not valid:
        return None  # all offered cards are blacklisted → skip
    valid_cards = [c for _, c in valid]
    scorer = (lambda c: score_card_in_deck(c, deck)) if deck else score_card
    base = [scorer(c) for c in valid_cards]
    # Set-aware bonus: MC rollout > v2 predictor (richer signal when enabled)
    if _MC_ROLLOUT_ENABLED and deck:
        set_bonus = _mc_rollout_bonuses(valid_cards, deck)
    else:
        set_bonus = (predictor_v2_set_bonuses(valid_cards, deck)
                     if deck else [0.0] * len(valid_cards))
    scored = sorted(enumerate(b + s for b, s in zip(base, set_bonus)),
                    key=lambda x: x[1], reverse=True)
    best_valid_idx, best_score = scored[0]
    if best_score >= threshold:
        return valid[best_valid_idx][0]  # remap to original cards index
    return None


def pick_worst_card(cards: list[dict], threshold: float = 5.0) -> int | None:
    """Return index of the worst card below threshold for removal, or None."""
    if not cards:
        return None
    scored = [(i, score_card(c)) for i, c in enumerate(cards)]
    scored.sort(key=lambda x: x[1])
    worst_idx, worst_score = scored[0]
    if worst_score < threshold:
        return worst_idx
    return None
