// <auto-generated>
// Generated by tools/audit_godot_stub_refs.py --emit-stubs from the holes the audit found in
// src/GodotStubs against lib/sts2.dll, using the real GodotSharp.dll as the signature oracle.
// No-op headless stubs: methods do nothing and return what Godot returns for 'nothing' (empty string,
// empty arrays/collections, Error.Failed, else default); properties are auto-properties; singletons exist.
// Hand-written stubs live in the other files and always win -- this file only fills holes, and every
// stub type is `partial` so it can add members without editing the hand-written declaration.
// Do not hand-edit; re-run the audit after a game update and append the new output instead.
// </auto-generated>
#nullable disable
#pragma warning disable CS0067, CS0108, CS0109, CS0114, CS0169, CS0414, CS0649, CS0660, CS0661, CS8618, CS0824

namespace Godot
{
    public partial class AcceptDialog : global::Godot.Window
    {
        public new partial class SignalName : global::Godot.Window.SignalName
        {
        }
    }
    public partial class AnimationMixer : global::Godot.Node
    {
        public bool Active { set { } }
        public new partial class SignalName : global::Godot.Node.SignalName
        {
            public static readonly global::Godot.StringName AnimationFinished = "animation_finished";
        }
    }
    public partial class AnimationPlayer
    {
        public string CurrentAnimation { get; set; } = "";
    }
    public partial class AspectRatioContainer
    {
        public new partial class MethodName : global::Godot.Container.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Container.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Container.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class AssemblyHasScriptsAttribute
    {
        public AssemblyHasScriptsAttribute(global::System.Type[] scriptTypes) { }
    }
    public partial class AtlasTexture
    {
        public global::Godot.Rect2 Margin { set { } }
    }
    public static partial class AudioServer
    {
        public static global::Godot.AudioServerInstance Singleton { get; set; } = new();
    }
    public partial class AudioServerInstance : global::Godot.GodotObject
    {
        public int GetBusIndex(global::Godot.StringName busName) { return default; }
        public void SetBusVolumeDb(int busIdx, float volumeDb) { }
    }
    public partial class AudioStreamPlayer
    {
        public bool IsPlaying() { return default; }
        public global::Godot.StringName Bus { set { } }
        public float PitchScale { set { } }
        public float VolumeLinear { set { } }
    }
    public partial class BackBufferCopy
    {
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class BaseButton
    {
        public partial class SignalName
        {
            public static readonly global::Godot.StringName ButtonUp = "button_up";
        }
    }
    public partial class BoxContainer
    {
        public new partial class MethodName : global::Godot.Container.MethodName
        {
        }
        public new partial class PropertyName : global::Godot.Container.PropertyName
        {
        }
        public new partial class SignalName : global::Godot.Container.SignalName
        {
        }
    }
    public partial class CanvasItem
    {
        public global::Godot.Vector2 GetGlobalMousePosition() { return default; }
        public global::Godot.Transform2D GetGlobalTransform() { return default; }
        public global::Godot.Transform2D GetGlobalTransformWithCanvas() { return default; }
        public global::Godot.Material GetMaterial() { return default; }
        public global::Godot.Transform2D GetViewportTransform() { return default; }
        public void MoveToFront() { }
        public global::Godot.CanvasItem.ClipChildrenMode ClipChildren { set { } }
        public global::Godot.Material Material { get; set; }
        public bool UseParentMaterial { set { } }
        public int ZIndex { get; set; }
        public event global::System.Action ItemRectChanged;
        public enum ClipChildrenMode : long { Disabled = 0, Only = 1, AndDraw = 2, Max = 3 }
        public new partial class SignalName : global::Godot.Node.SignalName
        {
            public static readonly global::Godot.StringName ItemRectChanged = "item_rect_changed";
            public static readonly global::Godot.StringName VisibilityChanged = "visibility_changed";
        }
    }
    public partial class CanvasItemMaterial
    {
        public global::Godot.CanvasItemMaterial.BlendModeEnum BlendMode { set { } }
        public enum BlendModeEnum : long { Mix = 0, Add = 1, Sub = 2, Mul = 3, PremultAlpha = 4 }
    }
    public partial class CanvasLayer : global::Godot.Node
    {
    }
    public partial class CharFXTransform
    {
        public void SetGlyphIndex(uint glyphIndex) { }
        public global::Godot.Rid Font { get; set; }
        public uint GlyphIndex { get; set; }
        public global::Godot.Vector2I Range { get; set; }
    }
    public partial class ColorRect
    {
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class ConfirmationDialog : global::Godot.AcceptDialog
    {
        public new partial class SignalName : global::Godot.AcceptDialog.SignalName
        {
        }
    }
    public partial class Container
    {
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class Control
    {
        public void AddThemeColorOverride(global::Godot.StringName name, global::Godot.Color color) { }
        public void AddThemeConstantOverride(global::Godot.StringName name, int constant) { }
        public void AddThemeFontOverride(global::Godot.StringName name, global::Godot.Font font) { }
        public void AddThemeFontSizeOverride(global::Godot.StringName name, int fontSize) { }
        public void AddThemeStyleboxOverride(global::Godot.StringName name, global::Godot.StyleBox stylebox) { }
        public global::Godot.Vector2 GetMinimumSize() { return default; }
        public int GetThemeConstant(global::Godot.StringName name, global::Godot.StringName themeType) { return default; }
        public global::Godot.Font GetThemeFont(global::Godot.StringName name, global::Godot.StringName themeType) { return default; }
        public int GetThemeFontSize(global::Godot.StringName name, global::Godot.StringName themeType) { return default; }
        public bool HasThemeFont(global::Godot.StringName name, global::Godot.StringName themeType) { return default; }
        public bool HasThemeFontOverride(global::Godot.StringName name) { return default; }
        public void RemoveThemeColorOverride(global::Godot.StringName name) { }
        public void RemoveThemeFontSizeOverride(global::Godot.StringName name) { }
        public void ResetSize() { }
        public void SetAnchorAndOffset(global::Godot.Side side, float anchor, float offset, bool pushOppositeAnchor) { }
        public void SetAnchorsPreset(global::Godot.Control.LayoutPreset preset, bool keepOffsets) { }
        public void SetFocusBehaviorRecursive(global::Godot.Control.FocusBehaviorRecursiveEnum focusBehaviorRecursive) { }
        public void SetMouseBehaviorRecursive(global::Godot.Control.MouseBehaviorRecursiveEnum mouseBehaviorRecursive) { }
        public global::Godot.Control.FocusBehaviorRecursiveEnum FocusBehaviorRecursive { get; set; }
        public global::Godot.NodePath FocusNeighborBottom { get; set; } = new();
        public global::Godot.NodePath FocusNeighborLeft { get; set; } = new();
        public global::Godot.NodePath FocusNeighborRight { get; set; } = new();
        public global::Godot.NodePath FocusNeighborTop { get; set; } = new();
        public global::Godot.Control.CursorShape MouseDefaultCursorShape { set { } }
        public float OffsetBottom { get; set; }
        public float OffsetLeft { get; set; }
        public float OffsetRight { get; set; }
        public float OffsetTop { get; set; }
        public float RotationDegrees { get; set; }
        public global::Godot.Control.SizeFlags SizeFlagsHorizontal { get; set; }
        public enum CursorShape : long { Arrow = 0, Ibeam = 1, PointingHand = 2, Cross = 3, Wait = 4, Busy = 5, Drag = 6, CanDrop = 7, Forbidden = 8, Vsize = 9, Hsize = 10, Bdiagsize = 11, Fdiagsize = 12, Move = 13, Vsplit = 14, Hsplit = 15, Help = 16 }
        public enum FocusBehaviorRecursiveEnum : long { Inherited = 0, Disabled = 1, Enabled = 2 }
        public partial class MethodName
        {
            public static readonly global::Godot.StringName GrabFocus = "grab_focus";
        }
        public enum MouseBehaviorRecursiveEnum : long { Inherited = 0, Disabled = 1, Enabled = 2 }
        public partial class PropertyName
        {
            public static readonly global::Godot.StringName Size = "size";
        }
        public partial class SignalName
        {
            public static readonly global::Godot.StringName GuiInput = "gui_input";
        }
        [global::System.Flags] public enum SizeFlags : long { ShrinkBegin = 0, Fill = 1, Expand = 2, ExpandFill = 3, ShrinkCenter = 4, ShrinkEnd = 8 }
    }
    public partial class CpuParticles2D
    {
        public float EmissionSphereRadius { set { } }
        public global::Godot.Vector2 Gravity { set { } }
        public float InitialVelocityMax { set { } }
        public float InitialVelocityMin { set { } }
        public float ScaleAmountMax { set { } }
        public float ScaleAmountMin { get; set; }
        public global::Godot.Texture2D Texture { get; set; }
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
            public static readonly global::Godot.StringName Finished = "finished";
        }
    }
    public partial class Curve2D : global::Godot.Resource
    {
        public float GetBakedLength() { return default; }
        public global::Godot.Transform2D SampleBakedWithRotation(float offset, bool cubic) { return default; }
        public void SetPointPosition(int idx, global::Godot.Vector2 position) { }
        public int PointCount { get; set; }
    }
    public partial class CurveXyzTexture : global::Godot.Texture2D
    {
        public global::Godot.Curve CurveX { get; set; }
        public global::Godot.Curve CurveY { get; set; }
    }
    public partial class DirAccess
    {
        public static global::Godot.Error CopyAbsolute(string from, string to, int chmodFlags) { return global::Godot.Error.Failed; }
        public bool CurrentIsDir() { return default; }
        public static string[] GetDirectoriesAt(string path) { return global::System.Array.Empty<string>(); }
        public static string[] GetFilesAt(string path) { return global::System.Array.Empty<string>(); }
        public string GetNext() { return ""; }
        public global::Godot.Error ListDirBegin() { return global::Godot.Error.Failed; }
        public global::Godot.Error Remove(string path) { return global::Godot.Error.Failed; }
        public static global::Godot.Error RemoveAbsolute(string path) { return global::Godot.Error.Failed; }
        public static global::Godot.Error RenameAbsolute(string from, string to) { return global::Godot.Error.Failed; }
        public bool IncludeHidden { set { } }
    }
    public partial class DisplayServer
    {
        public static global::Godot.DisplayServer.ScreenOrientation ScreenGetOrientation(int screen) { return default; }
        public static global::Godot.Vector2I ScreenGetPosition(int screen) { return default; }
        public static int WindowGetCurrentScreen(int windowId) { return default; }
        public static global::Godot.Vector2I WindowGetMaxSize(int windowId) { return default; }
        public static global::Godot.Vector2I WindowGetMinSize(int windowId) { return default; }
        public static global::Godot.Vector2I WindowGetPosition(int windowId) { return default; }
        public static bool WindowIsFocused(int windowId) { return default; }
        public static void WindowSetCurrentScreen(int screen, int windowId) { }
        public static void WindowSetMode(global::Godot.DisplayServer.WindowMode mode, int windowId) { }
        public static void WindowSetPosition(global::Godot.Vector2I position, int windowId) { }
        public static void WindowSetSize(global::Godot.Vector2I size, int windowId) { }
        public static void WindowSetTitle(string title, int windowId) { }
        public static void WindowSetVsyncMode(global::Godot.DisplayServer.VSyncMode vsyncMode, int windowId) { }
        public enum ScreenOrientation : long { Landscape = 0, Portrait = 1, ReverseLandscape = 2, ReversePortrait = 3, SensorLandscape = 4, SensorPortrait = 5, Sensor = 6 }
        public enum VSyncMode : long { Disabled = 0, Enabled = 1, Adaptive = 2, Mailbox = 3 }
        public enum WindowMode : long { Windowed = 0, Minimized = 1, Maximized = 2, Fullscreen = 3, ExclusiveFullscreen = 4 }
    }
    public partial class ENetConnection : global::Godot.RefCounted
    {
        public ENetConnection() { }
        public global::Godot.ENetPacketPeer ConnectToHost(string address, int port, int channels, int data) { return default; }
        public global::Godot.Error CreateHost(int maxPeers, int maxChannels, int inBandwidth, int outBandwidth) { return global::Godot.Error.Failed; }
        public global::Godot.Error CreateHostBound(string bindAddress, int bindPort, int maxPeers, int maxChannels, int inBandwidth, int outBandwidth) { return global::Godot.Error.Failed; }
        public void Destroy() { }
        public void Flush() { }
        public global::Godot.Collections.Array Service(int timeout) { return new(); }
        public enum EventType : long { Error = -1, None = 0, Connect = 1, Disconnect = 2, Receive = 3 }
    }
    public partial class ENetPacketPeer : global::Godot.PacketPeer
    {
        public global::Godot.ENetPacketPeer.PeerState GetState() { return default; }
        public bool IsActive() { return default; }
        public void PeerDisconnect(int data) { }
        public void PeerDisconnectLater(int data) { }
        public void PeerDisconnectNow(int data) { }
        public void Reset() { }
        public global::Godot.Error Send(int channel, byte[] packet, int flags) { return global::Godot.Error.Failed; }
        public void SetTimeout(int timeout, int timeoutMin, int timeoutMax) { }
        public enum PeerState : long { Disconnected = 0, Connecting = 1, AcknowledgingConnect = 2, ConnectionPending = 3, ConnectionSucceeded = 4, Connected = 5, DisconnectLater = 6, Disconnecting = 7, AcknowledgingDisconnect = 8, Zombie = 9 }
    }
    public partial class ExportToolButtonAttribute
    {
        public ExportToolButtonAttribute(string text) { }
    }
    public partial class FastNoiseLite
    {
        public void SetSeed(int seed) { }
        public float FractalGain { set { } }
        public int FractalOctaves { set { } }
        public float Frequency { set { } }
        public global::Godot.FastNoiseLite.NoiseTypeEnum NoiseType { set { } }
        public global::Godot.Vector3 Offset { get; set; }
        public int Seed { set { } }
        public enum NoiseTypeEnum : long { Value = 5, ValueCubic = 4, Perlin = 3, Cellular = 2, Simplex = 0, SimplexSmooth = 1 }
    }
    public partial class FileAccess
    {
        public void Flush() { }
        public byte[] GetBuffer(long length) { return global::System.Array.Empty<byte>(); }
        public global::Godot.Error GetError() { return global::Godot.Error.Failed; }
        public ulong GetLength() { return default; }
        public string GetLine() { return ""; }
        public static ulong GetModifiedTime(string file) { return default; }
        public static global::Godot.Error GetOpenError() { return global::Godot.Error.Failed; }
        public ulong GetPosition() { return default; }
        public static long GetSize(string file) { return default; }
        public bool IsOpen() { return default; }
        public void Seek(ulong position) { }
        public bool StoreBuffer(byte[] buffer) { return default; }
        public bool StoreLine(string line) { return default; }
    }
    public partial class FileDialog : global::Godot.ConfirmationDialog
    {
        public FileDialog() { }
        public global::Godot.FileDialog.AccessEnum Access { set { } }
        public string CurrentDir { set { } }
        public global::Godot.FileDialog.FileModeEnum FileMode { set { } }
        public string[] Filters { set { } }
        public bool UseNativeDialog { set { } }
        public enum AccessEnum : long { Resources = 0, Userdata = 1, Filesystem = 2 }
        public enum FileModeEnum : long { OpenFile = 0, OpenFiles = 1, OpenDir = 2, OpenAny = 3, SaveFile = 4 }
        public new partial class SignalName : global::Godot.ConfirmationDialog.SignalName
        {
            public static readonly global::Godot.StringName FileSelected = "file_selected";
        }
    }
    public partial class FlowContainer
    {
        public int GetLineCount() { return default; }
        public global::Godot.FlowContainer.AlignmentMode Alignment { set { } }
        public bool ReverseFill { set { } }
        public enum AlignmentMode : long { Begin = 0, Center = 1, End = 2 }
        public new partial class MethodName : global::Godot.Container.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Container.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Container.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class Font
    {
        public bool HasChar(long @char) { return default; }
    }
    public static partial class Geometry2D
    {
        public static global::Godot.Variant LineIntersectsLine(global::Godot.Vector2 fromA, global::Godot.Vector2 dirA, global::Godot.Vector2 fromB, global::Godot.Vector2 dirB) { return default; }
    }
    public partial class GodotObject
    {
        public global::Godot.Variant Call(global::Godot.StringName method, global::Godot.Variant[] args) { return default; }
        public global::Godot.Variant CallDeferred(global::Godot.StringName method, global::Godot.Variant[] args) { return default; }
        public virtual void Dispose() { }
        public global::Godot.Collections.Array<global::Godot.Collections.Dictionary> GetIncomingConnections() { return new(); }
        public global::Godot.Collections.Array<global::Godot.Collections.Dictionary> GetSignalConnectionList(global::Godot.StringName signal) { return new(); }
        public global::Godot.Collections.Array<global::Godot.Collections.Dictionary> GetSignalList() { return new(); }
        public bool HasMethod(global::Godot.StringName method) { return default; }
        public bool HasSignal(global::Godot.StringName signal) { return default; }
        public static global::Godot.GodotObject InstanceFromId(ulong instanceId) { return default; }
        protected internal virtual void RestoreGodotObjectData(global::Godot.Bridge.GodotSerializationInfo info) { }
        protected internal virtual void SaveGodotObjectData(global::Godot.Bridge.GodotSerializationInfo info) { }
        public void Set(global::Godot.StringName property, global::Godot.Variant value) { }
        public void SetDeferred(global::Godot.StringName property, global::Godot.Variant value) { }
        public void SetScript(global::Godot.Variant script) { }
        public virtual void _Notification(int what) { }
    }
    public partial class GpuParticles2D
    {
        public global::Godot.Material GetProcessMaterial() { return default; }
        public void SetEmitting(bool emitting) { }
        public void SetOneShot(bool secs) { }
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
            public static readonly global::Godot.StringName Finished = "finished";
        }
    }
    public partial class Gradient
    {
        public global::Godot.Color GetColor(int point) { return default; }
        public int GetPointCount() { return default; }
        public global::Godot.Color Sample(float offset) { return default; }
        public void SetColor(int point, global::Godot.Color color) { }
        public void SetOffset(int point, float offset) { }
    }
    public partial class GradientTexture2D
    {
        public global::Godot.Gradient Gradient { get; set; }
    }
    public partial class HBoxContainer
    {
        public new partial class MethodName : global::Godot.BoxContainer.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.BoxContainer.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.BoxContainer.SignalName
        {
            public SignalName() { }
        }
    }
    public enum HorizontalAlignment : long { Left = 0, Center = 1, Right = 2, Fill = 3 }
    public partial class Image
    {
        public void Convert(global::Godot.Image.Format format) { }
        public global::Godot.Image.Format GetFormat() { return default; }
        public int GetHeight() { return default; }
        public int GetWidth() { return default; }
        public static global::Godot.Image LoadFromFile(string path) { return default; }
        public void Resize(int width, int height, global::Godot.Image.Interpolation interpolation) { }
        public global::Godot.Error SavePng(string path) { return global::Godot.Error.Failed; }
        public byte[] SavePngToBuffer() { return global::System.Array.Empty<byte>(); }
        public global::Godot.Collections.Dictionary Data { get; set; } = new();
        public enum Interpolation : long { Nearest = 0, Bilinear = 1, Cubic = 2, Trilinear = 3, Lanczos = 4 }
    }
    public partial class ImageTexture
    {
        public static global::Godot.ImageTexture CreateFromImage(global::Godot.Image image) { return default; }
    }
    public enum InlineAlignment : long { TopTo = 0, CenterTo = 1, BaselineTo = 3, BottomTo = 2, ToTop = 0, ToCenter = 4, ToBaseline = 8, ToBottom = 12, Top = 0, Center = 5, Bottom = 14, ImageMask = 3, TextMask = 12 }
    public static partial class Input
    {
        public static global::Godot.Collections.Array<int> GetConnectedJoypads() { return new(); }
        public static string GetJoyName(int device) { return ""; }
        public static global::Godot.Vector2 GetVector(global::Godot.StringName negativeX, global::Godot.StringName positiveX, global::Godot.StringName negativeY, global::Godot.StringName positiveY, float deadzone) { return default; }
        public static bool IsActionJustPressed(global::Godot.StringName action, bool exactMatch) { return default; }
        public static bool IsActionJustReleased(global::Godot.StringName action, bool exactMatch) { return default; }
        public static bool IsActionPressed(global::Godot.StringName action, bool exactMatch) { return default; }
        public static bool IsKeyPressed(global::Godot.Key keycode) { return default; }
        public static void ParseInputEvent(global::Godot.InputEvent @event) { }
        public static void SetCustomMouseCursor(global::Godot.Resource image, global::Godot.Input.CursorShape shape, global::System.Nullable<global::Godot.Vector2> hotspot) { }
        public static void WarpMouse(global::Godot.Vector2 position) { }
        public static global::Godot.Input.MouseModeEnum MouseMode { get; set; }
        public enum CursorShape : long { Arrow = 0, Ibeam = 1, PointingHand = 2, Cross = 3, Wait = 4, Busy = 5, Drag = 6, CanDrop = 7, Forbidden = 8, Vsize = 9, Hsize = 10, Bdiagsize = 11, Fdiagsize = 12, Move = 13, Vsplit = 14, Hsplit = 15, Help = 16 }
        public enum MouseModeEnum : long { Visible = 0, Hidden = 1, Captured = 2, Confined = 3, ConfinedHidden = 4, Max = 5 }
    }
    public partial class InputEvent
    {
        public bool IsActionPressed(global::Godot.StringName action, bool allowEcho, bool exactMatch) { return default; }
        public bool IsActionReleased(global::Godot.StringName action, bool exactMatch) { return default; }
        public bool IsEcho() { return default; }
        public int Device { set { } }
    }
    public partial class InputEventAction
    {
        public bool Pressed { set { } }
    }
    public partial class InputEventFromWindow : global::Godot.InputEvent
    {
    }
    public partial class InputEventGesture : global::Godot.InputEventWithModifiers
    {
    }
    public partial class InputEventJoypadMotion
    {
    }
    public partial class InputEventKey
    {
        public global::Godot.Key Keycode { get; set; }
        public bool Pressed { get; set; }
    }
    public partial class InputEventMouse : global::Godot.InputEventWithModifiers
    {
        public global::Godot.Vector2 GlobalPosition { get; set; }
        public global::Godot.Vector2 Position { get; set; }
    }
    public partial class InputEventMouseButton
    {
        public global::Godot.MouseButton ButtonIndex { get; set; }
        public bool Pressed { get; set; }
    }
    public partial class InputEventMouseMotion
    {
        public global::Godot.Vector2 Velocity { get; set; }
    }
    public partial class InputEventPanGesture : global::Godot.InputEventGesture
    {
        public global::Godot.Vector2 Delta { get; set; }
    }
    public partial class InputEventWithModifiers : global::Godot.InputEventFromWindow
    {
        public bool IsCtrlPressed() { return default; }
        public bool IsShiftPressed() { return default; }
        public bool AltPressed { get; set; }
        public bool CtrlPressed { get; set; }
        public bool MetaPressed { get; set; }
    }
    public static partial class InputMap
    {
        public static bool HasAction(global::Godot.StringName action) { return default; }
    }
    public enum JoyAxis : long { Invalid = -1, LeftX = 0, LeftY = 1, RightX = 2, RightY = 3, TriggerLeft = 4, TriggerRight = 5, SdlMax = 6, Max = 10 }
    public partial class Label
    {
        public global::Godot.TextServer.AutowrapMode AutowrapMode { get; set; }
        public global::Godot.HorizontalAlignment HorizontalAlignment { set { } }
        public global::Godot.VerticalAlignment VerticalAlignment { set { } }
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class Line2D
    {
        public void AddPoint(global::Godot.Vector2 position, int index) { }
        public global::Godot.Gradient GetGradient() { return default; }
        public int GetPointCount() { return default; }
        public global::Godot.Vector2 GetPointPosition(int index) { return default; }
        public void RemovePoint(int index) { }
        public void SetGradient(global::Godot.Gradient color) { }
        public void SetPointPosition(int index, global::Godot.Vector2 position) { }
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class LineEdit
    {
        public void Edit() { }
        public bool IsEditing() { return default; }
        public void SetPlaceholder(string text) { }
        public void Unedit() { }
        public bool CaretBlink { set { } }
        public int CaretColumn { get; set; }
        public bool Editable { set { } }
        public event global::Godot.LineEdit.TextChangedEventHandler TextChanged;
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
            public static readonly global::Godot.StringName Deselect = "deselect";
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public delegate void TextChangedEventHandler(string newText);
    }
    public partial class MarginContainer
    {
        public new partial class MethodName : global::Godot.Container.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Container.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Container.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class MustBeVariantAttribute : global::System.Attribute
    {
        public MustBeVariantAttribute() { }
    }
    public partial class NinePatchRect
    {
        public int PatchMarginLeft { get; set; }
        public int PatchMarginRight { get; set; }
    }
    public partial class Node
    {
        public void SetProcess(bool enable) { }
        public void SetProcessInput(bool enable) { }
        public global::Godot.Node.ProcessModeEnum ProcessMode { set { } }
        public string SceneFilePath { get; set; } = "";
        public event global::System.Action TreeExiting;
        public partial class MethodName
        {
            public static readonly global::Godot.StringName AddSibling = "add_sibling";
            public static readonly global::Godot.StringName MoveChild = "move_child";
        }
        public enum ProcessModeEnum : long { Inherit = 0, Pausable = 1, WhenPaused = 2, Always = 3, Disabled = 4 }
        public partial class SignalName
        {
            public static readonly global::Godot.StringName ChildEnteredTree = "child_entered_tree";
            public static readonly global::Godot.StringName ChildExitingTree = "child_exiting_tree";
            public static readonly global::Godot.StringName Ready = "ready";
            public static readonly global::Godot.StringName TreeExited = "tree_exited";
            public static readonly global::Godot.StringName TreeExiting = "tree_exiting";
        }
    }
    public partial class Node2D
    {
        public float GetAngleTo(global::Godot.Vector2 point) { return default; }
        public void Rotate(float radians) { }
        public global::Godot.Vector2 ToLocal(global::Godot.Vector2 globalPoint) { return default; }
        public float GlobalRotation { set { } }
        public global::Godot.Vector2 GlobalScale { get; set; }
        public float Skew { get; set; }
    }
    public partial class Noise : global::Godot.Resource
    {
        public float GetNoise1D(float x) { return default; }
        public float GetNoise2D(float x, float y) { return default; }
    }
    public partial class NoiseTexture2D : global::Godot.Texture2D
    {
        public global::Godot.Noise Noise { get; set; }
    }
    public partial class OS
    {
        public static void Crash(string message) { }
        public static string[] GetCmdlineUserArgs() { return global::System.Array.Empty<string>(); }
        public static string GetDistributionName() { return ""; }
        public static string[] GetGrantedPermissions() { return global::System.Array.Empty<string>(); }
        public static global::Godot.Collections.Dictionary GetMemoryInfo() { return new(); }
        public static string GetModelName() { return ""; }
        public static string GetProcessorName() { return ""; }
        public static ulong GetStaticMemoryPeakUsage() { return default; }
        public static ulong GetStaticMemoryUsage() { return default; }
        public static bool IsInLowProcessorUsageMode() { return default; }
        public static bool IsSandboxed() { return default; }
        public static bool IsStdOutVerbose() { return default; }
        public static bool IsUserfsPersistent() { return default; }
        public static global::Godot.Error ShellShowInFileManager(string fileOrDirPath, bool openFolder) { return global::Godot.Error.Failed; }
    }
    public partial class PacketPeer : global::Godot.RefCounted
    {
        public byte[] GetPacket() { return global::System.Array.Empty<byte>(); }
        public global::Godot.Error GetPacketError() { return global::Godot.Error.Failed; }
    }
    public partial class Panel
    {
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class ParticleProcessMaterial
    {
        public global::Godot.Color Color { set { } }
        public global::Godot.Vector3 EmissionShapeOffset { set { } }
        public global::Godot.Vector3 EmissionShapeScale { set { } }
        public float HueVariationMax { set { } }
        public float HueVariationMin { set { } }
        public global::Godot.Vector2 Scale { set { } }
        public float ScaleMax { set { } }
        public float ScaleMin { set { } }
    }
    public partial class Path2D
    {
        public global::Godot.Curve2D Curve { get; set; }
    }
    public partial class PathFollow2D
    {
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
        }
    }
    public static partial class Performance
    {
        public static double GetMonitor(global::Godot.Performance.Monitor monitor) { return default; }
        public enum Monitor : long { TimeFps = 0, TimeProcess = 1, TimePhysicsProcess = 2, TimeNavigationProcess = 3, MemoryStatic = 4, MemoryStaticMax = 5, MemoryMessageBufferMax = 6, ObjectCount = 7, ObjectResourceCount = 8, ObjectNodeCount = 9, ObjectOrphanNodeCount = 10, RenderTotalObjectsInFrame = 11, RenderTotalPrimitivesInFrame = 12, RenderTotalDrawCallsInFrame = 13, RenderVideoMemUsed = 14, RenderTextureMemUsed = 15, RenderBufferMemUsed = 16, Physics2DActiveObjects = 17, Physics2DCollisionPairs = 18, Physics2DIslandCount = 19, Physics3DActiveObjects = 20, Physics3DCollisionPairs = 21, Physics3DIslandCount = 22, AudioOutputLatency = 23, NavigationActiveMaps = 24, NavigationRegionCount = 25, NavigationAgentCount = 26, NavigationLinkCount = 27, NavigationPolygonCount = 28, NavigationEdgeCount = 29, NavigationEdgeMergeCount = 30, NavigationEdgeConnectionCount = 31, NavigationEdgeFreeCount = 32, NavigationObstacleCount = 33, PipelineCompilationsCanvas = 34, PipelineCompilationsMesh = 35, PipelineCompilationsSurface = 36, PipelineCompilationsDraw = 37, PipelineCompilationsSpecialization = 38, Navigation2DActiveMaps = 39, Navigation2DRegionCount = 40, Navigation2DAgentCount = 41, Navigation2DLinkCount = 42, Navigation2DPolygonCount = 43, Navigation2DEdgeCount = 44, Navigation2DEdgeMergeCount = 45, Navigation2DEdgeConnectionCount = 46, Navigation2DEdgeFreeCount = 47, Navigation2DObstacleCount = 48, Navigation3DActiveMaps = 49, Navigation3DRegionCount = 50, Navigation3DAgentCount = 51, Navigation3DLinkCount = 52, Navigation3DPolygonCount = 53, Navigation3DEdgeCount = 54, Navigation3DEdgeMergeCount = 55, Navigation3DEdgeConnectionCount = 56, Navigation3DEdgeFreeCount = 57, Navigation3DObstacleCount = 58, MonitorMax = 59 }
    }
    public partial class ProjectSettings
    {
        public static bool LoadResourcePack(string pack, bool replaceFiles, int offset) { return default; }
    }
    public partial class PropertyTweener
    {
        public global::Godot.PropertyTweener FromCurrent() { return default; }
    }
    public partial class Range
    {
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
    }
    public partial class RefCounted : global::Godot.GodotObject
    {
        public new partial class SignalName : global::Godot.GodotObject.SignalName
        {
        }
    }
    public partial class RenderingDevice : global::Godot.GodotObject
    {
        public string GetDeviceName() { return ""; }
    }
    public partial class RenderingServer
    {
        public static global::Godot.RenderingDevice GetRenderingDevice() { return default; }
        public static ulong GetRenderingInfo(global::Godot.RenderingServer.RenderingInfo info) { return default; }
        public static void ViewportSetMsaa2D(global::Godot.Rid viewport, global::Godot.RenderingServer.ViewportMsaa msaa) { }
        public static global::Godot.RenderingServerInstance Singleton { get; set; } = new();
        public enum RenderingInfo : long { TotalObjectsInFrame = 0, TotalPrimitivesInFrame = 1, TotalDrawCallsInFrame = 2, TextureMemUsed = 3, BufferMemUsed = 4, VideoMemUsed = 5, PipelineCompilationsCanvas = 6, PipelineCompilationsMesh = 7, PipelineCompilationsSurface = 8, PipelineCompilationsDraw = 9, PipelineCompilationsSpecialization = 10 }
        public partial class SignalName
        {
            public static readonly global::Godot.StringName FramePostDraw = "frame_post_draw";
        }
    }
    public partial class RenderingServerInstance : global::Godot.GodotObject
    {
    }
    public partial class ResourceLoader
    {
        public static void AddResourceFormatLoader(global::Godot.ResourceFormatLoader formatLoader, bool atFront) { }
        public static global::Godot.Resource LoadThreadedGet(string path) { return default; }
        public static global::Godot.ResourceLoader.ThreadLoadStatus LoadThreadedGetStatus(string path, global::Godot.Collections.Array progress) { return default; }
        public static global::Godot.Error LoadThreadedRequest(string path, string typeHint, bool useSubThreads, global::Godot.ResourceLoader.CacheMode cacheMode) { return global::Godot.Error.Failed; }
        public enum ThreadLoadStatus : long { InvalidResource = 0, InProgress = 1, Failed = 2, Loaded = 3 }
    }
    public partial class RichTextEffect
    {
        public new partial class MethodName : global::Godot.Resource.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Resource.PropertyName
        {
            public PropertyName() { }
        }
    }
    public partial class RichTextLabel
    {
        public int GetTotalCharacterCount() { return default; }
        public void InstallEffect(global::Godot.Variant effect) { }
        public void ParseBbcode(string bbcode) { }
        public void ScrollToLine(int line) { }
        public void SetText(string text) { }
        public global::Godot.TextServer.AutowrapMode AutowrapMode { set { } }
        public bool BbcodeEnabled { get; set; }
        public global::Godot.Collections.Array CustomEffects { get; set; } = new();
        public bool FitContent { get; set; }
        public global::Godot.HorizontalAlignment HorizontalAlignment { set { } }
        public global::Godot.VerticalAlignment VerticalAlignment { set { } }
        public float VisibleRatio { set { } }
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
        }
    }
    public partial struct Rid
    {
    }
    public partial class SceneTree
    {
        public global::Godot.Node GetEditedSceneRoot() { return default; }
        public long GetFrame() { return default; }
        public void Quit(int exitCode) { }
        public bool Paused { get; set; }
    }
    public partial class SceneTreeTimer
    {
        public new partial class SignalName : global::Godot.RefCounted.SignalName
        {
            public static readonly global::Godot.StringName Timeout = "timeout";
        }
    }
    public enum Side : long { Left = 0, Top = 1, Right = 2, Bottom = 3 }
    public partial class Sprite2D
    {
        public bool FlipH { set { } }
        public new partial class MethodName : global::Godot.Node2D.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Node2D.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Node2D.SignalName
        {
            public SignalName() { }
        }
    }
    public partial class StringName
    {
        public static bool operator ==(in global::Godot.NativeInterop.godot_string_name left, global::Godot.StringName right) {  return default; }
        public static bool operator !=(in global::Godot.NativeInterop.godot_string_name left, global::Godot.StringName right) {  return default; }
    }
    public partial class StyleBox : global::Godot.Resource
    {
    }
    public partial class SubViewport
    {
        public global::Godot.SubViewport.UpdateMode RenderTargetUpdateMode { set { } }
        public global::Godot.Vector2I Size { get; set; }
        public global::Godot.Vector2I Size2DOverride { set { } }
        public enum UpdateMode : long { Disabled = 0, Once = 1, WhenVisible = 2, WhenParentVisible = 3, Always = 4 }
    }
    public partial class TextEdit
    {
        public int GetCaretColumn(int caretIndex) { return default; }
        public int GetCaretLine(int caretIndex) { return default; }
        public void SetCaretColumn(int column, bool adjustViewport, int caretIndex) { }
        public void SetCaretLine(int line, bool adjustViewport, bool canBeHidden, int wrapIndex, int caretIndex) { }
        public string PlaceholderText { set { } }
        public new partial class MethodName : global::Godot.Control.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.Control.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.Control.SignalName
        {
            public SignalName() { }
            public static readonly global::Godot.StringName TextChanged = "text_changed";
        }
    }
    public partial class TextParagraph
    {
        public bool AddObject(global::Godot.Variant key, global::Godot.Vector2 size, global::Godot.InlineAlignment inlineAlign, int length, float baseline) { return default; }
        public bool AddString(string text, global::Godot.Font font, int fontSize, string language, global::Godot.Variant meta) { return default; }
        public int GetLineCount() { return default; }
        public global::Godot.Rid GetLineRid(int line) { return default; }
        public global::Godot.HorizontalAlignment Alignment { set { } }
        public global::Godot.TextServer.LineBreakFlag BreakFlags { set { } }
        public global::Godot.TextServer.Direction Direction { set { } }
        public global::Godot.TextServer.JustificationFlag JustificationFlags { set { } }
        public int MaxLinesVisible { set { } }
        public global::Godot.TextServer.Orientation Orientation { set { } }
        public global::Godot.TextServer.OverrunBehavior TextOverrunBehavior { set { } }
        public float Width { set { } }
    }
    public partial class TextServer : global::Godot.RefCounted
    {
        public long FontGetCharFromGlyphIndex(global::Godot.Rid fontRid, long size, long glyphIndex) { return default; }
        public long FontGetGlyphIndex(global::Godot.Rid fontRid, long size, long @char, long variationSelector) { return default; }
        public global::Godot.Collections.Array<global::Godot.Collections.Dictionary> ShapedTextGetGlyphs(global::Godot.Rid shaped) { return new(); }
        public enum AutowrapMode : long { Off = 0, Arbitrary = 1, Word = 2, WordSmart = 3 }
        public enum Direction : long { Auto = 0, Ltr = 1, Rtl = 2, Inherited = 3 }
        [global::System.Flags] public enum JustificationFlag : long { None = 0, Kashida = 1, WordBound = 2, TrimEdgeSpaces = 4, AfterLastTab = 8, ConstrainEllipsis = 16, SkipLastLine = 32, SkipLastLineWithVisibleChars = 64, DoNotSkipSingleLine = 128 }
        [global::System.Flags] public enum LineBreakFlag : long { None = 0, Mandatory = 1, WordBound = 2, GraphemeBound = 4, Adaptive = 8, TrimEdgeSpaces = 16, TrimIndent = 32, TrimStartEdgeSpaces = 64, TrimEndEdgeSpaces = 128 }
        public enum Orientation : long { Horizontal = 0, Vertical = 1 }
        public enum OverrunBehavior : long { NoTrimming = 0, TrimChar = 1, TrimWord = 2, TrimEllipsis = 3, TrimWordEllipsis = 4, TrimEllipsisForce = 5, TrimWordEllipsisForce = 6 }
    }
    public static partial class TextServerManager
    {
        public static global::Godot.TextServerManagerInstance Singleton { get; set; } = new();
    }
    public partial class TextServerManagerInstance : global::Godot.GodotObject
    {
        public global::Godot.TextServer GetPrimaryInterface() { return default; }
    }
    public partial class Texture2D
    {
        public global::Godot.Image GetImage() { return default; }
        public global::Godot.Vector2 GetSize() { return default; }
        public int GetWidth() { return default; }
    }
    public partial class TextureRect
    {
        public void SetFlipV(bool enable) { }
        public void SetTexture(global::Godot.Texture2D texture) { }
        public global::Godot.TextureRect.ExpandModeEnum ExpandMode { set { } }
        public bool FlipH { set { } }
        public global::Godot.TextureRect.StretchModeEnum StretchMode { set { } }
        public enum ExpandModeEnum : long { KeepSize = 0, IgnoreSize = 1, FitWidth = 2, FitWidthProportional = 3, FitHeight = 4, FitHeightProportional = 5 }
        public enum StretchModeEnum : long { Scale = 0, Tile = 1, Keep = 2, KeepCentered = 3, KeepAspect = 4, KeepAspectCentered = 5, KeepAspectCovered = 6 }
    }
    public partial class Timer
    {
        public new partial class SignalName : global::Godot.Node.SignalName
        {
            public static readonly global::Godot.StringName Timeout = "timeout";
        }
    }
    public partial class VBoxContainer
    {
        public new partial class MethodName : global::Godot.BoxContainer.MethodName
        {
            public MethodName() { }
        }
        public new partial class PropertyName : global::Godot.BoxContainer.PropertyName
        {
            public PropertyName() { }
        }
        public new partial class SignalName : global::Godot.BoxContainer.SignalName
        {
            public SignalName() { }
        }
    }
    public enum VerticalAlignment : long { Top = 0, Center = 1, Bottom = 2, Fill = 3 }
    public partial class Viewport
    {
        public global::Godot.Transform2D GetStretchTransform() { return default; }
        public global::Godot.ViewportTexture GetTexture() { return default; }
        public global::Godot.Rid GetViewportRid() { return default; }
        public global::Godot.Control GuiGetFocusOwner() { return default; }
        public void GuiReleaseFocus() { }
        public void SetInputAsHandled() { }
        public partial class SignalName
        {
            public static readonly global::Godot.StringName SizeChanged = "size_changed";
        }
    }
    public partial class ViewportTexture : global::Godot.Texture2D
    {
    }
    public partial class Window
    {
        public bool HasFocus() { return default; }
        public void Show() { }
        public global::Godot.Window.ContentScaleAspectEnum ContentScaleAspect { set { } }
        public global::Godot.Vector2I ContentScaleSize { get; set; }
        public int CurrentScreen { get; set; }
        public global::Godot.Vector2I Size { get; set; }
        public string Title { set { } }
        public bool Unresizable { get; set; }
        public enum ContentScaleAspectEnum : long { Ignore = 0, Keep = 1, KeepWidth = 2, KeepHeight = 3, Expand = 4 }
        public partial class SignalName
        {
            public static readonly global::Godot.StringName FilesDropped = "files_dropped";
        }
    }
}

namespace Godot.Bridge
{
    public partial class GodotSerializationInfo
    {
        public void AddProperty(global::Godot.StringName name, global::Godot.Variant value) { }
        public void AddSignalEventDelegate(global::Godot.StringName name, global::System.Delegate eventDelegate) { }
        public bool TryGetProperty(global::Godot.StringName name, out global::Godot.Variant value) { value = default; return default; }
        public bool TryGetSignalEventDelegate<T>(global::Godot.StringName name, out T value) { value = default; return default; }
    }
    public partial struct ManagedCallbacks
    {
        public static void Create(nint outManagedCallbacks) { }
    }
    public partial struct MethodInfo
    {
        public MethodInfo(global::Godot.StringName name, global::Godot.Bridge.PropertyInfo returnVal, global::Godot.MethodFlags flags, global::System.Collections.Generic.List<global::Godot.Bridge.PropertyInfo> arguments, global::System.Collections.Generic.List<global::Godot.Variant> defaultArguments) { }
    }
    public partial struct PropertyInfo
    {
        public PropertyInfo(global::Godot.Variant.Type type, global::Godot.StringName name, global::Godot.PropertyHint hint, string hintString, global::Godot.PropertyUsageFlags usage, global::Godot.StringName className, bool exported) { }
        public PropertyInfo(global::Godot.Variant.Type type, global::Godot.StringName name, global::Godot.PropertyHint hint, string hintString, global::Godot.PropertyUsageFlags usage, bool exported) { }
    }
    public partial class ScriptManagerBridge
    {
        public static void LookupScriptsInAssembly(global::System.Reflection.Assembly assembly) { }
    }
}

namespace Godot.NativeInterop
{
    public static partial class GodotBoolExtensions
    {
        public static global::Godot.NativeInterop.godot_bool ToGodotBool(bool @bool) { return default; }
    }
    public partial class GodotDllImportResolver
    {
        public GodotDllImportResolver(nint internalHandle) { }
        public nint OnResolveDllImport(string libraryName, global::System.Reflection.Assembly assembly, global::System.Nullable<global::System.Runtime.InteropServices.DllImportSearchPath> searchPath) { return default; }
    }
    public static partial class NativeFuncs
    {
        public static void Initialize(nint unmanagedCallbacks, int unmanagedCallbacksSize) { }
    }
    public partial class VariantUtils
    {
        public static T ConvertTo<T>(in global::Godot.NativeInterop.godot_variant variant) { return default; }
        public static global::Godot.Collections.Array<T> ConvertToArray<T>(in global::Godot.NativeInterop.godot_variant p_var) { return new(); }
        public static global::Godot.Collections.Dictionary<TKey,TValue> ConvertToDictionary<TKey, TValue>(in global::Godot.NativeInterop.godot_variant p_var) { return new(); }
        public static T[] ConvertToSystemArrayOfGodotObject<T>(in global::Godot.NativeInterop.godot_variant p_var) { return global::System.Array.Empty<T>(); }
        public static global::Godot.NativeInterop.godot_variant CreateFrom<T>(in T from) { return default; }
        public static global::Godot.NativeInterop.godot_variant CreateFromArray<T>(global::Godot.Collections.Array<T> from) { return default; }
        public static global::Godot.NativeInterop.godot_variant CreateFromDictionary<TKey, TValue>(global::Godot.Collections.Dictionary<TKey,TValue> from) { return default; }
        public static global::Godot.NativeInterop.godot_variant CreateFromSystemArrayOfGodotObject(global::Godot.GodotObject[] from) { return default; }
    }
}
